/* Generated by zerodds idl-cpp c_mode. Do not edit. */
#ifndef ZERODDS_GENERATED_H
#define ZERODDS_GENERATED_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "zerodds_xcdr2.h"
#ifdef __cplusplus
extern "C" {
#endif

#ifndef ZERODDS_X2_ALIGN4_8BYTE
#define ZERODDS_X2_ALIGN4_8BYTE
static inline int zd_x2_write_u64(uint8_t** buf, size_t* len, size_t* cap, uint64_t v) {
    if (zerodds_xcdr2_c_pad_to(buf, len, cap, 4) != 0) return -1;
    if (zerodds_xcdr2_c_grow(buf, cap, *len + 8) != 0) return -1;
    for (int i = 0; i < 8; ++i) { (*buf)[(*len)++] = (uint8_t)((v >> (8 * i)) & 0xFFu); }
    return 0;
}
static inline int zd_x2_write_i64(uint8_t** buf, size_t* len, size_t* cap, int64_t v) { return zd_x2_write_u64(buf, len, cap, (uint64_t)v); }
static inline int zd_x2_write_f64(uint8_t** buf, size_t* len, size_t* cap, double v) { uint64_t u; memcpy(&u, &v, sizeof(u)); return zd_x2_write_u64(buf, len, cap, u); }
static inline int zd_x2_read_u64(const uint8_t* buf, size_t len, size_t* pos, uint64_t* out) {
    if (zerodds_xcdr2_c_pad_read(buf, len, pos, 4) != 0) return -1;
    if (*pos + 8 > len) return -1;
    uint64_t v = 0;
    for (int i = 0; i < 8; ++i) { v |= (uint64_t)buf[*pos + (size_t)i] << (8 * i); }
    *pos += 8; *out = v; return 0;
}
static inline int zd_x2_read_i64(const uint8_t* buf, size_t len, size_t* pos, int64_t* out) { uint64_t u; int rc = zd_x2_read_u64(buf, len, pos, &u); if (rc != 0) return rc; *out = (int64_t)u; return 0; }
static inline int zd_x2_read_f64(const uint8_t* buf, size_t len, size_t* pos, double* out) { uint64_t u; int rc = zd_x2_read_u64(buf, len, pos, &u); if (rc != 0) return rc; memcpy(out, &u, sizeof(*out)); return 0; }
#endif

typedef int32_t combo_Mode_t;
enum { combo_Mode_MODE_IDLE = 0 };
enum { combo_Mode_MODE_ACTIVE = 1 };
enum { combo_Mode_MODE_FAULT = 2 };

typedef struct combo_Reading_s {
    combo_Mode_t _d;
    union {
        int32_t idleTicks;
        double activeRate;
        char* faultCode;
    } _u;
} combo_Reading_t;

typedef struct combo_Sample_s {
    int32_t seq;
    double value;
} combo_Sample_t;

static int combo_Sample_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int combo_Sample_decode(const uint8_t* buf, size_t len, void* out_sample);
static void combo_Sample_sample_free(void* sample);

static const char combo_Sample_type_name[] = "combo::Sample";
static const zerodds_typesupport_t combo_Sample_typesupport = {
    .type_hash = {0},
    .type_name = combo_Sample_type_name,
    .is_keyed = 0,
    .extensibility = 0,
    ._reserved = {0},
    .encode = combo_Sample_encode,
    .decode = combo_Sample_decode,
    .key_hash = NULL,
    .sample_free = combo_Sample_sample_free,
};

static int combo_Sample_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const combo_Sample_t* s = (const combo_Sample_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->seq) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->value) != 0) goto fail;
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int combo_Sample_decode(const uint8_t* buf, size_t len, void* out_sample) {
    combo_Sample_t* s = (combo_Sample_t*)out_sample;
    size_t pos = 0;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->seq)) != 0) return -7;
    if (zd_x2_read_f64(buf, len, &pos, &(s->value)) != 0) return -7;
    (void)s;
    return 0;
}

static void combo_Sample_sample_free(void* sample) {
    if (sample == NULL) return;
    combo_Sample_t* s = (combo_Sample_t*)sample;
    (void)s;
}

static int combo_Reading_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int combo_Reading_decode(const uint8_t* buf, size_t len, void* out_sample);
static void combo_Reading_sample_free(void* sample);

static const char combo_Reading_type_name[] = "combo::Reading";
static const zerodds_typesupport_t combo_Reading_typesupport = {
    .type_hash = {0},
    .type_name = combo_Reading_type_name,
    .is_keyed = 0,
    .extensibility = 0,
    ._reserved = {0},
    .encode = combo_Reading_encode,
    .decode = combo_Reading_decode,
    .key_hash = NULL,
    .sample_free = combo_Reading_sample_free,
};

static int combo_Reading_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const combo_Reading_t* s = (const combo_Reading_t*)sample;
    (void)s;
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (int32_t)(((*s))._d)) != 0) goto fail;
    switch (((*s))._d) {
    case 0:
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((*s))._u.idleTicks) != 0) goto fail;
        break;
    case 1:
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, ((*s))._u.activeRate) != 0) goto fail;
        break;
    default:
    if ((((*s))._u.faultCode) != NULL && strlen(((*s))._u.faultCode) > 16u) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, ((*s))._u.faultCode) != 0) goto fail;
        break;
    }
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int combo_Reading_decode(const uint8_t* buf, size_t len, void* out_sample) {
    combo_Reading_t* s = (combo_Reading_t*)out_sample;
    size_t pos = 0;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, (int32_t*)&(((*s))._d)) != 0) return -7;
    switch (((*s))._d) {
    case 0:
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((*s))._u.idleTicks)) != 0) return -7;
        break;
    case 1:
    if (zd_x2_read_f64(buf, len, &pos, &(((*s))._u.activeRate)) != 0) return -7;
        break;
    default:
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(((*s))._u.faultCode)) != 0) return -7;
        break;
    }
    (void)s;
    return 0;
}

static void combo_Reading_sample_free(void* sample) {
    if (sample == NULL) return;
    combo_Reading_t* s = (combo_Reading_t*)sample;
    (void)s;
}

typedef struct combo_Telemetry_s {
    int32_t unitId;
    char* region;
    combo_Mode_t mode;
    double batteryCurrent;
    struct { uint32_t len; combo_Sample_t* elems; } history;
    combo_Reading_t reading;
    struct { uint32_t len; char** keys; int32_t* vals; } counters;
    double calibration;
    uint8_t calibration_present;
    int32_t window[4];
} combo_Telemetry_t;

static int combo_Telemetry_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int combo_Telemetry_decode(const uint8_t* buf, size_t len, void* out_sample);
static void combo_Telemetry_sample_free(void* sample);
static int combo_Telemetry_key_hash(const void* sample, uint8_t out_hash[16]);

static const char combo_Telemetry_type_name[] = "combo::Telemetry";
static const zerodds_typesupport_t combo_Telemetry_typesupport = {
    .type_hash = {0},
    .type_name = combo_Telemetry_type_name,
    .is_keyed = 1,
    .extensibility = 1,
    ._reserved = {0},
    .encode = combo_Telemetry_encode,
    .decode = combo_Telemetry_decode,
    .key_hash = combo_Telemetry_key_hash,
    .sample_free = combo_Telemetry_sample_free,
};

static int combo_Telemetry_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const combo_Telemetry_t* s = (const combo_Telemetry_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->unitId) != 0) goto fail;
    if ((s->region) != NULL && strlen(s->region) > 32u) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, s->region) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (int32_t)(s->mode)) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->batteryCurrent) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t seq_dheader_pos = w_len;
    w_len += 4;
    size_t seq_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->history).len) != 0) goto fail;
    for (uint32_t i0 = 0; i0 < (s->history).len; ++i0) {
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->history).elems[i0]).seq) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, ((s->history).elems[i0]).value) != 0) goto fail;
    }
    uint32_t seq_dheader_len = (uint32_t)(w_len - seq_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, seq_dheader_pos, seq_dheader_len);
    }
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (int32_t)((s->reading)._d)) != 0) goto fail;
    switch ((s->reading)._d) {
    case 0:
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->reading)._u.idleTicks) != 0) goto fail;
        break;
    case 1:
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, (s->reading)._u.activeRate) != 0) goto fail;
        break;
    default:
    if (((s->reading)._u.faultCode) != NULL && strlen((s->reading)._u.faultCode) > 16u) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, (s->reading)._u.faultCode) != 0) goto fail;
        break;
    }
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t map_dheader_pos = w_len;
    w_len += 4;
    size_t map_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->counters).len) != 0) goto fail;
    for (uint32_t mi0 = 0; mi0 < (s->counters).len; ++mi0) {
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, (s->counters).keys[mi0]) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->counters).vals[mi0]) != 0) goto fail;
    }
    uint32_t map_dheader_len = (uint32_t)(w_len - map_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, map_dheader_pos, map_dheader_len);
    }
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->calibration_present ? 1 : 0) != 0) goto fail;
    if (s->calibration_present) {
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->calibration) != 0) goto fail;
    }
    for (uint32_t ai0 = 0; ai0 < 4; ++ai0) {
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->window[ai0]) != 0) goto fail;
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int combo_Telemetry_decode(const uint8_t* buf, size_t len, void* out_sample) {
    combo_Telemetry_t* s = (combo_Telemetry_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->unitId)) != 0) return -7;
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(s->region)) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, (int32_t*)&(s->mode)) != 0) return -7;
    if (zd_x2_read_f64(buf, len, &pos, &(s->batteryCurrent)) != 0) return -7;
    {
        uint32_t seq_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_dheader) != 0) return -7;
        (void)seq_dheader;
        uint32_t seq_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_len) != 0) return -7;
        (s->history).len = seq_len;
        (s->history).elems = (combo_Sample_t*)calloc(seq_len ? seq_len : 1, sizeof(combo_Sample_t));
        if ((s->history).elems == NULL && seq_len > 0) return -7;
        for (uint32_t i0 = 0; i0 < seq_len; ++i0) {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->history).elems[i0]).seq)) != 0) return -7;
    if (zd_x2_read_f64(buf, len, &pos, &(((s->history).elems[i0]).value)) != 0) return -7;
        }
    }
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, (int32_t*)&((s->reading)._d)) != 0) return -7;
    switch ((s->reading)._d) {
    case 0:
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->reading)._u.idleTicks)) != 0) return -7;
        break;
    case 1:
    if (zd_x2_read_f64(buf, len, &pos, &((s->reading)._u.activeRate)) != 0) return -7;
        break;
    default:
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &((s->reading)._u.faultCode)) != 0) return -7;
        break;
    }
    {
        uint32_t map_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &map_dheader) != 0) return -7;
        (void)map_dheader;
        uint32_t map_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &map_len) != 0) return -7;
        (s->counters).len = map_len;
        (s->counters).keys = (char**)calloc(map_len ? map_len : 1, sizeof(char*));
        (s->counters).vals = (int32_t*)calloc(map_len ? map_len : 1, sizeof(int32_t));
        if ((((s->counters).keys == NULL) || ((s->counters).vals == NULL)) && map_len > 0) return -7;
        for (uint32_t mi0 = 0; mi0 < map_len; ++mi0) {
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &((s->counters).keys[mi0])) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->counters).vals[mi0])) != 0) return -7;
        }
    }
    {
        uint8_t present = 0;
        if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &present) != 0) return -7;
        s->calibration_present = present;
        if (present) {
    if (zd_x2_read_f64(buf, len, &pos, &(s->calibration)) != 0) return -7;
        }
    }
    for (uint32_t ri0 = 0; ri0 < 4; ++ri0) {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->window[ri0])) != 0) return -7;
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void combo_Telemetry_sample_free(void* sample) {
    if (sample == NULL) return;
    combo_Telemetry_t* s = (combo_Telemetry_t*)sample;
    (void)s;
    free(s->region); s->region = NULL;
    free((s->history).elems); (s->history).elems = NULL; (s->history).len = 0;
    for (uint32_t fki = 0; fki < (s->counters).len; ++fki) free((s->counters).keys[fki]);
    free((s->counters).keys); (s->counters).keys = NULL;
    free((s->counters).vals); (s->counters).vals = NULL; (s->counters).len = 0;
    for (uint32_t fi0 = 0; fi0 < 4; ++fi0) {
    }
}

static int combo_Telemetry_key_hash(const void* sample, uint8_t out_hash[16]) {
    const combo_Telemetry_t* s = (const combo_Telemetry_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->unitId) != 0) { free(kh_buf); return -1; }
    if (zerodds_xcdr2_c_kh_write_string(&kh_buf, &kh_len, &kh_cap, s->region) != 0) { free(kh_buf); return -1; }
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

#ifdef __cplusplus
}
#endif
#endif

/* XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised) */
static const unsigned char combo_Mode_type_object[] = {
    0x40, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xdb, 0x78, 0xd3, 0x17, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x15, 0xd1, 0xdf, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb2, 0xc5, 0xb2, 0x9f,
};
static const unsigned char combo_CurrentInAmpsType_type_object[] = {
    0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a,
};
static const unsigned char combo_Sample_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe0, 0x68, 0xc2, 0xde, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x20, 0x63, 0xc1, 0x60,
};
static const unsigned char combo_Reading_type_object[] = {
    0x51, 0x00, 0x02, 0x00, 0x00, 0x00, 0xf1, 0x31, 0xcc, 0xe6, 0x28, 0xbb,
    0xdf, 0x5a, 0xc9, 0x28, 0x23, 0xc7, 0x8a, 0x34, 0x7c, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xc2, 0x90, 0x82, 0x81,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0xe5, 0xf9, 0x08, 0xde, 0x03, 0x00, 0x00, 0x00,
    0x40, 0x00, 0x70, 0x10, 0x00, 0x00, 0x00, 0x00, 0x60, 0x1f, 0x94, 0x40,
};
static const unsigned char combo_Telemetry_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x3a, 0xe0, 0xf2, 0xbc, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x70, 0x20, 0x96, 0x0d, 0xb2, 0xed,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x31, 0xcc, 0xe6, 0x28, 0xbb,
    0xdf, 0x5a, 0xc9, 0x28, 0x23, 0xc7, 0x8a, 0x34, 0x7c, 0x15, 0xd6, 0x17,
    0x12, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x9b,
    0x3f, 0x0e, 0xd4, 0x20, 0x14, 0x6c, 0x00, 0xc6, 0xd1, 0x0e, 0xff, 0xb3,
    0x5a, 0x9d, 0x04, 0xf4, 0xe2, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0xf1, 0x00, 0x00, 0x00, 0xf1, 0x80, 0xf9, 0xa0, 0x9d,
    0x09, 0xf3, 0x9b, 0x8e, 0x8e, 0x3a, 0x55, 0x17, 0x44, 0xc1, 0x3c, 0xd1,
    0x5f, 0x8f, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x57,
    0xd7, 0xce, 0x95, 0xf7, 0xae, 0xe2, 0x3d, 0x50, 0x74, 0xdf, 0xfa, 0x32,
    0xc2, 0xec, 0xea, 0xdc, 0x1d, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xa0, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x70, 0x00,
    0x09, 0x76, 0xbd, 0xd4, 0x08, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0a, 0x0b,
    0xf7, 0x19, 0xdf, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x05,
    0xb8, 0xc7, 0x4c,
};
