// Generated by zerodds idl-cpp. Do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "dds/topic/TopicTraits.hpp"
#include "dds/topic/xcdr2.hpp"
#include "dds/topic/xcdr2_md5.hpp"

namespace feat {
    class WStr {
    public:
        WStr() = default;
        ~WStr() = default;
        WStr(std::wstring label, std::wstring text)
            : label_(std::move(label)), text_(std::move(text)) {}

    private:
        std::wstring label_;
        std::wstring text_;

    public:
        std::wstring& label() { return label_; }
        const std::wstring& label() const { return label_; }
        void label(const std::wstring& value) { label_ = value; }
        std::wstring& text() { return text_; }
        const std::wstring& text() const { return text_; }
        void text(const std::wstring& value) { text_ = value; }
    };

    class Mut {
    public:
        Mut() = default;
        ~Mut() = default;
        Mut(int32_t a, double b, std::string c)
            : a_(std::move(a)), b_(std::move(b)), c_(std::move(c)) {}

    private:
        int32_t a_;
        double b_;
        std::string c_;

    public:
        int32_t& a() { return a_; }
        const int32_t& a() const { return a_; }
        void a(const int32_t& value) { a_ = value; }
        double& b() { return b_; }
        const double& b() const { return b_; }
        void b(const double& value) { b_ = value; }
        std::string& c() { return c_; }
        const std::string& c() const { return c_; }
        void c(const std::string& value) { c_ = value; }
    };

    class MutLeaf {
    public:
        MutLeaf() = default;
        ~MutLeaf() = default;
        MutLeaf(int32_t u, double v)
            : u_(std::move(u)), v_(std::move(v)) {}

    private:
        int32_t u_;
        double v_;

    public:
        int32_t& u() { return u_; }
        const int32_t& u() const { return u_; }
        void u(const int32_t& value) { u_ = value; }
        double& v() { return v_; }
        const double& v() const { return v_; }
        void v(const double& value) { v_ = value; }
    };

    class MutNest {
    public:
        MutNest() = default;
        ~MutNest() = default;
        MutNest(int32_t tag, ::feat::MutLeaf leaf, std::vector<::feat::MutLeaf> list)
            : tag_(std::move(tag)), leaf_(std::move(leaf)), list_(std::move(list)) {}

    private:
        int32_t tag_;
        ::feat::MutLeaf leaf_;
        std::vector<::feat::MutLeaf> list_;

    public:
        int32_t& tag() { return tag_; }
        const int32_t& tag() const { return tag_; }
        void tag(const int32_t& value) { tag_ = value; }
        ::feat::MutLeaf& leaf() { return leaf_; }
        const ::feat::MutLeaf& leaf() const { return leaf_; }
        void leaf(const ::feat::MutLeaf& value) { leaf_ = value; }
        std::vector<::feat::MutLeaf>& list() { return list_; }
        const std::vector<::feat::MutLeaf>& list() const { return list_; }
        void list(const std::vector<::feat::MutLeaf>& value) { list_ = value; }
    };

    class NestedKey {
    public:
        NestedKey() = default;
        ~NestedKey() = default;
        NestedKey(int32_t hi, int32_t lo)
            : hi_(std::move(hi)), lo_(std::move(lo)) {}

    private:
        int32_t hi_; // @key
        int32_t lo_; // @key

    public:
        int32_t& hi() { return hi_; }
        const int32_t& hi() const { return hi_; }
        void hi(const int32_t& value) { hi_ = value; }
        int32_t& lo() { return lo_; }
        const int32_t& lo() const { return lo_; }
        void lo(const int32_t& value) { lo_ = value; }
    };

    class OuterKey {
    public:
        OuterKey() = default;
        ~OuterKey() = default;
        OuterKey(::feat::NestedKey k, int32_t payload)
            : k_(std::move(k)), payload_(std::move(payload)) {}

    private:
        ::feat::NestedKey k_; // @key
        int32_t payload_;

    public:
        ::feat::NestedKey& k() { return k_; }
        const ::feat::NestedKey& k() const { return k_; }
        void k(const ::feat::NestedKey& value) { k_ = value; }
        int32_t& payload() { return payload_; }
        const int32_t& payload() const { return payload_; }
        void payload(const int32_t& value) { payload_ = value; }
    };

    /** IDL `@bit_bound(32)` */
    enum class Perm : uint32_t {
        READ = 1ULL << 0,
        WRITE = 1ULL << 1,
        EXEC = 1ULL << 2,
    };

    constexpr Perm operator|(Perm a, Perm b) noexcept {
        return static_cast<Perm>(static_cast<uint32_t>(a) | static_cast<uint32_t>(b));
    }
    constexpr Perm operator&(Perm a, Perm b) noexcept {
        return static_cast<Perm>(static_cast<uint32_t>(a) & static_cast<uint32_t>(b));
    }
    constexpr Perm operator^(Perm a, Perm b) noexcept {
        return static_cast<Perm>(static_cast<uint32_t>(a) ^ static_cast<uint32_t>(b));
    }
    constexpr Perm operator~(Perm a) noexcept {
        return static_cast<Perm>(~static_cast<uint32_t>(a));
    }

    struct Flags {
        uint64_t value{};

        uint64_t kind() const noexcept { return (value >> 0) & 0x7ULL; }
        void kind(uint64_t v) noexcept { value = (value & ~(0x7ULL << 0)) | ((v & 0x7ULL) << 0); }
        uint64_t prio() const noexcept { return (value >> 3) & 0x1FULL; }
        void prio(uint64_t v) noexcept { value = (value & ~(0x1FULL << 3)) | ((v & 0x1FULL) << 3); }
    };

    class Bits {
    public:
        Bits() = default;
        ~Bits() = default;
        Bits(::feat::Perm perm, ::feat::Flags flags)
            : perm_(std::move(perm)), flags_(std::move(flags)) {}

    private:
        ::feat::Perm perm_;
        ::feat::Flags flags_;

    public:
        ::feat::Perm& perm() { return perm_; }
        const ::feat::Perm& perm() const { return perm_; }
        void perm(const ::feat::Perm& value) { perm_ = value; }
        ::feat::Flags& flags() { return flags_; }
        const ::feat::Flags& flags() const { return flags_; }
        void flags(const ::feat::Flags& value) { flags_ = value; }
    };

    class Tree {
    public:
        Tree() = default;
        ~Tree() = default;
        Tree(int32_t value, std::vector<::feat::Tree> kids)
            : value_(std::move(value)), kids_(std::move(kids)) {}

    private:
        int32_t value_;
        std::vector<::feat::Tree> kids_;

    public:
        int32_t& value() { return value_; }
        const int32_t& value() const { return value_; }
        void value(const int32_t& value) { value_ = value; }
        std::vector<::feat::Tree>& kids() { return kids_; }
        const std::vector<::feat::Tree>& kids() const { return kids_; }
        void kids(const std::vector<::feat::Tree>& value) { kids_ = value; }
    };

    class Pt {
    public:
        Pt() = default;
        ~Pt() = default;
        Pt(int32_t x, int32_t y)
            : x_(std::move(x)), y_(std::move(y)) {}

    private:
        int32_t x_;
        int32_t y_;

    public:
        int32_t& x() { return x_; }
        const int32_t& x() const { return x_; }
        void x(const int32_t& value) { x_ = value; }
        int32_t& y() { return y_; }
        const int32_t& y() const { return y_; }
        void y(const int32_t& value) { y_ = value; }
    };

    class Arr {
    public:
        Arr() = default;
        ~Arr() = default;
        Arr(std::array<std::array<int32_t, 3>, 2> grid, std::array<::feat::Pt, 2> shape)
            : grid_(std::move(grid)), shape_(std::move(shape)) {}

    private:
        std::array<std::array<int32_t, 3>, 2> grid_;
        std::array<::feat::Pt, 2> shape_;

    public:
        std::array<std::array<int32_t, 3>, 2>& grid() { return grid_; }
        const std::array<std::array<int32_t, 3>, 2>& grid() const { return grid_; }
        void grid(const std::array<std::array<int32_t, 3>, 2>& value) { grid_ = value; }
        std::array<::feat::Pt, 2>& shape() { return shape_; }
        const std::array<::feat::Pt, 2>& shape() const { return shape_; }
        void shape(const std::array<::feat::Pt, 2>& value) { shape_ = value; }
    };

    class Sel {
    public:
        using value_type = std::variant<::feat::Pt, int32_t, uint8_t>;
        Sel() = default;
        ~Sel() = default;

        int32_t _d() const { return discriminator_; }
        void _d(int32_t d) { discriminator_ = d; }
        value_type& value() { return value_; }
        const value_type& value() const { return value_; }

        // case 1 -> p
        // case 2 -> n
        // case default -> z

    private:
        int32_t discriminator_{};
        value_type value_{};
    };

    enum class Hue : int32_t {
        H_RED,
        H_GREEN,
        H_BLUE,
    };

    class MapEnum {
    public:
        MapEnum() = default;
        ~MapEnum() = default;
        MapEnum(::feat::Hue h, std::map<int32_t, ::feat::Pt> m, std::vector<::feat::Sel> sels)
            : h_(std::move(h)), m_(std::move(m)), sels_(std::move(sels)) {}

    private:
        ::feat::Hue h_;
        std::map<int32_t, ::feat::Pt> m_;
        std::vector<::feat::Sel> sels_;

    public:
        ::feat::Hue& h() { return h_; }
        const ::feat::Hue& h() const { return h_; }
        void h(const ::feat::Hue& value) { h_ = value; }
        std::map<int32_t, ::feat::Pt>& m() { return m_; }
        const std::map<int32_t, ::feat::Pt>& m() const { return m_; }
        void m(const std::map<int32_t, ::feat::Pt>& value) { m_ = value; }
        std::vector<::feat::Sel>& sels() { return sels_; }
        const std::vector<::feat::Sel>& sels() const { return sels_; }
        void sels(const std::vector<::feat::Sel>& value) { sels_ = value; }
    };

    class Prim {
    public:
        Prim() = default;
        ~Prim() = default;
        Prim(int8_t i8, uint8_t u8, int16_t i16, uint16_t u16, int32_t i32, uint32_t u32, int64_t i64, uint64_t u64, float f32, double f64, bool b, uint8_t o, char ch)
            : i8_(std::move(i8)), u8_(std::move(u8)), i16_(std::move(i16)), u16_(std::move(u16)), i32_(std::move(i32)), u32_(std::move(u32)), i64_(std::move(i64)), u64_(std::move(u64)), f32_(std::move(f32)), f64_(std::move(f64)), b_(std::move(b)), o_(std::move(o)), ch_(std::move(ch)) {}

    private:
        int8_t i8_;
        uint8_t u8_;
        int16_t i16_;
        uint16_t u16_;
        int32_t i32_;
        uint32_t u32_;
        int64_t i64_;
        uint64_t u64_;
        float f32_;
        double f64_;
        bool b_;
        uint8_t o_;
        char ch_;

    public:
        int8_t& i8() { return i8_; }
        const int8_t& i8() const { return i8_; }
        void i8(const int8_t& value) { i8_ = value; }
        uint8_t& u8() { return u8_; }
        const uint8_t& u8() const { return u8_; }
        void u8(const uint8_t& value) { u8_ = value; }
        int16_t& i16() { return i16_; }
        const int16_t& i16() const { return i16_; }
        void i16(const int16_t& value) { i16_ = value; }
        uint16_t& u16() { return u16_; }
        const uint16_t& u16() const { return u16_; }
        void u16(const uint16_t& value) { u16_ = value; }
        int32_t& i32() { return i32_; }
        const int32_t& i32() const { return i32_; }
        void i32(const int32_t& value) { i32_ = value; }
        uint32_t& u32() { return u32_; }
        const uint32_t& u32() const { return u32_; }
        void u32(const uint32_t& value) { u32_ = value; }
        int64_t& i64() { return i64_; }
        const int64_t& i64() const { return i64_; }
        void i64(const int64_t& value) { i64_ = value; }
        uint64_t& u64() { return u64_; }
        const uint64_t& u64() const { return u64_; }
        void u64(const uint64_t& value) { u64_ = value; }
        float& f32() { return f32_; }
        const float& f32() const { return f32_; }
        void f32(const float& value) { f32_ = value; }
        double& f64() { return f64_; }
        const double& f64() const { return f64_; }
        void f64(const double& value) { f64_ = value; }
        bool& b() { return b_; }
        const bool& b() const { return b_; }
        void b(const bool& value) { b_ = value; }
        uint8_t& o() { return o_; }
        const uint8_t& o() const { return o_; }
        void o(const uint8_t& value) { o_ = value; }
        char& ch() { return ch_; }
        const char& ch() const { return ch_; }
        void ch(const char& value) { ch_ = value; }
    };

} // namespace feat

// DDS-PSM-Cxx topic_type_support<T> -- auto-generiert (XCDR2 Wire, XTypes 1.3 7.4).
namespace dds {
namespace topic {

template <>
struct topic_type_support<::feat::Sel> {
    static const char* type_name() { return "feat::Sel"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Sel& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Sel& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Sel& zd_v);
    static ::feat::Sel decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Sel& zd_v);
};

template <>
struct topic_type_support<::feat::WStr> {
    static const char* type_name() { return "feat::WStr"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::WStr& zd_v);
    static std::vector<uint8_t> encode(const ::feat::WStr& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::WStr& zd_v);
    static ::feat::WStr decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::WStr& zd_v);
};

template <>
struct topic_type_support<::feat::Mut> {
    static const char* type_name() { return "feat::Mut"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::MUTABLE; }
    static std::vector<uint8_t> encode(const ::feat::Mut& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Mut& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Mut& zd_v);
    static ::feat::Mut decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Mut& zd_v);
};

template <>
struct topic_type_support<::feat::MutLeaf> {
    static const char* type_name() { return "feat::MutLeaf"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::MUTABLE; }
    static std::vector<uint8_t> encode(const ::feat::MutLeaf& zd_v);
    static std::vector<uint8_t> encode(const ::feat::MutLeaf& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::MutLeaf& zd_v);
    static ::feat::MutLeaf decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::MutLeaf& zd_v);
};

template <>
struct topic_type_support<::feat::MutNest> {
    static const char* type_name() { return "feat::MutNest"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::MUTABLE; }
    static std::vector<uint8_t> encode(const ::feat::MutNest& zd_v);
    static std::vector<uint8_t> encode(const ::feat::MutNest& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::MutNest& zd_v);
    static ::feat::MutNest decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::MutNest& zd_v);
};

template <>
struct topic_type_support<::feat::NestedKey> {
    static const char* type_name() { return "feat::NestedKey"; }
    static constexpr bool is_keyed() { return true; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::FINAL; }
    static std::vector<uint8_t> encode(const ::feat::NestedKey& zd_v);
    static std::vector<uint8_t> encode(const ::feat::NestedKey& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::NestedKey& zd_v);
    static ::feat::NestedKey decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::NestedKey& zd_v);
};

template <>
struct topic_type_support<::feat::OuterKey> {
    static const char* type_name() { return "feat::OuterKey"; }
    static constexpr bool is_keyed() { return true; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::FINAL; }
    static std::vector<uint8_t> encode(const ::feat::OuterKey& zd_v);
    static std::vector<uint8_t> encode(const ::feat::OuterKey& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::OuterKey& zd_v);
    static ::feat::OuterKey decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::OuterKey& zd_v);
};

template <>
struct topic_type_support<::feat::Bits> {
    static const char* type_name() { return "feat::Bits"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Bits& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Bits& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Bits& zd_v);
    static ::feat::Bits decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Bits& zd_v);
};

template <>
struct topic_type_support<::feat::Tree> {
    static const char* type_name() { return "feat::Tree"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Tree& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Tree& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Tree& zd_v);
    static ::feat::Tree decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Tree& zd_v);
};

template <>
struct topic_type_support<::feat::Pt> {
    static const char* type_name() { return "feat::Pt"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Pt& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Pt& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Pt& zd_v);
    static ::feat::Pt decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Pt& zd_v);
};

template <>
struct topic_type_support<::feat::Arr> {
    static const char* type_name() { return "feat::Arr"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Arr& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Arr& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Arr& zd_v);
    static ::feat::Arr decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Arr& zd_v);
};

template <>
struct topic_type_support<::feat::MapEnum> {
    static const char* type_name() { return "feat::MapEnum"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::MapEnum& zd_v);
    static std::vector<uint8_t> encode(const ::feat::MapEnum& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::MapEnum& zd_v);
    static ::feat::MapEnum decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::MapEnum& zd_v);
};

template <>
struct topic_type_support<::feat::Prim> {
    static const char* type_name() { return "feat::Prim"; }
    static constexpr bool is_keyed() { return false; }
    static constexpr ::dds::topic::core::policy::DataRepresentationKind extensibility() { return ::dds::topic::core::policy::DataRepresentationKind::APPENDABLE; }
    static std::vector<uint8_t> encode(const ::feat::Prim& zd_v);
    static std::vector<uint8_t> encode(const ::feat::Prim& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::vector<uint8_t> encode_be(const ::feat::Prim& zd_v);
    static ::feat::Prim decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr);
    static std::array<uint8_t, 16> key_hash(const ::feat::Prim& zd_v);
};

inline std::vector<uint8_t> topic_type_support<::feat::Sel>::encode(const ::feat::Sel& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Sel>::encode(const ::feat::Sel& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
            ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v._d(), zd_max_align);
        switch (static_cast<int32_t>(zd_v._d())) {
        case static_cast<int32_t>(1):
        {
            const ::feat::Pt& zd_bv = std::get<::feat::Pt>(zd_v.value());
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb0 = ::dds::topic::topic_type_support<::feat::Pt>::encode(zd_bv, zd_repr);
                    zd_out.insert(zd_out.end(), zd_nsb0.begin(), zd_nsb0.end());
                }
            break;
        }
        case static_cast<int32_t>(2):
        {
            const int32_t& zd_bv = std::get<int32_t>(zd_v.value());
                ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_bv, zd_max_align);
            break;
        }
        default: {
            const uint8_t& zd_bv = std::get<uint8_t>(zd_v.value());
                ::dds::topic::xcdr2::write_u8(zd_out, zd_bv);
            break;
        }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Sel>::encode_be(const ::feat::Sel& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
            ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v._d());
        switch (static_cast<int32_t>(zd_v._d())) {
        case static_cast<int32_t>(1):
        {
            const ::feat::Pt& zd_bv = std::get<::feat::Pt>(zd_v.value());
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb1 = ::dds::topic::topic_type_support<::feat::Pt>::encode_be(zd_bv);
                    zd_out.insert(zd_out.end(), zd_nsb1.begin(), zd_nsb1.end());
                }
            break;
        }
        case static_cast<int32_t>(2):
        {
            const int32_t& zd_bv = std::get<int32_t>(zd_v.value());
                ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_bv);
            break;
        }
        default: {
            const uint8_t& zd_bv = std::get<uint8_t>(zd_v.value());
                ::dds::topic::xcdr2::write_u8(zd_out, zd_bv);
            break;
        }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Sel topic_type_support<::feat::Sel>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Sel zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        int32_t zd_disc{};
        zd_disc =(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v._d(zd_disc);
        switch (static_cast<int32_t>(zd_v._d())) {
        case static_cast<int32_t>(1):
        {
            ::feat::Pt zd_bv{};
            {
                ::feat::Pt zd_ns2{};
                ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
                const size_t zd_nss2 = zd_pos;
                size_t zd_npk2 = zd_pos;
                const uint32_t zd_nl2 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk2, zd_len);
                zd_ns2 = ::dds::topic::topic_type_support<::feat::Pt>::decode(zd_buf + zd_nss2, 4u + zd_nl2, zd_repr);
                zd_pos = zd_nss2 + 4u + zd_nl2;
                zd_bv =(zd_ns2);
            }
            zd_v.value() = zd_bv;
            break;
        }
        case static_cast<int32_t>(2):
        {
            int32_t zd_bv{};
            zd_bv =(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
            zd_v.value() = zd_bv;
            break;
        }
        default: {
            uint8_t zd_bv{};
            zd_bv =(::dds::topic::xcdr2::read_u8(zd_buf, zd_pos, zd_len));
            zd_v.value() = zd_bv;
            break;
        }
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Sel>::key_hash(const ::feat::Sel& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::WStr>::encode(const ::feat::WStr& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::WStr>::encode(const ::feat::WStr& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        if (zd_v.label().size() > 16) throw std::length_error("bounded wstring length exceeds its IDL bound (16)");
        ::dds::topic::xcdr2::write_wstring_origin(zd_out, zd_origin, zd_v.label(), zd_max_align);
        ::dds::topic::xcdr2::write_wstring_origin(zd_out, zd_origin, zd_v.text(), zd_max_align);
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::WStr>::encode_be(const ::feat::WStr& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        if (zd_v.label().size() > 16) throw std::length_error("bounded wstring length exceeds its IDL bound (16)");
        ::dds::topic::xcdr2::write_wstring_be(zd_out, zd_v.label());
        ::dds::topic::xcdr2::write_wstring_be(zd_out, zd_v.text());
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::WStr topic_type_support<::feat::WStr>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::WStr zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.label(::dds::topic::xcdr2::read_wstring_origin(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.text(::dds::topic::xcdr2::read_wstring_origin(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::WStr>::key_hash(const ::feat::WStr& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::Mut>::encode(const ::feat::Mut& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Mut>::encode(const ::feat::Mut& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        ::dds::topic::xcdr2::emheader_4<int32_t>(zd_out, zd_origin, 0xau, false, zd_v.a());
        ::dds::topic::xcdr2::emheader_8<double>(zd_out, zd_origin, 0x14u, false, zd_v.b());
        if (zd_v.c().size() > 8) throw std::length_error("bounded string length exceeds its IDL bound (8)");
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x1eu, false));
            { const auto zd_body_origin = zd_out.size(); (void)zd_body_origin;
              ::dds::topic::xcdr2::write_string_origin(zd_out, zd_body_origin, zd_v.c(), zd_max_align);
            } }
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Mut>::encode_be(const ::feat::Mut& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(2u, 0xau, false));
            ::dds::topic::xcdr2::write_be_raw<int32_t>(zd_out, zd_v.a()); }
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(3u, 0x14u, false));
            ::dds::topic::xcdr2::write_be_raw<double>(zd_out, zd_v.b()); }
        if (zd_v.c().size() > 8) throw std::length_error("bounded string length exceeds its IDL bound (8)");
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x1eu, false));
            { const auto zd_body_origin = zd_out.size(); (void)zd_body_origin;
              ::dds::topic::xcdr2::write_string_be(zd_out, zd_v.c());
            } }
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline ::feat::Mut topic_type_support<::feat::Mut>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Mut zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        while (zd_pos + 4 <= zd_end) {
            const auto zd_h = ::dds::topic::xcdr2::emheader_read(zd_buf, zd_pos, zd_len, zd_origin);
            switch (zd_h.member_id) {
                case 0xau: {
                    zd_v.a(::dds::topic::xcdr2::read_le_raw<int32_t>(zd_buf, zd_pos, zd_len));
                    break;
                }
                case 0x14u: {
                    zd_v.b(::dds::topic::xcdr2::read_le_raw<double>(zd_buf, zd_pos, zd_len));
                    break;
                }
                case 0x1eu: {
                    auto zd_body_origin = zd_pos;
                    zd_v.c(::dds::topic::xcdr2::read_string_origin(zd_buf, zd_pos, zd_len, zd_body_origin, zd_max_align));
                    break;
                }
                default: {
                    // Unknown member: per-LC skip per XTypes 1.3
                    // §7.4.3.4.2 (LengthCode::body_len). LC0..3 are
                    // fixed 1/2/4/8-byte bodies WITHOUT NEXTINT; LC4/5 NEXTINT=
                    // byte length; LC6/7 NEXTINT=element count (4 + 4n / 4 + 8n).
                    if (zd_h.lc == 0) { zd_pos += 1; }
                    else if (zd_h.lc == 1) { zd_pos += 2; }
                    else if (zd_h.lc == 2) { zd_pos += 4; }
                    else if (zd_h.lc == 3) { zd_pos += 8; }
                    else if (zd_h.lc == 4 || zd_h.lc == 5) { auto zd_n = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += zd_n; }
                    else if (zd_h.lc == 6) { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 4 * static_cast<size_t>(zd_c); }
                    else { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 8 * static_cast<size_t>(zd_c); }
                    break;
                }
            }
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Mut>::key_hash(const ::feat::Mut& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::MutLeaf>::encode(const ::feat::MutLeaf& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::MutLeaf>::encode(const ::feat::MutLeaf& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        ::dds::topic::xcdr2::emheader_4<int32_t>(zd_out, zd_origin, 0x1u, false, zd_v.u());
        ::dds::topic::xcdr2::emheader_8<double>(zd_out, zd_origin, 0x2u, false, zd_v.v());
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::MutLeaf>::encode_be(const ::feat::MutLeaf& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(2u, 0x1u, false));
            ::dds::topic::xcdr2::write_be_raw<int32_t>(zd_out, zd_v.u()); }
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(3u, 0x2u, false));
            ::dds::topic::xcdr2::write_be_raw<double>(zd_out, zd_v.v()); }
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline ::feat::MutLeaf topic_type_support<::feat::MutLeaf>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::MutLeaf zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        while (zd_pos + 4 <= zd_end) {
            const auto zd_h = ::dds::topic::xcdr2::emheader_read(zd_buf, zd_pos, zd_len, zd_origin);
            switch (zd_h.member_id) {
                case 0x1u: {
                    zd_v.u(::dds::topic::xcdr2::read_le_raw<int32_t>(zd_buf, zd_pos, zd_len));
                    break;
                }
                case 0x2u: {
                    zd_v.v(::dds::topic::xcdr2::read_le_raw<double>(zd_buf, zd_pos, zd_len));
                    break;
                }
                default: {
                    // Unknown member: per-LC skip per XTypes 1.3
                    // §7.4.3.4.2 (LengthCode::body_len). LC0..3 are
                    // fixed 1/2/4/8-byte bodies WITHOUT NEXTINT; LC4/5 NEXTINT=
                    // byte length; LC6/7 NEXTINT=element count (4 + 4n / 4 + 8n).
                    if (zd_h.lc == 0) { zd_pos += 1; }
                    else if (zd_h.lc == 1) { zd_pos += 2; }
                    else if (zd_h.lc == 2) { zd_pos += 4; }
                    else if (zd_h.lc == 3) { zd_pos += 8; }
                    else if (zd_h.lc == 4 || zd_h.lc == 5) { auto zd_n = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += zd_n; }
                    else if (zd_h.lc == 6) { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 4 * static_cast<size_t>(zd_c); }
                    else { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 8 * static_cast<size_t>(zd_c); }
                    break;
                }
            }
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::MutLeaf>::key_hash(const ::feat::MutLeaf& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::MutNest>::encode(const ::feat::MutNest& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::MutNest>::encode(const ::feat::MutNest& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        ::dds::topic::xcdr2::emheader_4<int32_t>(zd_out, zd_origin, 0xau, false, zd_v.tag());
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x14u, false));
            auto zd_nsb3 = ::dds::topic::topic_type_support<::feat::MutLeaf>::encode(zd_v.leaf(), zd_repr);
            zd_out.insert(zd_out.end(), zd_nsb3.begin(), zd_nsb3.end()); }
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x1eu, false));
            { const auto zd_body_origin = zd_out.size(); (void)zd_body_origin;
              const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
              ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_body_origin, static_cast<uint32_t>(zd_v.list().size()), zd_max_align);
              for (const auto& zd_e : zd_v.list()) {
                    {
                        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_body_origin, 4);
                        auto zd_nsb4 = ::dds::topic::topic_type_support<::feat::MutLeaf>::encode(zd_e, zd_repr);
                        zd_out.insert(zd_out.end(), zd_nsb4.begin(), zd_nsb4.end());
                    }
              }
              ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
            }
        }
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::MutNest>::encode_be(const ::feat::MutNest& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_scope = ::dds::topic::xcdr2::mutable_begin(zd_out);
        const size_t zd_origin = zd_scope.origin;
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(2u, 0xau, false));
            ::dds::topic::xcdr2::write_be_raw<int32_t>(zd_out, zd_v.tag()); }
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x14u, false));
            auto zd_nsb5 = ::dds::topic::topic_type_support<::feat::MutLeaf>::encode_be(zd_v.leaf());
            zd_out.insert(zd_out.end(), zd_nsb5.begin(), zd_nsb5.end()); }
        { ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
            ::dds::topic::xcdr2::emheader_write(zd_out, ::dds::topic::xcdr2::emheader_make(5u, 0x1eu, false));
            { const auto zd_body_origin = zd_out.size(); (void)zd_body_origin;
              const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
              ::dds::topic::xcdr2::write_be<uint32_t>(zd_out, static_cast<uint32_t>(zd_v.list().size()));
              for (const auto& zd_e : zd_v.list()) {
                    {
                        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_body_origin, 4);
                        auto zd_nsb6 = ::dds::topic::topic_type_support<::feat::MutLeaf>::encode_be(zd_e);
                        zd_out.insert(zd_out.end(), zd_nsb6.begin(), zd_nsb6.end());
                    }
              }
              ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
            }
        }
        ::dds::topic::xcdr2::mutable_end(zd_out, zd_scope);
        return zd_out;
    }
inline ::feat::MutNest topic_type_support<::feat::MutNest>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::MutNest zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        while (zd_pos + 4 <= zd_end) {
            const auto zd_h = ::dds::topic::xcdr2::emheader_read(zd_buf, zd_pos, zd_len, zd_origin);
            switch (zd_h.member_id) {
                case 0xau: {
                    zd_v.tag(::dds::topic::xcdr2::read_le_raw<int32_t>(zd_buf, zd_pos, zd_len));
                    break;
                }
                case 0x14u: {
                    auto zd_body_origin = zd_pos; (void)zd_body_origin;
                    ::feat::MutLeaf zd_ns7{};
                    const size_t zd_nss7 = zd_pos;
                    size_t zd_npk7 = zd_pos;
                    const uint32_t zd_nl7 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk7, zd_len);
                    zd_ns7 = ::dds::topic::topic_type_support<::feat::MutLeaf>::decode(zd_buf + zd_nss7, 4u + zd_nl7, zd_repr);
                    zd_pos = zd_nss7 + 4u + zd_nl7;
                    zd_v.leaf(zd_ns7);
                    break;
                }
                case 0x1eu: {
                    auto zd_body_origin = zd_pos;
                    { const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len); (void)zd_seq_dh; }
                    auto zd_cnt = ::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_body_origin, zd_max_align);
                    std::vector<::feat::MutLeaf> zd_seq;
                    zd_seq.reserve(zd_cnt);
                    for (uint32_t zd_i = 0; zd_i < zd_cnt; ++zd_i) {
                        ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_body_origin, 4);
                        const size_t zd_nss8 = zd_pos;
                        size_t zd_npk8 = zd_pos;
                        const uint32_t zd_nl8 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk8, zd_len);
                        ::feat::MutLeaf zd_se8 = ::dds::topic::topic_type_support<::feat::MutLeaf>::decode(zd_buf + zd_nss8, 4u + zd_nl8, zd_repr);
                        zd_pos = zd_nss8 + 4u + zd_nl8;
                        zd_seq.push_back(std::move(zd_se8));
                    }
                    zd_v.list(std::move(zd_seq));
                    break;
                }
                default: {
                    // Unknown member: per-LC skip per XTypes 1.3
                    // §7.4.3.4.2 (LengthCode::body_len). LC0..3 are
                    // fixed 1/2/4/8-byte bodies WITHOUT NEXTINT; LC4/5 NEXTINT=
                    // byte length; LC6/7 NEXTINT=element count (4 + 4n / 4 + 8n).
                    if (zd_h.lc == 0) { zd_pos += 1; }
                    else if (zd_h.lc == 1) { zd_pos += 2; }
                    else if (zd_h.lc == 2) { zd_pos += 4; }
                    else if (zd_h.lc == 3) { zd_pos += 8; }
                    else if (zd_h.lc == 4 || zd_h.lc == 5) { auto zd_n = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += zd_n; }
                    else if (zd_h.lc == 6) { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 4 * static_cast<size_t>(zd_c); }
                    else { auto zd_c = ::dds::topic::xcdr2::emheader_nextint_read(zd_buf, zd_pos, zd_len); zd_pos += 4 + 8 * static_cast<size_t>(zd_c); }
                    break;
                }
            }
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::MutNest>::key_hash(const ::feat::MutNest& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::NestedKey>::encode(const ::feat::NestedKey& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::NestedKey>::encode(const ::feat::NestedKey& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const size_t zd_origin = 0;
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.hi(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.lo(), zd_max_align);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::NestedKey>::encode_be(const ::feat::NestedKey& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_origin = 0;
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.hi());
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.lo());
        return zd_out;
    }
inline ::feat::NestedKey topic_type_support<::feat::NestedKey>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::NestedKey zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const size_t zd_origin = 0;
        (void)zd_origin;
        zd_v.hi(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.lo(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::NestedKey>::key_hash(const ::feat::NestedKey& zd_v) {
        (void)zd_v;
        std::vector<uint8_t> zd_out;
        const size_t zd_origin = 0;
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.hi());
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.lo());
        std::array<uint8_t, 16> zd_h{};
        if (zd_out.size() <= 16) {
            std::memcpy(zd_h.data(), zd_out.data(), zd_out.size());
            return zd_h;
        }
        return ::dds::topic::xcdr2_md5::md5(zd_out);
    }

inline std::vector<uint8_t> topic_type_support<::feat::OuterKey>::encode(const ::feat::OuterKey& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::OuterKey>::encode(const ::feat::OuterKey& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const size_t zd_origin = 0;
        (void)zd_origin;
            ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.k().hi(), zd_max_align);
            ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.k().lo(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.payload(), zd_max_align);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::OuterKey>::encode_be(const ::feat::OuterKey& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_origin = 0;
        (void)zd_origin;
            ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.k().hi());
            ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.k().lo());
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.payload());
        return zd_out;
    }
inline ::feat::OuterKey topic_type_support<::feat::OuterKey>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::OuterKey zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const size_t zd_origin = 0;
        (void)zd_origin;
        {
            ::feat::NestedKey zd_ns9{};
            zd_ns9.hi(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
            zd_ns9.lo(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
            zd_v.k(zd_ns9);
        }
        zd_v.payload(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::OuterKey>::key_hash(const ::feat::OuterKey& zd_v) {
        (void)zd_v;
        std::vector<uint8_t> zd_out;
        const size_t zd_origin = 0;
        (void)zd_origin;
            ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.k().hi());
            ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.k().lo());
        std::array<uint8_t, 16> zd_h{};
        if (zd_out.size() <= 16) {
            std::memcpy(zd_h.data(), zd_out.data(), zd_out.size());
            return zd_h;
        }
        return ::dds::topic::xcdr2_md5::md5(zd_out);
    }

inline std::vector<uint8_t> topic_type_support<::feat::Bits>::encode(const ::feat::Bits& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Bits>::encode(const ::feat::Bits& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_origin, static_cast<uint32_t>(zd_v.perm()), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<uint8_t>(zd_out, zd_origin, static_cast<uint8_t>(zd_v.flags().value), zd_max_align);
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Bits>::encode_be(const ::feat::Bits& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<uint32_t>(zd_out, zd_origin, static_cast<uint32_t>(zd_v.perm()));
        ::dds::topic::xcdr2::write_be_origin<uint8_t>(zd_out, zd_origin, static_cast<uint8_t>(zd_v.flags().value));
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Bits topic_type_support<::feat::Bits>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Bits zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.perm(static_cast<::feat::Perm>(::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align)));
        zd_v.flags(::feat::Flags{ static_cast<uint64_t>(::dds::topic::xcdr2::read_le_origin<uint8_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align)) });
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Bits>::key_hash(const ::feat::Bits& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::Tree>::encode(const ::feat::Tree& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Tree>::encode(const ::feat::Tree& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.value(), zd_max_align);
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_origin, static_cast<uint32_t>(zd_v.kids().size()), zd_max_align);
        for (const auto& zd_e : zd_v.kids()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb10 = ::dds::topic::topic_type_support<::feat::Tree>::encode(zd_e, zd_repr);
                    zd_out.insert(zd_out.end(), zd_nsb10.begin(), zd_nsb10.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Tree>::encode_be(const ::feat::Tree& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.value());
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_be<uint32_t>(zd_out, static_cast<uint32_t>(zd_v.kids().size()));
        for (const auto& zd_e : zd_v.kids()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb11 = ::dds::topic::topic_type_support<::feat::Tree>::encode_be(zd_e);
                    zd_out.insert(zd_out.end(), zd_nsb11.begin(), zd_nsb11.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Tree topic_type_support<::feat::Tree>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Tree zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.value(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        {
            ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
            const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len); (void)zd_seq_dh;
            auto zd_cnt = ::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align);
            std::vector<::feat::Tree> zd_seq;
            zd_seq.reserve(zd_cnt);
            for (uint32_t zd_i = 0; zd_i < zd_cnt; ++zd_i) {
                ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
                const size_t zd_nss12 = zd_pos;
                size_t zd_npk12 = zd_pos;
                const uint32_t zd_nl12 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk12, zd_len);
                ::feat::Tree zd_se12 = ::dds::topic::topic_type_support<::feat::Tree>::decode(zd_buf + zd_nss12, 4u + zd_nl12, zd_repr);
                zd_pos = zd_nss12 + 4u + zd_nl12;
                zd_seq.push_back(std::move(zd_se12));
            }
            zd_v.kids(std::move(zd_seq));
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Tree>::key_hash(const ::feat::Tree& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::Pt>::encode(const ::feat::Pt& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Pt>::encode(const ::feat::Pt& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.x(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.y(), zd_max_align);
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Pt>::encode_be(const ::feat::Pt& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.x());
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.y());
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Pt topic_type_support<::feat::Pt>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Pt zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.x(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.y(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Pt>::key_hash(const ::feat::Pt& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::Arr>::encode(const ::feat::Arr& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Arr>::encode(const ::feat::Arr& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        for (const auto& zd_a0 : zd_v.grid()) {
            for (const auto& zd_a1 : zd_a0) {
                    ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_a1, zd_max_align);
            }
        }
        {
        const auto zd_arr_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        for (const auto& zd_a0 : zd_v.shape()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb13 = ::dds::topic::topic_type_support<::feat::Pt>::encode(zd_a0, zd_repr);
                    zd_out.insert(zd_out.end(), zd_nsb13.begin(), zd_nsb13.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_arr_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Arr>::encode_be(const ::feat::Arr& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        for (const auto& zd_a0 : zd_v.grid()) {
            for (const auto& zd_a1 : zd_a0) {
                    ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_a1);
            }
        }
        {
        const auto zd_arr_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        for (const auto& zd_a0 : zd_v.shape()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb14 = ::dds::topic::topic_type_support<::feat::Pt>::encode_be(zd_a0);
                    zd_out.insert(zd_out.end(), zd_nsb14.begin(), zd_nsb14.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_arr_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Arr topic_type_support<::feat::Arr>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Arr zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        {
            auto zd_arr = zd_v.grid();
            for (auto& zd_a0 : zd_arr) {
                for (auto& zd_a1 : zd_a0) {
                    zd_a1 = ::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align);
                }
            }
            zd_v.grid(zd_arr);
        }
        {
        const auto zd_arr_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len); (void)zd_arr_dh;
        auto zd_arr = zd_v.shape();
        for (auto& zd_a0 : zd_arr) {
            {
                ::feat::Pt zd_ns15{};
                ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
                const size_t zd_nss15 = zd_pos;
                size_t zd_npk15 = zd_pos;
                const uint32_t zd_nl15 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk15, zd_len);
                zd_ns15 = ::dds::topic::topic_type_support<::feat::Pt>::decode(zd_buf + zd_nss15, 4u + zd_nl15, zd_repr);
                zd_pos = zd_nss15 + 4u + zd_nl15;
                zd_a0 =(zd_ns15);
            }
        }
        zd_v.shape(zd_arr);
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Arr>::key_hash(const ::feat::Arr& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::MapEnum>::encode(const ::feat::MapEnum& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::MapEnum>::encode(const ::feat::MapEnum& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<int16_t>(zd_out, zd_origin, static_cast<int16_t>(zd_v.h()), zd_max_align);
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_map_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_origin, static_cast<uint32_t>(zd_v.m().size()), zd_max_align);
        for (const auto& zd_kv : zd_v.m()) {
                ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_kv.first, zd_max_align);
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb16 = ::dds::topic::topic_type_support<::feat::Pt>::encode(zd_kv.second, zd_repr);
                    zd_out.insert(zd_out.end(), zd_nsb16.begin(), zd_nsb16.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_map_dh);
        }
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_origin, static_cast<uint32_t>(zd_v.sels().size()), zd_max_align);
        for (const auto& zd_e : zd_v.sels()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nub17 = ::dds::topic::topic_type_support<::feat::Sel>::encode(zd_e, zd_repr);
                    zd_out.insert(zd_out.end(), zd_nub17.begin(), zd_nub17.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::MapEnum>::encode_be(const ::feat::MapEnum& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be<int16_t>(zd_out, static_cast<int16_t>(zd_v.h()));
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_map_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_be<uint32_t>(zd_out, static_cast<uint32_t>(zd_v.m().size()));
        for (const auto& zd_kv : zd_v.m()) {
                ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_kv.first);
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nsb18 = ::dds::topic::topic_type_support<::feat::Pt>::encode_be(zd_kv.second);
                    zd_out.insert(zd_out.end(), zd_nsb18.begin(), zd_nsb18.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_map_dh);
        }
        {
        ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
        const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        ::dds::topic::xcdr2::write_be<uint32_t>(zd_out, static_cast<uint32_t>(zd_v.sels().size()));
        for (const auto& zd_e : zd_v.sels()) {
                {
                    ::dds::topic::xcdr2::pad_to_from_origin(zd_out, zd_origin, 4);
                    auto zd_nub19 = ::dds::topic::topic_type_support<::feat::Sel>::encode_be(zd_e);
                    zd_out.insert(zd_out.end(), zd_nub19.begin(), zd_nub19.end());
                }
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_seq_dh);
        }
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::MapEnum topic_type_support<::feat::MapEnum>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::MapEnum zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.h(static_cast<::feat::Hue>(::dds::topic::xcdr2::read_le_origin<int16_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align)));
        {
            ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
            const auto zd_map_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len); (void)zd_map_dh;
            auto zd_mcnt = ::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align);
            std::map<int32_t, ::feat::Pt> zd_map20;
            for (uint32_t zd_i = 0; zd_i < zd_mcnt; ++zd_i) {
                int32_t zd_mk20{};
                ::feat::Pt zd_mv20{};
                zd_mk20 =(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
                {
                    ::feat::Pt zd_ns21{};
                    ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
                    const size_t zd_nss21 = zd_pos;
                    size_t zd_npk21 = zd_pos;
                    const uint32_t zd_nl21 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk21, zd_len);
                    zd_ns21 = ::dds::topic::topic_type_support<::feat::Pt>::decode(zd_buf + zd_nss21, 4u + zd_nl21, zd_repr);
                    zd_pos = zd_nss21 + 4u + zd_nl21;
                    zd_mv20 =(zd_ns21);
                }
                zd_map20.emplace(std::move(zd_mk20), std::move(zd_mv20));
            }
            zd_v.m(std::move(zd_map20));
        }
        {
            ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
            const auto zd_seq_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len); (void)zd_seq_dh;
            auto zd_cnt = ::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align);
            std::vector<::feat::Sel> zd_seq;
            zd_seq.reserve(zd_cnt);
            for (uint32_t zd_i = 0; zd_i < zd_cnt; ++zd_i) {
                ::dds::topic::xcdr2::skip_pad_from_origin(zd_pos, zd_origin, 4);
                const size_t zd_nss22 = zd_pos;
                size_t zd_npk22 = zd_pos;
                const uint32_t zd_nl22 = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_npk22, zd_len);
                ::feat::Sel zd_se22 = ::dds::topic::topic_type_support<::feat::Sel>::decode(zd_buf + zd_nss22, 4u + zd_nl22, zd_repr);
                zd_pos = zd_nss22 + 4u + zd_nl22;
                zd_seq.push_back(std::move(zd_se22));
            }
            zd_v.sels(std::move(zd_seq));
        }
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::MapEnum>::key_hash(const ::feat::MapEnum& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

inline std::vector<uint8_t> topic_type_support<::feat::Prim>::encode(const ::feat::Prim& zd_v) {
        return encode(zd_v, ::dds::topic::xcdr2::XcdrVersion::Xcdr2);
    }
inline std::vector<uint8_t> topic_type_support<::feat::Prim>::encode(const ::feat::Prim& zd_v, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_le_origin<int8_t>(zd_out, zd_origin, zd_v.i8(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<uint8_t>(zd_out, zd_origin, zd_v.u8(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int16_t>(zd_out, zd_origin, zd_v.i16(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<uint16_t>(zd_out, zd_origin, zd_v.u16(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int32_t>(zd_out, zd_origin, zd_v.i32(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<uint32_t>(zd_out, zd_origin, zd_v.u32(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<int64_t>(zd_out, zd_origin, zd_v.i64(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<uint64_t>(zd_out, zd_origin, zd_v.u64(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<float>(zd_out, zd_origin, zd_v.f32(), zd_max_align);
        ::dds::topic::xcdr2::write_le_origin<double>(zd_out, zd_origin, zd_v.f64(), zd_max_align);
        ::dds::topic::xcdr2::write_bool(zd_out, zd_v.b());
        ::dds::topic::xcdr2::write_u8(zd_out, zd_v.o());
        ::dds::topic::xcdr2::write_le_origin<char>(zd_out, zd_origin, zd_v.ch(), zd_max_align);
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline std::vector<uint8_t> topic_type_support<::feat::Prim>::encode_be(const ::feat::Prim& zd_v) {
        std::vector<uint8_t> zd_out;
        (void)zd_v;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_begin(zd_out);
        const size_t zd_origin = zd_out.size();
        (void)zd_origin;
        ::dds::topic::xcdr2::write_be_origin<int8_t>(zd_out, zd_origin, zd_v.i8());
        ::dds::topic::xcdr2::write_be_origin<uint8_t>(zd_out, zd_origin, zd_v.u8());
        ::dds::topic::xcdr2::write_be_origin<int16_t>(zd_out, zd_origin, zd_v.i16());
        ::dds::topic::xcdr2::write_be_origin<uint16_t>(zd_out, zd_origin, zd_v.u16());
        ::dds::topic::xcdr2::write_be_origin<int32_t>(zd_out, zd_origin, zd_v.i32());
        ::dds::topic::xcdr2::write_be_origin<uint32_t>(zd_out, zd_origin, zd_v.u32());
        ::dds::topic::xcdr2::write_be_origin<int64_t>(zd_out, zd_origin, zd_v.i64());
        ::dds::topic::xcdr2::write_be_origin<uint64_t>(zd_out, zd_origin, zd_v.u64());
        ::dds::topic::xcdr2::write_be_origin<float>(zd_out, zd_origin, zd_v.f32());
        ::dds::topic::xcdr2::write_be_origin<double>(zd_out, zd_origin, zd_v.f64());
        ::dds::topic::xcdr2::write_bool(zd_out, zd_v.b());
        ::dds::topic::xcdr2::write_u8(zd_out, zd_v.o());
        ::dds::topic::xcdr2::write_be_origin<char>(zd_out, zd_origin, zd_v.ch());
        ::dds::topic::xcdr2::dheader_end(zd_out, zd_dh);
        return zd_out;
    }
inline ::feat::Prim topic_type_support<::feat::Prim>::decode(const uint8_t* zd_buf, size_t zd_len, ::dds::topic::xcdr2::XcdrVersion zd_repr) {
        size_t zd_pos = 0;
        ::feat::Prim zd_v;
        const size_t zd_max_align = ::dds::topic::xcdr2::xcdr_max_align(zd_repr);
        (void)zd_buf; (void)zd_len; (void)zd_pos; (void)zd_max_align;
        const auto zd_dh = ::dds::topic::xcdr2::dheader_read(zd_buf, zd_pos, zd_len);
        const size_t zd_origin = zd_pos;
        const size_t zd_end = zd_origin + zd_dh;
        (void)zd_end;
        zd_v.i8(::dds::topic::xcdr2::read_le_origin<int8_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.u8(::dds::topic::xcdr2::read_le_origin<uint8_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.i16(::dds::topic::xcdr2::read_le_origin<int16_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.u16(::dds::topic::xcdr2::read_le_origin<uint16_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.i32(::dds::topic::xcdr2::read_le_origin<int32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.u32(::dds::topic::xcdr2::read_le_origin<uint32_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.i64(::dds::topic::xcdr2::read_le_origin<int64_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.u64(::dds::topic::xcdr2::read_le_origin<uint64_t>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.f32(::dds::topic::xcdr2::read_le_origin<float>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.f64(::dds::topic::xcdr2::read_le_origin<double>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        zd_v.b(::dds::topic::xcdr2::read_bool(zd_buf, zd_pos, zd_len));
        zd_v.o(::dds::topic::xcdr2::read_u8(zd_buf, zd_pos, zd_len));
        zd_v.ch(::dds::topic::xcdr2::read_le_origin<char>(zd_buf, zd_pos, zd_len, zd_origin, zd_max_align));
        if (zd_pos < zd_end) zd_pos = zd_end;
        return zd_v;
    }
inline std::array<uint8_t, 16> topic_type_support<::feat::Prim>::key_hash(const ::feat::Prim& zd_v) {
        (void)zd_v;
        return std::array<uint8_t, 16>{{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}};
    }

} // namespace topic
} // namespace dds
