// Generated by zerodds idl-csharp. Do not edit.
// Target: C# 12.0 / .NET 8+
#nullable enable

using Omg.Types;
using System;
using ZeroDDS.Cdr;

namespace qos
{
    public partial record class Reading : ITopicType<Reading>
    {
        [Key]
        public int Id { get; init; } = default!;
        public int Seq { get; init; } = default!;
        public double Value { get; init; } = default!;
    }

    public sealed class ReadingTypeSupport : IDdsTopicType<Reading>
    {
        public static readonly ReadingTypeSupport Instance = new();

        public string TypeName => "qos::Reading";
        public bool IsKeyed => true;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Reading sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Reading sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Reading sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteInt32(sample.Id);
                w.WriteInt32(sample.Seq);
                w.WriteFloat64(sample.Value);
            }
        }

        public Reading Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Reading DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int __m0 = default!;
            __m0 = r.ReadInt32();
            int __m1 = default!;
            __m1 = r.ReadInt32();
            double __m2 = default!;
            __m2 = r.ReadFloat64();
            r.EndDHeader(__scope);
            return new Reading
            {
                Id = __m0!,
                Seq = __m1!,
                Value = __m2!,
            };
        }

        public byte[] KeyHash(Reading sample)
        {
            var __kw = new Xcdr2Writer(EndianMode.BigEndian);
            __kw.WriteInt32(sample.Id);
            var __kb = __kw.ToArray();
            if (__kb.Length > 16) { return Md5.Hash(__kb); }
            var __h = new byte[16];
            System.Array.Copy(__kb, 0, __h, 0, __kb.Length);
            return __h;
        }
    }

} // namespace qos

// XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised)
public static class TypeObjects
{
    /// <summary>Minimal TypeObject for qos::Reading.</summary>
    public static readonly byte[] qos_Reading = {
        0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0xb8, 0x0b, 0xb7, 0x74, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe0, 0x68, 0xc2, 0xde, 0x00,
        0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x20, 0x63, 0xc1, 0x60,
    };
}
