/* Generated by zerodds idl-cpp c_mode. Do not edit. */
#ifndef ZERODDS_GENERATED_H
#define ZERODDS_GENERATED_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "zerodds.h"
#include "zerodds_xcdr2.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct conf_Keyed_s {
    int32_t id;
    char* region;
    double value;
} conf_Keyed_t;

static int conf_Keyed_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int conf_Keyed_decode(const uint8_t* buf, size_t len, void* out_sample);
static void conf_Keyed_sample_free(void* sample);
static int conf_Keyed_key_hash(const void* sample, uint8_t out_hash[16]);

static const char conf_Keyed_type_name[] = "conf::Keyed";
static const zerodds_typesupport_t conf_Keyed_typesupport = {
    .type_hash = {0},
    .type_name = conf_Keyed_type_name,
    .is_keyed = 1,
    .extensibility = 1,
    ._reserved = {0},
    .encode = conf_Keyed_encode,
    .decode = conf_Keyed_decode,
    .key_hash = conf_Keyed_key_hash,
    .sample_free = conf_Keyed_sample_free,
};

static int conf_Keyed_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const conf_Keyed_t* s = (const conf_Keyed_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->id) != 0) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, s->region) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, s->value) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int conf_Keyed_decode(const uint8_t* buf, size_t len, void* out_sample) {
    conf_Keyed_t* s = (conf_Keyed_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->id)) != 0) return -7;
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(s->region)) != 0) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &(s->value)) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void conf_Keyed_sample_free(void* sample) {
    if (sample == NULL) return;
    conf_Keyed_t* s = (conf_Keyed_t*)sample;
    (void)s;
    free(s->region); s->region = NULL;
}

static int conf_Keyed_key_hash(const void* sample, uint8_t out_hash[16]) {
    const conf_Keyed_t* s = (const conf_Keyed_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->id) != 0) { free(kh_buf); return -1; }
    if (zerodds_xcdr2_c_kh_write_string(&kh_buf, &kh_len, &kh_cap, s->region) != 0) { free(kh_buf); return -1; }
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

typedef struct conf_MultiKey_s {
    int32_t a;
    int32_t b;
    int32_t payload;
} conf_MultiKey_t;

static int conf_MultiKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int conf_MultiKey_decode(const uint8_t* buf, size_t len, void* out_sample);
static void conf_MultiKey_sample_free(void* sample);
static int conf_MultiKey_key_hash(const void* sample, uint8_t out_hash[16]);

static const char conf_MultiKey_type_name[] = "conf::MultiKey";
static const zerodds_typesupport_t conf_MultiKey_typesupport = {
    .type_hash = {0},
    .type_name = conf_MultiKey_type_name,
    .is_keyed = 1,
    .extensibility = 1,
    ._reserved = {0},
    .encode = conf_MultiKey_encode,
    .decode = conf_MultiKey_decode,
    .key_hash = conf_MultiKey_key_hash,
    .sample_free = conf_MultiKey_sample_free,
};

static int conf_MultiKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const conf_MultiKey_t* s = (const conf_MultiKey_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->a) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->b) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->payload) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int conf_MultiKey_decode(const uint8_t* buf, size_t len, void* out_sample) {
    conf_MultiKey_t* s = (conf_MultiKey_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->a)) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->b)) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->payload)) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void conf_MultiKey_sample_free(void* sample) {
    if (sample == NULL) return;
    conf_MultiKey_t* s = (conf_MultiKey_t*)sample;
    (void)s;
}

static int conf_MultiKey_key_hash(const void* sample, uint8_t out_hash[16]) {
    const conf_MultiKey_t* s = (const conf_MultiKey_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->a) != 0) { free(kh_buf); return -1; }
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->b) != 0) { free(kh_buf); return -1; }
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

#ifdef __cplusplus
}
#endif
#endif

/* XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised) */
static const unsigned char conf_Keyed_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0xb8, 0x0b, 0xb7, 0x74, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x70, 0x10, 0x96, 0x0d, 0xb2, 0xed,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x20, 0x63, 0xc1, 0x60,
};
static const unsigned char conf_MultiKey_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x0c, 0xc1, 0x75, 0xb9, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x92, 0xeb, 0x5f, 0xfe, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x32, 0x1c, 0x3c, 0xf4,
};
