/* Generated by zerodds idl-cpp c_mode. Do not edit. */
#ifndef ZERODDS_GENERATED_H
#define ZERODDS_GENERATED_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "zerodds_xcdr2.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef int32_t conf_Status_t;
enum { conf_Status_OFFLINE = 0 };
enum { conf_Status_NOMINAL = 1 };
enum { conf_Status_DEGRADED = 2 };
enum { conf_Status_FAULT = 3 };

typedef struct conf_GeoPoint_s {
    double lat;
    double lon;
} conf_GeoPoint_t;

static int conf_GeoPoint_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int conf_GeoPoint_decode(const uint8_t* buf, size_t len, void* out_sample);
static void conf_GeoPoint_sample_free(void* sample);

static const char conf_GeoPoint_type_name[] = "conf::GeoPoint";
static const zerodds_typesupport_t conf_GeoPoint_typesupport = {
    .type_hash = {0},
    .type_name = conf_GeoPoint_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = conf_GeoPoint_encode,
    .decode = conf_GeoPoint_decode,
    .key_hash = NULL,
    .sample_free = conf_GeoPoint_sample_free,
};

static int conf_GeoPoint_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const conf_GeoPoint_t* s = (const conf_GeoPoint_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, s->lat) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, s->lon) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int conf_GeoPoint_decode(const uint8_t* buf, size_t len, void* out_sample) {
    conf_GeoPoint_t* s = (conf_GeoPoint_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &(s->lat)) != 0) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &(s->lon)) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void conf_GeoPoint_sample_free(void* sample) {
    if (sample == NULL) return;
    conf_GeoPoint_t* s = (conf_GeoPoint_t*)sample;
    (void)s;
}

typedef struct conf_SensorReading_s {
    int32_t sensor_id;
    char* site;
    conf_Status_t status;
    double temperature;
    conf_GeoPoint_t location;
    int32_t samples[4];
    double calibration;
    uint8_t calibration_present;
    char* note;
    uint8_t note_present;
} conf_SensorReading_t;

static int conf_SensorReading_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int conf_SensorReading_decode(const uint8_t* buf, size_t len, void* out_sample);
static void conf_SensorReading_sample_free(void* sample);
static int conf_SensorReading_key_hash(const void* sample, uint8_t out_hash[16]);

static const char conf_SensorReading_type_name[] = "conf::SensorReading";
static const zerodds_typesupport_t conf_SensorReading_typesupport = {
    .type_hash = {0},
    .type_name = conf_SensorReading_type_name,
    .is_keyed = 1,
    .extensibility = 1,
    ._reserved = {0},
    .encode = conf_SensorReading_encode,
    .decode = conf_SensorReading_decode,
    .key_hash = conf_SensorReading_key_hash,
    .sample_free = conf_SensorReading_sample_free,
};

static int conf_SensorReading_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const conf_SensorReading_t* s = (const conf_SensorReading_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->sensor_id) != 0) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, s->site) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (int32_t)(s->status)) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, s->temperature) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, (s->location).lat) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, (s->location).lon) != 0) goto fail;
    for (uint32_t ai0 = 0; ai0 < 4; ++ai0) {
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->samples[ai0]) != 0) goto fail;
    }
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->calibration_present ? 1 : 0) != 0) goto fail;
    if (s->calibration_present) {
    if (zerodds_xcdr2_c_write_f64(&w_buf, &w_len, &w_cap, s->calibration) != 0) goto fail;
    }
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->note_present ? 1 : 0) != 0) goto fail;
    if (s->note_present) {
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, s->note) != 0) goto fail;
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int conf_SensorReading_decode(const uint8_t* buf, size_t len, void* out_sample) {
    conf_SensorReading_t* s = (conf_SensorReading_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->sensor_id)) != 0) return -7;
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(s->site)) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, (int32_t*)&(s->status)) != 0) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &(s->temperature)) != 0) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &((s->location).lat)) != 0) return -7;
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &((s->location).lon)) != 0) return -7;
    for (uint32_t ri0 = 0; ri0 < 4; ++ri0) {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->samples[ri0])) != 0) return -7;
    }
    {
        uint8_t present = 0;
        if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &present) != 0) return -7;
        s->calibration_present = present;
        if (present) {
    if (zerodds_xcdr2_c_read_f64(buf, len, &pos, &(s->calibration)) != 0) return -7;
        }
    }
    {
        uint8_t present = 0;
        if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &present) != 0) return -7;
        s->note_present = present;
        if (present) {
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(s->note)) != 0) return -7;
        }
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void conf_SensorReading_sample_free(void* sample) {
    if (sample == NULL) return;
    conf_SensorReading_t* s = (conf_SensorReading_t*)sample;
    (void)s;
    free(s->site); s->site = NULL;
    free(s->note); s->note = NULL;
}

static int conf_SensorReading_key_hash(const void* sample, uint8_t out_hash[16]) {
    const conf_SensorReading_t* s = (const conf_SensorReading_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->sensor_id) != 0) { free(kh_buf); return -1; }
    if (zerodds_xcdr2_c_kh_write_string(&kh_buf, &kh_len, &kh_cap, s->site) != 0) { free(kh_buf); return -1; }
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

#ifdef __cplusplus
}
#endif
#endif

/* XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised) */
static const unsigned char conf_Status_type_object[] = {
    0x40, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x7e, 0xd9, 0x29, 0xf4, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xaa, 0x2f, 0xa3, 0xfb, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x21, 0x01, 0x70, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x89, 0x3b, 0x3a, 0xaf,
};
static const unsigned char conf_Celsius_type_object[] = {
    0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a,
};
static const unsigned char conf_GeoPoint_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x40, 0x73, 0xd4, 0x1b, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0xa7, 0xbc, 0x1a, 0xd1,
};
static const unsigned char conf_TemperatureType_type_object[] = {
    0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x9b, 0x3f, 0x0e, 0xd4, 0x20,
    0x14, 0x6c, 0x00, 0xc6, 0xd1, 0x0e, 0xff, 0xb3, 0x5a,
};
static const unsigned char conf_SensorReading_type_object[] = {
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0xd9, 0x6d, 0x86, 0x6a, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x70, 0x10, 0x98, 0xde, 0xfd, 0x6e,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x45, 0x88, 0x2c, 0x2f, 0xb8,
    0x3e, 0x20, 0xdf, 0x2a, 0x9a, 0xfd, 0x47, 0x55, 0xcb, 0x9a, 0xcb, 0x44,
    0x54, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0xf7,
    0x09, 0x04, 0xe3, 0xde, 0x32, 0x85, 0xb8, 0x96, 0xab, 0xcf, 0xee, 0x7d,
    0xd6, 0xee, 0xf4, 0x38, 0xf7, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xf1, 0x17, 0x11, 0x5e, 0x82, 0x62, 0xc8, 0xf0, 0x18, 0xae,
    0xa6, 0xba, 0xa3, 0x7c, 0x88, 0xd5, 0x18, 0x9d, 0xe0, 0x00, 0x00, 0x00,
    0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x6e, 0xf9, 0x16, 0x1b, 0x00,
    0x07, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0a, 0x0b, 0xf7, 0x19, 0xdf, 0x00,
    0x08, 0x00, 0x00, 0x00, 0x08, 0x00, 0x70, 0x00, 0xaa, 0xd6, 0x53, 0xca,
};
