// Generated by zerodds idl-csharp. Do not edit.
// Target: C# 12.0 / .NET 8+
#nullable enable

using Omg.Types;
using System;
using System.Collections.Generic;
using ZeroDDS.Cdr;

namespace combo
{
    public enum Mode : int
    {
        MODE_IDLE,
        MODE_ACTIVE,
        MODE_FAULT,
    }

    // typedef double CurrentInAmpsType;
    public sealed record class CurrentInAmpsType(double Value);

    public partial record class Sample : ITopicType<Sample>
    {
        public int Seq { get; init; } = default!;
        public double Value { get; init; } = default!;
    }

    public sealed class SampleTypeSupport : IDdsTopicType<Sample>
    {
        public static readonly SampleTypeSupport Instance = new();

        public string TypeName => "combo::Sample";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Final;

        public byte[] Encode(Sample sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Sample sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Sample sample)
        {
            w.WriteInt32(sample.Seq);
            w.WriteFloat64(sample.Value);
        }

        public Sample Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Sample DecodeFrom(ref Xcdr2Reader r)
        {
            int __m0 = default!;
            __m0 = r.ReadInt32();
            double __m1 = default!;
            __m1 = r.ReadFloat64();
            return new Sample
            {
                Seq = __m0!,
                Value = __m1!,
            };
        }

        public byte[] KeyHash(Sample sample)
        {
            return new byte[16];
        }
    }

    public partial record class Reading : ITopicType<Reading>
    {
        public Mode Discriminator { get; init; } = default!;
        public object? Value { get; init; } = default;

        // case MODE_IDLE -> idleTicks
        // case MODE_ACTIVE -> activeRate
        // case default -> faultCode
    }

    public sealed class ReadingTypeSupport : IDdsTopicType<Reading>
    {
        public static readonly ReadingTypeSupport Instance = new();

        public string TypeName => "combo::Reading";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Final;

        public byte[] Encode(Reading sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Reading sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Reading sample)
        {
            w.WriteInt32((int)sample.Discriminator);
            switch (sample.Discriminator)
            {
                case Mode.MODE_IDLE:
                    w.WriteInt32(((int)sample.Value!));
                    break;
                case Mode.MODE_ACTIVE:
                    w.WriteFloat64(((double)sample.Value!));
                    break;
                default:
                    if ((((string)sample.Value!)) != null && System.Text.Encoding.UTF8.GetByteCount(((string)sample.Value!)) > 16) throw new System.ArgumentException("bounded string length exceeds its IDL bound (16)");
                    w.WriteString(((string)sample.Value!));
                    break;
            }
        }

        public Reading Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Reading DecodeFrom(ref Xcdr2Reader r)
        {
            Mode __disc = (Mode)(r.ReadInt32());
            object? __val = null;
            switch (__disc)
            {
                case Mode.MODE_IDLE:
                    {
                        int __uv0;
                        __uv0 = r.ReadInt32();
                        __val = __uv0;
                    }
                    break;
                case Mode.MODE_ACTIVE:
                    {
                        double __uv1;
                        __uv1 = r.ReadFloat64();
                        __val = __uv1;
                    }
                    break;
                default:
                    {
                        string __uv2;
                        __uv2 = r.ReadString();
                        __val = __uv2;
                    }
                    break;
            }
            return new Reading { Discriminator = __disc, Value = __val };
        }

        public byte[] KeyHash(Reading sample)
        {
            return new byte[16];
        }
    }


    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Telemetry : ITopicType<Telemetry>
    {
        [Key]
        public int UnitId { get; init; } = default!;
        [Key]
        public string Region { get; init; } = default!;
        public Mode Mode { get; init; } = default!;
        public CurrentInAmpsType BatteryCurrent { get; init; } = default!;
        public ISequence<Sample> History { get; init; } = default!;
        public Reading Reading { get; init; } = default!;
        public IDictionary<string, int> Counters { get; init; } = default!;
        [Optional]
        public double? Calibration { get; init; } = default!;
        public int[] Window { get; init; } = default!;
    }

    public sealed class TelemetryTypeSupport : IDdsTopicType<Telemetry>
    {
        public static readonly TelemetryTypeSupport Instance = new();

        public string TypeName => "combo::Telemetry";
        public bool IsKeyed => true;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Telemetry sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Telemetry sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Telemetry sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteInt32(sample.UnitId);
                if ((sample.Region) != null && System.Text.Encoding.UTF8.GetByteCount(sample.Region) > 32) throw new System.ArgumentException("bounded string length exceeds its IDL bound (32)");
                w.WriteString(sample.Region);
                w.WriteInt32((int)sample.Mode);
                w.WriteFloat64((sample.BatteryCurrent).Value);
                {
                    var __seq0 = (sample.History) as System.Collections.Generic.IEnumerable<Sample>;
                    var __mat0 = __seq0 is null ? new System.Collections.Generic.List<Sample>() : new System.Collections.Generic.List<Sample>(__seq0);
                    using (var __seqdh0 = w.BeginAppendable())
                    {
                        w.WriteSequenceLength(__mat0.Count);
                        foreach (var __item0 in __mat0)
                        {
                            SampleTypeSupport.Instance.EncodeInto(w, __item0);
                        }
                    }
                }
                ReadingTypeSupport.Instance.EncodeInto(w, sample.Reading);
                {
                    var __map0 = (sample.Counters) ?? new System.Collections.Generic.Dictionary<string, int>();
                    using (var __mapdh0 = w.BeginAppendable())
                    {
                        w.WriteSequenceLength(__map0.Count);
                        foreach (var __kv0 in __map0)
                        {
                            w.WriteString(__kv0.Key);
                            w.WriteInt32(__kv0.Value);
                        }
                    }
                }
                if (sample.Calibration is null) { w.WriteOctet(0); }
                else
                {
                    w.WriteOctet(1);
                    w.WriteFloat64(sample.Calibration.Value);
                }
                for (int __a0 = 0; __a0 < 4; __a0++)
                {
                    w.WriteInt32(sample.Window[__a0]);
                }
            }
        }

        public Telemetry Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Telemetry DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int __m0 = default!;
            __m0 = r.ReadInt32();
            string __m1 = default!;
            __m1 = r.ReadString();
            Mode __m2 = default!;
            __m2 = (Mode)r.ReadInt32();
            CurrentInAmpsType __m3 = default!;
            __m3 = new CurrentInAmpsType(r.ReadFloat64());
            Omg.Types.ISequence<Sample> __m4 = default!;
            {
                var __seqdh0 = r.BeginDHeader();
                int __cnt0 = r.ReadSequenceLength();
                var __list0 = new Omg.Types.SequenceList<Sample>();
                for (int __i0 = 0; __i0 < __cnt0; __i0++)
                {
                    Sample __e0;
                    __e0 = SampleTypeSupport.Instance.DecodeFrom(ref r);
                    __list0.Add(__e0);
                }
                r.EndDHeader(__seqdh0);
                __m4 = __list0;
            }
            Reading __m5 = default!;
            __m5 = ReadingTypeSupport.Instance.DecodeFrom(ref r);
            System.Collections.Generic.IDictionary<string, int> __m6 = default!;
            {
                var __mapdh0 = r.BeginDHeader();
                int __mcnt0 = r.ReadSequenceLength();
                var __dict0 = new System.Collections.Generic.Dictionary<string, int>();
                for (int __mi0 = 0; __mi0 < __mcnt0; __mi0++)
                {
                    string __mk0;
                    __mk0 = r.ReadString();
                    int __mv0;
                    __mv0 = r.ReadInt32();
                    __dict0[__mk0] = __mv0;
                }
                r.EndDHeader(__mapdh0);
                __m6 = __dict0;
            }
            double? __m7 = default!;
            {
                byte __present = r.ReadOctet();
                if (__present != 0)
                {
                    __m7 = r.ReadFloat64();
                }
            }
            int[] __m8 = default!;
            __m8 = new int[4];
            for (int __da0 = 0; __da0 < 4; __da0++)
            {
                __m8[__da0] = r.ReadInt32();
            }
            r.EndDHeader(__scope);
            return new Telemetry
            {
                UnitId = __m0!,
                Region = __m1!,
                Mode = __m2!,
                BatteryCurrent = __m3!,
                History = __m4!,
                Reading = __m5!,
                Counters = __m6!,
                Calibration = __m7!,
                Window = __m8!,
            };
        }

        public byte[] KeyHash(Telemetry sample)
        {
            var __kw = new Xcdr2Writer(EndianMode.BigEndian);
            __kw.WriteInt32(sample.UnitId);
            __kw.WriteString(sample.Region);
            var __kb = __kw.ToArray();
            if (__kb.Length > 16) { return Md5.Hash(__kb); }
            var __h = new byte[16];
            System.Array.Copy(__kb, 0, __h, 0, __kb.Length);
            return __h;
        }
    }

} // namespace combo

// XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised)
public static class TypeObjects
{
    /// <summary>Minimal TypeObject for combo::Mode.</summary>
    public static readonly byte[] combo_Mode = {
        0x40, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xdb, 0x78, 0xd3, 0x17, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x15, 0xd1, 0xdf, 0x00, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb2, 0xc5, 0xb2, 0x9f,
    };
    /// <summary>Minimal TypeObject for combo::CurrentInAmpsType.</summary>
    public static readonly byte[] combo_CurrentInAmpsType = {
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a,
    };
    /// <summary>Minimal TypeObject for combo::Sample.</summary>
    public static readonly byte[] combo_Sample = {
        0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe0, 0x68, 0xc2, 0xde, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x20, 0x63, 0xc1, 0x60,
    };
    /// <summary>Minimal TypeObject for combo::Reading.</summary>
    public static readonly byte[] combo_Reading = {
        0x51, 0x00, 0x02, 0x00, 0x00, 0x00, 0xf1, 0x31, 0xcc, 0xe6, 0x28, 0xbb,
        0xdf, 0x5a, 0xc9, 0x28, 0x23, 0xc7, 0x8a, 0x34, 0x7c, 0x00, 0x00, 0x00,
        0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xc2, 0x90, 0x82, 0x81,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0xe5, 0xf9, 0x08, 0xde, 0x03, 0x00, 0x00, 0x00,
        0x40, 0x00, 0x70, 0x10, 0x00, 0x00, 0x00, 0x00, 0x60, 0x1f, 0x94, 0x40,
    };
    /// <summary>Minimal TypeObject for combo::Telemetry.</summary>
    public static readonly byte[] combo_Telemetry = {
        0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x3a, 0xe0, 0xf2, 0xbc, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x70, 0x20, 0x96, 0x0d, 0xb2, 0xed,
        0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x31, 0xcc, 0xe6, 0x28, 0xbb,
        0xdf, 0x5a, 0xc9, 0x28, 0x23, 0xc7, 0x8a, 0x34, 0x7c, 0x15, 0xd6, 0x17,
        0x12, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x9b,
        0x3f, 0x0e, 0xd4, 0x20, 0x14, 0x6c, 0x00, 0xc6, 0xd1, 0x0e, 0xff, 0xb3,
        0x5a, 0x9d, 0x04, 0xf4, 0xe2, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x80, 0xf1, 0x00, 0x00, 0x00, 0xf1, 0x80, 0xf9, 0xa0, 0x9d,
        0x09, 0xf3, 0x9b, 0x8e, 0x8e, 0x3a, 0x55, 0x17, 0x44, 0xc1, 0x3c, 0xd1,
        0x5f, 0x8f, 0x00, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x57,
        0xd7, 0xce, 0x95, 0xf7, 0xae, 0xe2, 0x3d, 0x50, 0x74, 0xdf, 0xfa, 0x32,
        0xc2, 0xec, 0xea, 0xdc, 0x1d, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00,
        0x00, 0x00, 0xa0, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x70, 0x00,
        0x09, 0x76, 0xbd, 0xd4, 0x08, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0a, 0x0b,
        0xf7, 0x19, 0xdf, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x05,
        0xb8, 0xc7, 0x4c,
    };
}
