#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""WIRE-level XCDR2 interop goldens for the ZeroDDS Python PSM — the FEATURE
corpus (`features.idl`): WStr, Mut, Bits, Tree, Arr, Prim.

For each feature this script:
  * ENCODE        -> serialize the CANONICAL.md sample via the generated
                     `@idl_struct.encode()` (the exact XCDR2-LE bytes a ZeroDDS
                     Python DataWriter puts on the wire) and write
                     `goldens/<feature>.python.bin`.
  * DECODE <file> -> read the bytes back via `.decode()` and assert the
                     reconstructed value == the canonical sample.

The Rust golden (`goldens/<feature>.rust.bin`) is the cross-PSM REFERENCE; this
Python PSM must produce byte-identical goldens AND decode the Rust golden back to
the canonical sample (CANONICAL.md "Convergence criterion").

Usage:
    features_interop.py ENCODE              # write all python goldens
    features_interop.py DECODE [rust|python] # decode that PSM's goldens, assert
    features_interop.py ROUNDTRIP           # encode + decode-python + decode-rust
"""
import os
import sys

# Make the zerodds runtime importable and the generated module loadable.
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(_REPO, "crates", "py", "python"))
sys.path.insert(0, _HERE)

import features  # noqa: E402  (generated by zerodds-idlc --python)

WStr = features.feat_WStr
Mut = features.feat_Mut
Bits = features.feat_Bits
Perm = features.feat_Perm
Flags_Bits = features.feat_Flags_Bits
Tree = features.feat_Tree
Arr = features.feat_Arr
Pt = features.feat_Pt
Prim = features.feat_Prim
MutLeaf = features.feat_MutLeaf
MutNest = features.feat_MutNest
NestedKey = features.feat_NestedKey
OuterKey = features.feat_OuterKey
Sel = features.feat_Sel
MapEnum = features.feat_MapEnum
MapPrim = features.feat_MapPrim
Money = features.feat_Money
Hue = features.feat_Hue

GOLDENS = os.path.join(_HERE, "..", "goldens")


# ---------------------------------------------------------------------------
# Canonical samples (EXACT values from CANONICAL.md; identical across all PSMs)
# ---------------------------------------------------------------------------

def canonical_wstr():
    # label="café" (c a f é/U+00E9), text="日本語🎉" (🎉 = U+1F389).
    return WStr(label="café", text="日本語\U0001F389")


def canonical_mut():
    # @mutable: a(@id10)=1000000, b(@id20)=2.5, c(@id30)="ok".
    return Mut(a=1_000_000, b=2.5, c="ok")


def canonical_bits():
    # perm = READ|EXEC = 0x05; flags: kind=5, prio=20 -> holder 0xA5.
    flags = (20 << Flags_Bits.PRIO_SHIFT) | (5 << Flags_Bits.KIND_SHIFT)
    return Bits(perm=Perm.READ | Perm.EXEC, flags=flags)


def canonical_tree():
    # root{1, [ {2,[ {4,[]} ]}, {3,[]} ]}.
    return Tree(
        value=1,
        kids=[
            Tree(value=2, kids=[Tree(value=4, kids=[])]),
            Tree(value=3, kids=[]),
        ],
    )


def canonical_arr():
    # grid[2][3]=[[10,11,12],[13,14,15]] row-major; shape[2]=[{1,2},{3,4}].
    return Arr(
        grid=[[10, 11, 12], [13, 14, 15]],
        shape=[Pt(x=1, y=2), Pt(x=3, y=4)],
    )


def canonical_mapenum():
    # @bit_bound(16) enum h=H_BLUE(2); map<long,Pt> m={3:{11,12}}; sequence<Sel> sels=[Sel(n=9)].
    return MapEnum(h=Hue.H_BLUE, m={3: Pt(x=11, y=12)}, sels=[Sel.make(2, 9)])


def canonical_mapprim():
    # map<long,long> primitive-valued -> NO collection DHEADER (XCDR2 §7.4.3.5).
    return MapPrim(m={7: 42, 8: 99})


def canonical_fixed():
    # fixed<P,S> CORBA-BCD: price=123.45 (12 34 5c), qty=1234 (01 23 4c).
    # The Python value is the decimal as a str (the Fixed[P,S] brand).
    return Money(price="123.45", qty="1234")


def canonical_prim():
    return Prim(
        i8=-128, u8=255, i16=-32768, u16=65535,
        i32=-2_147_483_648, u32=4_294_967_295,
        i64=-9_223_372_036_854_775_808, u64=18_446_744_073_709_551_615,
        f32=3.5, f64=-1234.5, b=True, o=0xAB, ch="Z",
    )


def canonical_mutnest():
    # @mutable nested-mutable + non-primitive sequence: tag(@id10)=9,
    # leaf(@id20)={u=100, v=1.25}, list(@id30)=[{u=1,v=0.5},{u=2,v=0.25}].
    # The nested @mutable leaf and the sequence<MutLeaf> each begin their body
    # with a DHEADER, so their EMHEADERs use LengthCode 5 (the leading word is
    # reused as the NEXTINT). tag is a primitive long -> LC2.
    return MutNest(
        tag=9,
        leaf=MutLeaf(u=100, v=1.25),
        list=[MutLeaf(u=1, v=0.5), MutLeaf(u=2, v=0.25)],
    )


def canonical_outerkey():
    # @final OuterKey with a nested @final NestedKey: k={hi=0x01020304,
    # lo=0x05060708}, payload=999. A @final nested struct is tight-packed (no
    # DHEADER); both structs are @final so the whole thing is positional.
    return OuterKey(
        k=NestedKey(hi=0x01020304, lo=0x05060708),
        payload=999,
    )


FEATURES = {
    "wstr": (WStr, canonical_wstr),
    "mut": (Mut, canonical_mut),
    "bits": (Bits, canonical_bits),
    "tree": (Tree, canonical_tree),
    "arr": (Arr, canonical_arr),
    "prim": (Prim, canonical_prim),
    "mutnest": (MutNest, canonical_mutnest),
    "outerkey": (OuterKey, canonical_outerkey),
    "mapenum": (MapEnum, canonical_mapenum),
    "mapprim": (MapPrim, canonical_mapprim),
    "fixed": (Money, canonical_fixed),
}


# ---------------------------------------------------------------------------
# Equality (Bits.flags is a plain int; the rest compare by dataclass __eq__).
# ---------------------------------------------------------------------------

def equal(a, b):
    return a == b


def encode_all():
    ok = True
    for name, (_cls, mk) in FEATURES.items():
        data = mk().encode()
        path = os.path.join(GOLDENS, f"{name}.python.bin")
        with open(path, "wb") as f:
            f.write(data)
        print(f"ENCODE {name}: {len(data)} bytes -> {path}")
        print("  hex:", " ".join(f"{b:02x}" for b in data))
    return ok


def decode_all(psm):
    ok = True
    for name, (cls, mk) in FEATURES.items():
        path = os.path.join(GOLDENS, f"{name}.{psm}.bin")
        with open(path, "rb") as f:
            data = f.read()
        got = cls.decode(data)
        want = mk()
        if equal(got, want):
            print(f"DECODE {name} ({psm}): OK ({len(data)} bytes) == canonical")
        else:
            print(f"DECODE {name} ({psm}): MISMATCH")
            print(f"  want={want!r}")
            print(f"  got ={got!r}")
            ok = False
    return ok


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "ROUNDTRIP"
    if mode == "ENCODE":
        return 0 if encode_all() else 1
    if mode == "DECODE":
        psm = sys.argv[2] if len(sys.argv) > 2 else "rust"
        return 0 if decode_all(psm) else 1
    if mode == "ROUNDTRIP":
        ok = encode_all()
        ok = decode_all("python") and ok
        ok = decode_all("rust") and ok
        return 0 if ok else 1
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
