# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from enum import IntEnum, IntFlag
from typing import Dict, List, TypeAlias
from zerodds.idl import idl_struct, idl_union, Array, Bitset, Bool, BoundedString, BoundedWString, Char, Float32, Float64, Int16, Int32, Int64, Int8, Octet, UInt16, UInt32, UInt64, UInt8, WString

@idl_struct(typename="feat::WStr", extensibility="appendable")
@dataclass
class feat_WStr:
    label: BoundedWString[16]
    text: WString

@idl_struct(typename="feat::Mut", extensibility="mutable", member_ids=[10, 20, 30])
@dataclass
class feat_Mut:
    a: Int32
    b: Float64
    c: BoundedString[8]

@idl_struct(typename="feat::MutLeaf", extensibility="mutable", member_ids=[1, 2])
@dataclass
class feat_MutLeaf:
    u: Int32
    v: Float64

@idl_struct(typename="feat::MutNest", extensibility="mutable", member_ids=[10, 20, 30])
@dataclass
class feat_MutNest:
    tag: Int32
    leaf: feat_MutLeaf
    list: List[feat_MutLeaf]

@idl_struct(typename="feat::NestedKey")
@dataclass
class feat_NestedKey:
    hi: Int32
    lo: Int32

@idl_struct(typename="feat::OuterKey")
@dataclass
class feat_OuterKey:
    k: feat_NestedKey
    payload: Int32

class feat_Perm(IntFlag):
    READ = 1 << 0
    WRITE = 1 << 1
    EXEC = 1 << 2
feat_Perm._idl_bit_bound = 32

feat_Flags: TypeAlias = Bitset[8]

class feat_Flags_Bits:
    KIND_SHIFT = 0
    KIND_WIDTH = 3
    KIND_MASK  = 0x7
    PRIO_SHIFT = 3
    PRIO_WIDTH = 5
    PRIO_MASK  = 0x1f

@idl_struct(typename="feat::Bits", extensibility="appendable")
@dataclass
class feat_Bits:
    perm: feat_Perm
    flags: feat_Flags

@idl_struct(typename="feat::Tree", extensibility="appendable")
@dataclass
class feat_Tree:
    value: Int32
    kids: List[feat_Tree]

@idl_struct(typename="feat::Pt", extensibility="appendable")
@dataclass
class feat_Pt:
    x: Int32
    y: Int32

@idl_struct(typename="feat::Arr", extensibility="appendable")
@dataclass
class feat_Arr:
    grid: Array[Array[Int32, 3], 2]
    shape: Array[feat_Pt, 2]

feat_Sel = idl_union(
    typename="feat::Sel",
    discriminator=Int32,
    cases={
        1: ("p", feat_Pt),
        2: ("n", Int32),
    },
    default=("z", Octet),
    extensibility="appendable",
)

class feat_Hue(IntEnum):
    H_RED = 0
    H_GREEN = 1
    H_BLUE = 2
feat_Hue._idl_bit_bound = 16

@idl_struct(typename="feat::MapEnum", extensibility="appendable")
@dataclass
class feat_MapEnum:
    h: feat_Hue
    m: Dict[Int32, feat_Pt]
    sels: List[feat_Sel]

@idl_struct(typename="feat::Prim", extensibility="appendable")
@dataclass
class feat_Prim:
    i8: Int8
    u8: UInt8
    i16: Int16
    u16: UInt16
    i32: Int32
    u32: UInt32
    i64: Int64
    u64: UInt64
    f32: Float32
    f64: Float64
    b: Bool
    o: Octet
    ch: Char

