#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""WIRE-level XCDR2 interop goldens for the ZeroDDS Python PSM — the FEATURE
corpus (`features.idl`): WStr, Mut, Bits, Tree, Arr, Prim.

For each feature this script:
  * ENCODE        -> serialize the CANONICAL.md sample via the generated
                     `@idl_struct.encode()` (the exact XCDR2-LE bytes a ZeroDDS
                     Python DataWriter puts on the wire) and write
                     `goldens/<feature>.python.bin`.
  * DECODE <file> -> read the bytes back via `.decode()` and assert the
                     reconstructed value == the canonical sample.

The Rust golden (`goldens/<feature>.rust.bin`) is the cross-PSM REFERENCE; this
Python PSM must produce byte-identical goldens AND decode the Rust golden back to
the canonical sample (CANONICAL.md "Convergence criterion").

Usage:
    features_interop.py ENCODE              # write all python goldens
    features_interop.py DECODE [rust|python] # decode that PSM's goldens, assert
    features_interop.py ROUNDTRIP           # encode + decode-python + decode-rust
"""
import os
import sys

# Make the zerodds runtime importable and the generated module loadable.
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.abspath(os.path.join(_HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(_REPO, "crates", "py", "python"))
sys.path.insert(0, _HERE)

import features  # noqa: E402  (generated by zerodds-idlc --python)

WStr = features.feat_WStr
Mut = features.feat_Mut
Bits = features.feat_Bits
Perm = features.feat_Perm
Flags_Bits = features.feat_Flags_Bits
Tree = features.feat_Tree
Arr = features.feat_Arr
Pt = features.feat_Pt
Prim = features.feat_Prim

GOLDENS = os.path.join(_HERE, "..", "goldens")


# ---------------------------------------------------------------------------
# Canonical samples (EXACT values from CANONICAL.md; identical across all PSMs)
# ---------------------------------------------------------------------------

def canonical_wstr():
    # label="café" (c a f é/U+00E9), text="日本語🎉" (🎉 = U+1F389).
    return WStr(label="café", text="日本語\U0001F389")


def canonical_mut():
    # @mutable: a(@id10)=1000000, b(@id20)=2.5, c(@id30)="ok".
    return Mut(a=1_000_000, b=2.5, c="ok")


def canonical_bits():
    # perm = READ|EXEC = 0x05; flags: kind=5, prio=20 -> holder 0xA5.
    flags = (20 << Flags_Bits.PRIO_SHIFT) | (5 << Flags_Bits.KIND_SHIFT)
    return Bits(perm=Perm.READ | Perm.EXEC, flags=flags)


def canonical_tree():
    # root{1, [ {2,[ {4,[]} ]}, {3,[]} ]}.
    return Tree(
        value=1,
        kids=[
            Tree(value=2, kids=[Tree(value=4, kids=[])]),
            Tree(value=3, kids=[]),
        ],
    )


def canonical_arr():
    # grid[2][3]=[[10,11,12],[13,14,15]] row-major; shape[2]=[{1,2},{3,4}].
    return Arr(
        grid=[[10, 11, 12], [13, 14, 15]],
        shape=[Pt(x=1, y=2), Pt(x=3, y=4)],
    )


def canonical_prim():
    return Prim(
        i8=-128, u8=255, i16=-32768, u16=65535,
        i32=-2_147_483_648, u32=4_294_967_295,
        i64=-9_223_372_036_854_775_808, u64=18_446_744_073_709_551_615,
        f32=3.5, f64=-1234.5, b=True, o=0xAB, ch="Z",
    )


FEATURES = {
    "wstr": (WStr, canonical_wstr),
    "mut": (Mut, canonical_mut),
    "bits": (Bits, canonical_bits),
    "tree": (Tree, canonical_tree),
    "arr": (Arr, canonical_arr),
    "prim": (Prim, canonical_prim),
}


# ---------------------------------------------------------------------------
# Equality (Bits.flags is a plain int; the rest compare by dataclass __eq__).
# ---------------------------------------------------------------------------

def equal(a, b):
    return a == b


def encode_all():
    ok = True
    for name, (_cls, mk) in FEATURES.items():
        data = mk().encode()
        path = os.path.join(GOLDENS, f"{name}.python.bin")
        with open(path, "wb") as f:
            f.write(data)
        print(f"ENCODE {name}: {len(data)} bytes -> {path}")
        print("  hex:", " ".join(f"{b:02x}" for b in data))
    return ok


def decode_all(psm):
    ok = True
    for name, (cls, mk) in FEATURES.items():
        path = os.path.join(GOLDENS, f"{name}.{psm}.bin")
        with open(path, "rb") as f:
            data = f.read()
        got = cls.decode(data)
        want = mk()
        if equal(got, want):
            print(f"DECODE {name} ({psm}): OK ({len(data)} bytes) == canonical")
        else:
            print(f"DECODE {name} ({psm}): MISMATCH")
            print(f"  want={want!r}")
            print(f"  got ={got!r}")
            ok = False
    return ok


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "ROUNDTRIP"
    if mode == "ENCODE":
        return 0 if encode_all() else 1
    if mode == "DECODE":
        psm = sys.argv[2] if len(sys.argv) > 2 else "rust"
        return 0 if decode_all(psm) else 1
    if mode == "ROUNDTRIP":
        ok = encode_all()
        ok = decode_all("python") and ok
        ok = decode_all("rust") and ok
        return 0 if ok else 1
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
