// Generated by zerodds idl-ts. Do not edit.

import type {
    Char, WChar, LongDouble,
    DdsAny, DdsException,
    DdsTypeDescriptor, DdsMemberDescriptor, DdsTypeRef,
    ServiceDescriptor, OperationDescriptor,
    OperationParameterDescriptor, AttributeDescriptor, ParameterMode,
} from "@zerodds/types";
import {
    registerType, makeChar, makeWChar, makeLongDouble,
} from "@zerodds/types";
import type {
    DdsTopicType, EndianMode,
} from "@zerodds/cdr";
import {
    Xcdr2Writer, Xcdr2Reader, md5,
} from "@zerodds/cdr";

export interface Reading {
    /**
     * @dds-key
     */
    id: number;
    seq: number;
    value: number;
}

export function isReading(v: unknown): v is Reading {
    if (typeof v !== "object" || v === null) return false;
    const o = v as Record<string, unknown>;
    if (typeof o.id !== "number") return false;
    if (typeof o.seq !== "number") return false;
    if (typeof o.value !== "number") return false;
    return true;
}

export const ReadingType: DdsTypeDescriptor<Reading> = {
    kind: "struct",
    name: "Reading",
    extensibility: "appendable",
    nested: false,
    fields: [
        {
            name: "id",
            id: 0,
            type: { kind: "primitive", name: "int32" },
            key: true,
            optional: false,
            mustUnderstand: false,
        },
        {
            name: "seq",
            id: 1,
            type: { kind: "primitive", name: "int32" },
            key: false,
            optional: false,
            mustUnderstand: false,
        },
        {
            name: "value",
            id: 2,
            type: { kind: "primitive", name: "double" },
            key: false,
            optional: false,
            mustUnderstand: false,
        },
    ],
    typeGuard: isReading,
};
registerType(ReadingType);

export const ReadingTypeSupport: DdsTopicType<Reading> = {
    typeName: "Reading",
    isKeyed: true,
    extensibility: "appendable",
    encodeInto(w: Xcdr2Writer, s: Reading): void {
        const _tok = w.beginAppendable();
        w.writeInt32(s.id);
        w.writeInt32(s.seq);
        w.writeFloat64(s.value);
        w.endAppendable(_tok);
    },
    encode(s: Reading, endian: EndianMode = "le"): Uint8Array {
        const w = new Xcdr2Writer(endian);
        this.encodeInto(w, s);
        return w.toBytes();
    },
    decodeFrom(r: Xcdr2Reader): Reading {
        const _tok = r.beginAppendable();
        const _f_id: number = r.readInt32();
        const _f_seq: number = r.readInt32();
        const _f_value: number = r.readFloat64();
        r.endAppendable(_tok);
        return {
            id: _f_id,
            seq: _f_seq,
            value: _f_value,
        };
    },
    decode(bytes: Uint8Array, offset = 0, length: number = bytes.length - offset): Reading {
        const r = new Xcdr2Reader(bytes, offset, length, "le");
        return this.decodeFrom(r);
    },
    keyHash(s: Reading): Uint8Array {
        const w = new Xcdr2Writer("be");
        w.writeInt32(s.id);
        const __holder = w.toBytes();
        if (__holder.length <= 16) {
            const __h = new Uint8Array(16);
            __h.set(__holder);
            return __h;
        }
        return md5(__holder);
    },
};


// XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised)
/** Minimal TypeObject for Reading. */
export const Reading = new Uint8Array([
    0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0xb8, 0x0b, 0xb7, 0x74, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xe0, 0x68, 0xc2, 0xde, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x20, 0x63, 0xc1, 0x60,
]);
