// Generated by zerodds idl-csharp. Do not edit.
// Target: C# 12.0 / .NET 8+
#nullable enable

using Omg.Types;
using System;
using System.Collections.Generic;
using ZeroDDS.Cdr;

namespace feat
{
    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class WStr : ITopicType<WStr>
    {
        public string Label { get; init; } = default!;
        public string Text { get; init; } = default!;
    }

    public sealed class WStrTypeSupport : IDdsTopicType<WStr>
    {
        public static readonly WStrTypeSupport Instance = new();

        public string TypeName => "feat::WStr";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(WStr sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(WStr sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, WStr sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                if ((sample.Label) != null && (sample.Label).Length > 16) throw new System.ArgumentException("bounded wstring length exceeds its IDL bound (16)");
                {
                    var __ws = (sample.Label) ?? string.Empty;
                    w.WriteUInt32((uint)(__ws.Length * 2));
                    for (int __wi = 0; __wi < __ws.Length; __wi++)
                    {
                        w.WriteUInt16(__ws[__wi]);
                    }
                }
                {
                    var __ws = (sample.Text) ?? string.Empty;
                    w.WriteUInt32((uint)(__ws.Length * 2));
                    for (int __wi = 0; __wi < __ws.Length; __wi++)
                    {
                        w.WriteUInt16(__ws[__wi]);
                    }
                }
            }
        }

        public WStr Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public WStr DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            string __m0 = default!;
            {
                uint __woct0 = r.ReadUInt32();
                var __wsb0 = new System.Text.StringBuilder((int)(__woct0 / 2));
                for (uint __wj0 = 0; __wj0 + 1 < __woct0; __wj0 += 2)
                {
                    __wsb0.Append((char)r.ReadUInt16());
                }
                __m0 = __wsb0.ToString();
            }
            string __m1 = default!;
            {
                uint __woct0 = r.ReadUInt32();
                var __wsb0 = new System.Text.StringBuilder((int)(__woct0 / 2));
                for (uint __wj0 = 0; __wj0 + 1 < __woct0; __wj0 += 2)
                {
                    __wsb0.Append((char)r.ReadUInt16());
                }
                __m1 = __wsb0.ToString();
            }
            r.EndDHeader(__scope);
            return new WStr
            {
                Label = __m0!,
                Text = __m1!,
            };
        }

        public byte[] KeyHash(WStr sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Mutable)]
    public partial record class Mut : ITopicType<Mut>
    {
        [Id(10)]
        public int A { get; init; } = default!;
        [Id(20)]
        public double B { get; init; } = default!;
        [Id(30)]
        public string C { get; init; } = default!;
    }

    public sealed class MutTypeSupport : IDdsTopicType<Mut>
    {
        public static readonly MutTypeSupport Instance = new();

        public string TypeName => "feat::Mut";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Mutable;

        public byte[] Encode(Mut sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Mut sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Mut sample)
        {
            using (var __scope = w.BeginMutable())
            {
                w.WriteEmHeader(10u, 2, false);
                w.WriteInt32(sample.A);
                w.WriteEmHeader(20u, 3, false);
                w.WriteFloat64(sample.B);
                w.WriteEmHeader(30u, 5, false);
                if ((sample.C) != null && System.Text.Encoding.UTF8.GetByteCount(sample.C) > 8) throw new System.ArgumentException("bounded string length exceeds its IDL bound (8)");
                w.WriteString(sample.C);
            }
        }

        public Mut Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Mut DecodeFrom(ref Xcdr2Reader r)
        {
            int __m0 = default!;
            double __m1 = default!;
            string __m2 = default!;
            var __scope = r.BeginDHeader();
            while (!r.DHeaderDone(__scope))
            {
                var (__id, __lc, __mu) = r.ReadEmHeader();
                if (__lc == 4) { var __nx = r.ReadUInt32(); _ = __nx; }
                switch (__id)
                {
                    case 10u:
                        __m0 = r.ReadInt32();
                        break;
                    case 20u:
                        __m1 = r.ReadFloat64();
                        break;
                    case 30u:
                        __m2 = r.ReadString();
                        break;
                    default:
                        throw new XcdrException($"unknown member id {__id}");
                }
            }
            r.EndDHeader(__scope);
            return new Mut
            {
                A = __m0!,
                B = __m1!,
                C = __m2!,
            };
        }

        public byte[] KeyHash(Mut sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Mutable)]
    public partial record class MutLeaf : ITopicType<MutLeaf>
    {
        [Id(1)]
        public int U { get; init; } = default!;
        [Id(2)]
        public double V { get; init; } = default!;
    }

    public sealed class MutLeafTypeSupport : IDdsTopicType<MutLeaf>
    {
        public static readonly MutLeafTypeSupport Instance = new();

        public string TypeName => "feat::MutLeaf";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Mutable;

        public byte[] Encode(MutLeaf sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(MutLeaf sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, MutLeaf sample)
        {
            using (var __scope = w.BeginMutable())
            {
                w.WriteEmHeader(1u, 2, false);
                w.WriteInt32(sample.U);
                w.WriteEmHeader(2u, 3, false);
                w.WriteFloat64(sample.V);
            }
        }

        public MutLeaf Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public MutLeaf DecodeFrom(ref Xcdr2Reader r)
        {
            int __m0 = default!;
            double __m1 = default!;
            var __scope = r.BeginDHeader();
            while (!r.DHeaderDone(__scope))
            {
                var (__id, __lc, __mu) = r.ReadEmHeader();
                if (__lc == 4) { var __nx = r.ReadUInt32(); _ = __nx; }
                switch (__id)
                {
                    case 1u:
                        __m0 = r.ReadInt32();
                        break;
                    case 2u:
                        __m1 = r.ReadFloat64();
                        break;
                    default:
                        throw new XcdrException($"unknown member id {__id}");
                }
            }
            r.EndDHeader(__scope);
            return new MutLeaf
            {
                U = __m0!,
                V = __m1!,
            };
        }

        public byte[] KeyHash(MutLeaf sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Mutable)]
    public partial record class MutNest : ITopicType<MutNest>
    {
        [Id(10)]
        public int Tag { get; init; } = default!;
        [Id(20)]
        public MutLeaf Leaf { get; init; } = default!;
        [Id(30)]
        public ISequence<MutLeaf> List { get; init; } = default!;
    }

    public sealed class MutNestTypeSupport : IDdsTopicType<MutNest>
    {
        public static readonly MutNestTypeSupport Instance = new();

        public string TypeName => "feat::MutNest";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Mutable;

        public byte[] Encode(MutNest sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(MutNest sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, MutNest sample)
        {
            using (var __scope = w.BeginMutable())
            {
                w.WriteEmHeader(10u, 2, false);
                w.WriteInt32(sample.Tag);
                w.WriteEmHeader(20u, 5, false);
                MutLeafTypeSupport.Instance.EncodeInto(w, sample.Leaf);
                w.WriteEmHeader(30u, 5, false);
                {
                    var __seq0 = (sample.List) as System.Collections.Generic.IEnumerable<MutLeaf>;
                    var __mat0 = __seq0 is null ? new System.Collections.Generic.List<MutLeaf>() : new System.Collections.Generic.List<MutLeaf>(__seq0);
                    using (var __seqdh0 = w.BeginAppendable())
                    {
                        w.WriteSequenceLength(__mat0.Count);
                        foreach (var __item0 in __mat0)
                        {
                            MutLeafTypeSupport.Instance.EncodeInto(w, __item0);
                        }
                    }
                }
            }
        }

        public MutNest Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public MutNest DecodeFrom(ref Xcdr2Reader r)
        {
            int __m0 = default!;
            MutLeaf __m1 = default!;
            Omg.Types.ISequence<MutLeaf> __m2 = default!;
            var __scope = r.BeginDHeader();
            while (!r.DHeaderDone(__scope))
            {
                var (__id, __lc, __mu) = r.ReadEmHeader();
                if (__lc == 4) { var __nx = r.ReadUInt32(); _ = __nx; }
                switch (__id)
                {
                    case 10u:
                        __m0 = r.ReadInt32();
                        break;
                    case 20u:
                        __m1 = MutLeafTypeSupport.Instance.DecodeFrom(ref r);
                        break;
                    case 30u:
                        {
                            var __seqdh0 = r.BeginDHeader();
                            int __cnt0 = r.ReadSequenceLength();
                            var __list0 = new Omg.Types.SequenceList<MutLeaf>();
                            for (int __i0 = 0; __i0 < __cnt0; __i0++)
                            {
                                MutLeaf __e0;
                                __e0 = MutLeafTypeSupport.Instance.DecodeFrom(ref r);
                                __list0.Add(__e0);
                            }
                            r.EndDHeader(__seqdh0);
                            __m2 = __list0;
                        }
                        break;
                    default:
                        throw new XcdrException($"unknown member id {__id}");
                }
            }
            r.EndDHeader(__scope);
            return new MutNest
            {
                Tag = __m0!,
                Leaf = __m1!,
                List = __m2!,
            };
        }

        public byte[] KeyHash(MutNest sample)
        {
            return new byte[16];
        }
    }

    [Nested]
    [Extensibility(ExtensibilityKind.Final)]
    public partial record class NestedKey
    {
        [Key]
        public int Hi { get; init; } = default!;
        [Key]
        public int Lo { get; init; } = default!;
    }

    public sealed class NestedKeyTypeSupport : IDdsTopicType<NestedKey>
    {
        public static readonly NestedKeyTypeSupport Instance = new();

        public string TypeName => "feat::NestedKey";
        public bool IsKeyed => true;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Final;

        public byte[] Encode(NestedKey sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(NestedKey sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, NestedKey sample)
        {
            w.WriteInt32(sample.Hi);
            w.WriteInt32(sample.Lo);
        }

        public NestedKey Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public NestedKey DecodeFrom(ref Xcdr2Reader r)
        {
            int __m0 = default!;
            __m0 = r.ReadInt32();
            int __m1 = default!;
            __m1 = r.ReadInt32();
            return new NestedKey
            {
                Hi = __m0!,
                Lo = __m1!,
            };
        }

        public byte[] KeyHash(NestedKey sample)
        {
            var __kw = new Xcdr2Writer(EndianMode.BigEndian);
            __kw.WriteInt32(sample.Hi);
            __kw.WriteInt32(sample.Lo);
            var __kb = __kw.ToArray();
            if (__kb.Length > 16) { return Md5.Hash(__kb); }
            var __h = new byte[16];
            System.Array.Copy(__kb, 0, __h, 0, __kb.Length);
            return __h;
        }
    }

    [Extensibility(ExtensibilityKind.Final)]
    public partial record class OuterKey : ITopicType<OuterKey>
    {
        [Key]
        public NestedKey K { get; init; } = default!;
        public int Payload { get; init; } = default!;
    }

    public sealed class OuterKeyTypeSupport : IDdsTopicType<OuterKey>
    {
        public static readonly OuterKeyTypeSupport Instance = new();

        public string TypeName => "feat::OuterKey";
        public bool IsKeyed => true;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Final;

        public byte[] Encode(OuterKey sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(OuterKey sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, OuterKey sample)
        {
            NestedKeyTypeSupport.Instance.EncodeInto(w, sample.K);
            w.WriteInt32(sample.Payload);
        }

        public OuterKey Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public OuterKey DecodeFrom(ref Xcdr2Reader r)
        {
            NestedKey __m0 = default!;
            __m0 = NestedKeyTypeSupport.Instance.DecodeFrom(ref r);
            int __m1 = default!;
            __m1 = r.ReadInt32();
            return new OuterKey
            {
                K = __m0!,
                Payload = __m1!,
            };
        }

        public byte[] KeyHash(OuterKey sample)
        {
            var __kw = new Xcdr2Writer(EndianMode.BigEndian);
            // nested key types delegate via TypeSupport (Phase 6+)
            var __kb = __kw.ToArray();
            if (__kb.Length > 16) { return Md5.Hash(__kb); }
            var __h = new byte[16];
            System.Array.Copy(__kb, 0, __h, 0, __kb.Length);
            return __h;
        }
    }

    /// <summary>IDL `@bit_bound(32)`</summary>
    [System.Flags]
    public enum Perm : uint
    {
        READ = (uint)(1u << 0),
        WRITE = (uint)(1u << 1),
        EXEC = (uint)(1u << 2),
    }

    public struct Flags
    {
        public ulong Value;

        public ulong Kind
        {
            readonly get => (Value >> 0) & 0x7UL;
            set => Value = (Value & ~(0x7UL << 0)) | ((value & 0x7UL) << 0);
        }
        public ulong Prio
        {
            readonly get => (Value >> 3) & 0x1FUL;
            set => Value = (Value & ~(0x1FUL << 3)) | ((value & 0x1FUL) << 3);
        }
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Bits : ITopicType<Bits>
    {
        public Perm Perm { get; init; } = default!;
        public Flags Flags { get; init; } = default!;
    }

    public sealed class BitsTypeSupport : IDdsTopicType<Bits>
    {
        public static readonly BitsTypeSupport Instance = new();

        public string TypeName => "feat::Bits";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Bits sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Bits sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Bits sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteUInt32((uint)sample.Perm);
                w.WriteOctet((byte)(sample.Flags).Value);
            }
        }

        public Bits Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Bits DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            Perm __m0 = default!;
            __m0 = (Perm)r.ReadUInt32();
            Flags __m1 = default!;
            __m1 = new Flags { Value = r.ReadOctet() };
            r.EndDHeader(__scope);
            return new Bits
            {
                Perm = __m0!,
                Flags = __m1!,
            };
        }

        public byte[] KeyHash(Bits sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Tree : ITopicType<Tree>
    {
        public int Value { get; init; } = default!;
        public ISequence<Tree> Kids { get; init; } = default!;
    }

    public sealed class TreeTypeSupport : IDdsTopicType<Tree>
    {
        public static readonly TreeTypeSupport Instance = new();

        public string TypeName => "feat::Tree";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Tree sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Tree sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Tree sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteInt32(sample.Value);
                {
                    var __seq0 = (sample.Kids) as System.Collections.Generic.IEnumerable<Tree>;
                    var __mat0 = __seq0 is null ? new System.Collections.Generic.List<Tree>() : new System.Collections.Generic.List<Tree>(__seq0);
                    using (var __seqdh0 = w.BeginAppendable())
                    {
                        w.WriteSequenceLength(__mat0.Count);
                        foreach (var __item0 in __mat0)
                        {
                            TreeTypeSupport.Instance.EncodeInto(w, __item0);
                        }
                    }
                }
            }
        }

        public Tree Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Tree DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int __m0 = default!;
            __m0 = r.ReadInt32();
            Omg.Types.ISequence<Tree> __m1 = default!;
            {
                var __seqdh0 = r.BeginDHeader();
                int __cnt0 = r.ReadSequenceLength();
                var __list0 = new Omg.Types.SequenceList<Tree>();
                for (int __i0 = 0; __i0 < __cnt0; __i0++)
                {
                    Tree __e0;
                    __e0 = TreeTypeSupport.Instance.DecodeFrom(ref r);
                    __list0.Add(__e0);
                }
                r.EndDHeader(__seqdh0);
                __m1 = __list0;
            }
            r.EndDHeader(__scope);
            return new Tree
            {
                Value = __m0!,
                Kids = __m1!,
            };
        }

        public byte[] KeyHash(Tree sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Pt : ITopicType<Pt>
    {
        public int X { get; init; } = default!;
        public int Y { get; init; } = default!;
    }

    public sealed class PtTypeSupport : IDdsTopicType<Pt>
    {
        public static readonly PtTypeSupport Instance = new();

        public string TypeName => "feat::Pt";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Pt sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Pt sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Pt sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteInt32(sample.X);
                w.WriteInt32(sample.Y);
            }
        }

        public Pt Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Pt DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int __m0 = default!;
            __m0 = r.ReadInt32();
            int __m1 = default!;
            __m1 = r.ReadInt32();
            r.EndDHeader(__scope);
            return new Pt
            {
                X = __m0!,
                Y = __m1!,
            };
        }

        public byte[] KeyHash(Pt sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Arr : ITopicType<Arr>
    {
        public int[][] Grid { get; init; } = default!;
        public Pt[] Shape { get; init; } = default!;
    }

    public sealed class ArrTypeSupport : IDdsTopicType<Arr>
    {
        public static readonly ArrTypeSupport Instance = new();

        public string TypeName => "feat::Arr";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Arr sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Arr sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Arr sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                for (int __a0 = 0; __a0 < 2; __a0++)
                {
                    for (int __a1 = 0; __a1 < 3; __a1++)
                    {
                        w.WriteInt32(sample.Grid[__a0][__a1]);
                    }
                }
                using (var __arrdh0 = w.BeginAppendable())
                {
                    for (int __a0 = 0; __a0 < 2; __a0++)
                    {
                        PtTypeSupport.Instance.EncodeInto(w, sample.Shape[__a0]);
                    }
                }
            }
        }

        public Arr Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Arr DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int[][] __m0 = default!;
            __m0 = new int[2][];
            for (int __da0 = 0; __da0 < 2; __da0++)
            {
                __m0[__da0] = new int[3];
                for (int __da1 = 0; __da1 < 3; __da1++)
                {
                    __m0[__da0][__da1] = r.ReadInt32();
                }
            }
            Pt[] __m1 = default!;
            var __arrdh1 = r.BeginDHeader();
            __m1 = new Pt[2];
            for (int __da0 = 0; __da0 < 2; __da0++)
            {
                __m1[__da0] = PtTypeSupport.Instance.DecodeFrom(ref r);
            }
            r.EndDHeader(__arrdh1);
            r.EndDHeader(__scope);
            return new Arr
            {
                Grid = __m0!,
                Shape = __m1!,
            };
        }

        public byte[] KeyHash(Arr sample)
        {
            return new byte[16];
        }
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Prim : ITopicType<Prim>
    {
        public sbyte I8 { get; init; } = default!;
        public byte U8 { get; init; } = default!;
        public short I16 { get; init; } = default!;
        public ushort U16 { get; init; } = default!;
        public int I32 { get; init; } = default!;
        public uint U32 { get; init; } = default!;
        public long I64 { get; init; } = default!;
        public ulong U64 { get; init; } = default!;
        public float F32 { get; init; } = default!;
        public double F64 { get; init; } = default!;
        public bool B { get; init; } = default!;
        public byte O { get; init; } = default!;
        public char Ch { get; init; } = default!;
    }

    public sealed class PrimTypeSupport : IDdsTopicType<Prim>
    {
        public static readonly PrimTypeSupport Instance = new();

        public string TypeName => "feat::Prim";
        public bool IsKeyed => false;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Prim sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Prim sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Prim sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteOctet((byte)(sample.I8));
                w.WriteOctet(sample.U8);
                w.WriteInt16(sample.I16);
                w.WriteUInt16(sample.U16);
                w.WriteInt32(sample.I32);
                w.WriteUInt32(sample.U32);
                w.WriteInt64(sample.I64);
                w.WriteUInt64(sample.U64);
                w.WriteFloat32(sample.F32);
                w.WriteFloat64(sample.F64);
                w.WriteBool(sample.B);
                w.WriteOctet(sample.O);
                w.WriteOctet((byte)(sample.Ch));
            }
        }

        public Prim Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(ref r);
        }

        public Prim DecodeFrom(ref Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            sbyte __m0 = default!;
            __m0 = (sbyte)r.ReadOctet();
            byte __m1 = default!;
            __m1 = r.ReadOctet();
            short __m2 = default!;
            __m2 = r.ReadInt16();
            ushort __m3 = default!;
            __m3 = r.ReadUInt16();
            int __m4 = default!;
            __m4 = r.ReadInt32();
            uint __m5 = default!;
            __m5 = r.ReadUInt32();
            long __m6 = default!;
            __m6 = r.ReadInt64();
            ulong __m7 = default!;
            __m7 = r.ReadUInt64();
            float __m8 = default!;
            __m8 = r.ReadFloat32();
            double __m9 = default!;
            __m9 = r.ReadFloat64();
            bool __m10 = default!;
            __m10 = r.ReadBool();
            byte __m11 = default!;
            __m11 = r.ReadOctet();
            char __m12 = default!;
            __m12 = (char)r.ReadOctet();
            r.EndDHeader(__scope);
            return new Prim
            {
                I8 = __m0!,
                U8 = __m1!,
                I16 = __m2!,
                U16 = __m3!,
                I32 = __m4!,
                U32 = __m5!,
                I64 = __m6!,
                U64 = __m7!,
                F32 = __m8!,
                F64 = __m9!,
                B = __m10!,
                O = __m11!,
                Ch = __m12!,
            };
        }

        public byte[] KeyHash(Prim sample)
        {
            return new byte[16];
        }
    }

} // namespace feat
