//! Behavioral DDS QoS-policy + keyed-lifecycle conformance harness for the
//! ZeroDDS Rust binding over REAL DCPS (two participants in one process,
//! same domain, UDP-loopback runtime).
//!
//! Each `check_*` constructs a fresh DomainParticipant pair, a writer and a
//! reader with the QoS under test, drives the discovery handshake
//! event-driven, then OBSERVES the runtime effect (not just that a setter
//! did not throw). Status is printed per check: VERIFIED / PARTIAL /
//! UNSUPPORTED, with the observed evidence.
//!
//! Topic type: `qos::Reading { @key long id; long seq; double value; }`
//! generated by `zerodds-idlc --rust` into `generated/reading.rs`.

use std::time::Duration as StdDuration;

use zerodds_dcps::runtime::RuntimeConfig;
use zerodds_dcps::{
    DataReaderQos, DataWriterQos, DomainParticipantFactory, DomainParticipantQos, PublisherQos,
    SubscriberQos, TopicQos,
};
use zerodds_qos::{
    Duration as QosDuration, DurabilityKind, HistoryKind, LivelinessKind, OwnershipKind,
    ReliabilityKind,
};

#[path = "../generated/reading.rs"]
mod generated;

use generated::qos::Reading;


fn cfg() -> RuntimeConfig {
    RuntimeConfig {
        tick_period: StdDuration::from_millis(10),
        spdp_period: StdDuration::from_millis(50),
        ..RuntimeConfig::default()
    }
}

/// A fresh participant on a unique domain so checks do not cross-talk.
fn participant(domain: i32) -> zerodds_dcps::DomainParticipant {
    DomainParticipantFactory::instance()
        .create_participant_with_config(domain, DomainParticipantQos::default(), cfg())
        .expect("participant")
}

fn r(id: i32, seq: i32, value: f64) -> Reading {
    Reading { id, seq, value }
}

/// Result of one check.
struct Outcome {
    name: &'static str,
    status: &'static str, // VERIFIED | PARTIAL | UNSUPPORTED
    note: String,
}

macro_rules! out {
    ($name:expr, $status:expr, $($arg:tt)*) => {
        Outcome { name: $name, status: $status, note: format!($($arg)*) }
    };
}

// 1. RELIABILITY -----------------------------------------------------------
fn check_reliability() -> Outcome {
    let dom = 10;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("Rel", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("Rel", TopicQos::default()).unwrap();

    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.history.kind = HistoryKind::KeepAll;
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.history.kind = HistoryKind::KeepAll;

    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();

    if w.wait_for_matched_subscription(1, StdDuration::from_secs(5)).is_err() {
        return out!("reliability", "UNSUPPORTED", "RELIABLE writer never matched reader");
    }
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();

    const N: i32 = 50;
    for i in 0..N {
        w.write(&r(1, i, i as f64)).unwrap();
    }
    // Collect with retries (event-driven wait_for_data between takes).
    let mut got: Vec<Reading> = Vec::new();
    let deadline = std::time::Instant::now() + StdDuration::from_secs(5);
    while (got.len() as i32) < N && std::time::Instant::now() < deadline {
        if rd.wait_for_data(StdDuration::from_millis(200)).is_ok() {
            got.extend(rd.take().unwrap());
        }
    }
    let in_order = got.windows(2).all(|w| w[0].seq <= w[1].seq);
    let all = got.len() as i32 == N;

    // BEST_EFFORT acceptance: just confirm a BE writer/reader pair matches + delivers.
    let dom2 = 11;
    let pp2 = participant(dom2);
    let sp2 = participant(dom2);
    let pt2 = pp2.create_topic::<Reading>("RelBE", TopicQos::default()).unwrap();
    let st2 = sp2.create_topic::<Reading>("RelBE", TopicQos::default()).unwrap();
    let mut beq = DataWriterQos::default();
    beq.reliability.kind = ReliabilityKind::BestEffort;
    let w2 = pp2.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt2, beq).unwrap();
    let rd2 = sp2.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st2, DataReaderQos::default()).unwrap();
    let be_matched = w2.wait_for_matched_subscription(1, StdDuration::from_secs(5)).is_ok();
    w2.write(&r(2, 0, 0.0)).unwrap();
    let be_delivered = rd2.wait_for_data(StdDuration::from_secs(2)).is_ok();

    if all && in_order && be_matched {
        out!("reliability", "VERIFIED",
            "RELIABLE delivered all {N}/{N} in order; BEST_EFFORT matched={be_matched} delivered={be_delivered}")
    } else if be_matched {
        out!("reliability", "PARTIAL",
            "RELIABLE delivered {}/{N} (in_order={in_order}); BEST_EFFORT matched+delivered={be_delivered}", got.len())
    } else {
        out!("reliability", "PARTIAL", "RELIABLE {}/{N}; BEST_EFFORT match failed", got.len())
    }
}

// 2. DURABILITY ------------------------------------------------------------
fn check_durability() -> Outcome {
    // TRANSIENT_LOCAL: reader joins AFTER writer published -> should get retained last sample.
    let dom = 20;
    let pp = participant(dom);
    let pt = pp.create_topic::<Reading>("Dur", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.durability.kind = DurabilityKind::TransientLocal;
    wq.history.kind = HistoryKind::KeepLast;
    wq.history.depth = 3;
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();

    // Publish BEFORE any reader exists.
    for i in 0..3 {
        w.write(&r(1, i, i as f64)).unwrap();
    }
    std::thread::sleep(StdDuration::from_millis(200));

    // Late-joining TL reader.
    let sp = participant(dom);
    let st = sp.create_topic::<Reading>("Dur", TopicQos::default()).unwrap();
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.durability.kind = DurabilityKind::TransientLocal;
    rq.history.kind = HistoryKind::KeepLast;
    rq.history.depth = 3;
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();

    let mut tl_got = Vec::new();
    let deadline = std::time::Instant::now() + StdDuration::from_secs(3);
    while std::time::Instant::now() < deadline {
        if rd.wait_for_data(StdDuration::from_millis(200)).is_ok() {
            tl_got.extend(rd.take().unwrap());
        }
        if !tl_got.is_empty() { break; }
    }

    // VOLATILE late joiner: should get nothing.
    let dom2 = 21;
    let pp2 = participant(dom2);
    let pt2 = pp2.create_topic::<Reading>("DurV", TopicQos::default()).unwrap();
    let mut wq2 = DataWriterQos::default();
    wq2.reliability.kind = ReliabilityKind::Reliable;
    wq2.durability.kind = DurabilityKind::Volatile;
    let w2 = pp2.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt2, wq2).unwrap();
    for i in 0..3 { w2.write(&r(1, i, i as f64)).unwrap(); }
    std::thread::sleep(StdDuration::from_millis(200));
    let sp2 = participant(dom2);
    let st2 = sp2.create_topic::<Reading>("DurV", TopicQos::default()).unwrap();
    let mut rq2 = DataReaderQos::default();
    rq2.reliability.kind = ReliabilityKind::Reliable;
    rq2.durability.kind = DurabilityKind::Volatile;
    let rd2 = sp2.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st2, rq2).unwrap();
    rd2.wait_for_matched_publication(1, StdDuration::from_secs(3)).ok();
    let vol_got = rd2.wait_for_data(StdDuration::from_secs(1)).is_ok();

    if !tl_got.is_empty() && !vol_got {
        out!("durability", "VERIFIED",
            "TRANSIENT_LOCAL late joiner received {} retained sample(s) (seqs {:?}); VOLATILE late joiner got nothing",
            tl_got.len(), tl_got.iter().map(|x| x.seq).collect::<Vec<_>>())
    } else if !tl_got.is_empty() {
        out!("durability", "PARTIAL",
            "TRANSIENT_LOCAL delivered {} retained; but VOLATILE late joiner ALSO got data (got_data={vol_got})", tl_got.len())
    } else {
        out!("durability", "UNSUPPORTED",
            "TRANSIENT_LOCAL late joiner received NOTHING (no historical replay); VOLATILE late-joiner got_data={vol_got}")
    }
}

// 3. HISTORY ---------------------------------------------------------------
fn check_history() -> Outcome {
    // KEEP_LAST(2) on a TRANSIENT_LOCAL writer: a late joiner sees at most 2 per instance.
    let dom = 30;
    let pp = participant(dom);
    let pt = pp.create_topic::<Reading>("Hist", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.durability.kind = DurabilityKind::TransientLocal;
    wq.history.kind = HistoryKind::KeepLast;
    wq.history.depth = 2;
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    // 5 samples on ONE instance; KEEP_LAST(2) should retain only last 2.
    for i in 0..5 { w.write(&r(7, i, i as f64)).unwrap(); }
    std::thread::sleep(StdDuration::from_millis(200));

    let sp = participant(dom);
    let st = sp.create_topic::<Reading>("Hist", TopicQos::default()).unwrap();
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.durability.kind = DurabilityKind::TransientLocal;
    rq.history.kind = HistoryKind::KeepLast;
    rq.history.depth = 2;
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();
    let mut got = Vec::new();
    let deadline = std::time::Instant::now() + StdDuration::from_secs(3);
    while std::time::Instant::now() < deadline {
        if rd.wait_for_data(StdDuration::from_millis(200)).is_ok() {
            got.extend(rd.take().unwrap());
        }
        std::thread::sleep(StdDuration::from_millis(50));
        if got.len() >= 2 { // give a chance for more before settling
            if rd.wait_for_data(StdDuration::from_millis(200)).is_err() { break; }
            got.extend(rd.take().unwrap());
        }
    }
    let seqs: Vec<i32> = got.iter().map(|x| x.seq).collect();

    if got.is_empty() {
        return out!("history", "PARTIAL",
            "KEEP_LAST(2) over TRANSIENT_LOCAL replay produced nothing (durability replay not observable here)");
    }
    if got.len() <= 2 && seqs.iter().all(|&s| s >= 3) {
        out!("history", "VERIFIED",
            "KEEP_LAST(2) capped late-joiner replay to {} sample(s) holding the newest seqs {:?} (older 0..2 dropped)", got.len(), seqs)
    } else if got.len() <= 2 {
        out!("history", "PARTIAL",
            "KEEP_LAST(2) capped count to {} but seqs={:?} (expected newest [3,4])", got.len(), seqs)
    } else {
        out!("history", "UNSUPPORTED",
            "KEEP_LAST(2) did NOT cap: late joiner saw {} samples seqs={:?}", got.len(), seqs)
    }
}

// 4. DEADLINE --------------------------------------------------------------
fn check_deadline() -> Outcome {
    let dom = 40;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("DL", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("DL", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.deadline.period = QosDuration::from_millis(100);
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.deadline.period = QosDuration::from_millis(100);
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();
    w.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();

    // Write one sample, then go silent for >> deadline period.
    w.write(&r(1, 0, 0.0)).unwrap();
    rd.wait_for_data(StdDuration::from_secs(1)).ok();
    let _ = rd.take();
    let before = rd.requested_deadline_missed_count();
    // Stay silent for several deadline periods; poll status to drive listeners.
    let deadline = std::time::Instant::now() + StdDuration::from_secs(2);
    let mut after = before;
    while std::time::Instant::now() < deadline {
        std::thread::sleep(StdDuration::from_millis(100));
        rd.drive_listeners();
        after = rd.requested_deadline_missed_count();
        if after > before { break; }
    }

    if after > before {
        out!("deadline", "VERIFIED",
            "requested-deadline-missed incremented {before}->{after} after writer fell silent past the 100ms offered deadline")
    } else {
        out!("deadline", "UNSUPPORTED",
            "requested-deadline-missed stayed at {before} after >2s silence past a 100ms deadline (no missed-deadline detection)")
    }
}

// 5. LIVELINESS ------------------------------------------------------------
fn check_liveliness() -> Outcome {
    let dom = 50;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("Liv", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("Liv", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.liveliness.kind = LivelinessKind::Automatic;
    wq.liveliness.lease_duration = QosDuration::from_millis(300);
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.liveliness.kind = LivelinessKind::Automatic;
    rq.liveliness.lease_duration = QosDuration::from_millis(300);
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();
    w.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();
    w.write(&r(1, 0, 0.0)).unwrap();
    rd.wait_for_data(StdDuration::from_secs(1)).ok();
    let _ = rd.take();
    rd.drive_listeners();
    let (alive_before, _ac0, na0) = rd.liveliness_changed_status();

    // Drop the writer (and its participant) -> liveliness should go not_alive.
    drop(w);
    drop(pp);

    let deadline = std::time::Instant::now() + StdDuration::from_secs(3);
    let mut na = na0;
    let mut alive_after = alive_before;
    while std::time::Instant::now() < deadline {
        std::thread::sleep(StdDuration::from_millis(100));
        rd.drive_listeners();
        let (a, _ac, n) = rd.liveliness_changed_status();
        na = n; alive_after = a;
        if n > na0 { break; }
    }

    if na > na0 {
        out!("liveliness", "VERIFIED",
            "AUTOMATIC liveliness: not_alive_count {na0}->{na} (alive {alive_before}->{alive_after}) after the writer stopped asserting")
    } else if !alive_before {
        out!("liveliness", "PARTIAL",
            "liveliness API present but reader never registered the writer as alive (alive_before=false); not_alive stayed {na0}")
    } else {
        out!("liveliness", "UNSUPPORTED",
            "writer dropped but not_alive_count stayed {na0} (alive={alive_after}); no alive->not_alive transition detected")
    }
}

// 6. OWNERSHIP -------------------------------------------------------------
fn check_ownership() -> Outcome {
    let dom = 60;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("Own", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("Own", TopicQos::default()).unwrap();

    let mk_writer = |strength: i32| {
        let mut wq = DataWriterQos::default();
        wq.reliability.kind = ReliabilityKind::Reliable;
        wq.ownership.kind = OwnershipKind::Exclusive;
        wq.ownership_strength.value = strength;
        pp.create_publisher(PublisherQos::default())
            .create_datawriter::<Reading>(&pt, wq).unwrap()
    };
    let w_lo = mk_writer(1);
    let w_hi = mk_writer(10);

    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.ownership.kind = OwnershipKind::Exclusive;
    rq.history.kind = HistoryKind::KeepAll;
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();

    w_lo.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    w_hi.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    rd.wait_for_matched_publication(2, StdDuration::from_secs(5)).ok();

    // Both writers publish on the SAME instance (id=1). Strong writer uses value 100.x,
    // weak writer uses value 1.x — so we can tell whose samples reached the reader.
    for i in 0..5 {
        w_hi.write(&r(1, i, 100.0 + i as f64)).unwrap();
        w_lo.write(&r(1, i, 1.0 + i as f64)).unwrap();
        std::thread::sleep(StdDuration::from_millis(20));
    }
    let mut got = Vec::new();
    let deadline = std::time::Instant::now() + StdDuration::from_secs(2);
    while std::time::Instant::now() < deadline {
        if rd.wait_for_data(StdDuration::from_millis(200)).is_ok() {
            got.extend(rd.take().unwrap());
        }
    }
    let from_hi = got.iter().filter(|x| x.value >= 100.0).count();
    let from_lo = got.iter().filter(|x| x.value < 100.0).count();

    if from_hi > 0 && from_lo == 0 {
        out!("ownership", "VERIFIED",
            "EXCLUSIVE: reader received {from_hi} samples ALL from the strength-10 writer; 0 from strength-1 writer")
    } else if from_hi > 0 && from_lo > 0 {
        out!("ownership", "UNSUPPORTED",
            "EXCLUSIVE not enforced: reader saw {from_hi} from strong + {from_lo} from weak writer (both delivered)")
    } else {
        out!("ownership", "PARTIAL",
            "EXCLUSIVE inconclusive: hi={from_hi} lo={from_lo} total={}", got.len())
    }
}

// 7. PARTITION -------------------------------------------------------------
/// Runs a matching + a mismatched partition pair where the partition is set
/// at `loc` ("pub_sub" = on Publisher/Subscriber QoS, the DDS-spec location;
/// "writer_reader" = on DataWriter/DataReader QoS, where the runtime reads it).
/// Returns (matched_delivered, mismatched_delivered).
fn partition_pair(base_domain: i32, loc: &str) -> (bool, bool) {
    let mk = |dom: i32, pname: &str, qname: &str, topic: &str| -> bool {
        let pp = participant(dom);
        let sp = participant(dom);
        let pt = pp.create_topic::<Reading>(topic, TopicQos::default()).unwrap();
        let st = sp.create_topic::<Reading>(topic, TopicQos::default()).unwrap();
        let mut pub_qos = PublisherQos::default();
        let mut sub_qos = SubscriberQos::default();
        let mut wq = DataWriterQos::default();
        wq.reliability.kind = ReliabilityKind::Reliable;
        let mut rq = DataReaderQos::default();
        rq.reliability.kind = ReliabilityKind::Reliable;
        if loc == "pub_sub" {
            pub_qos.partition.names = vec![pname.to_string()];
            sub_qos.partition.names = vec![qname.to_string()];
        } else {
            wq.partition.names = vec![pname.to_string()];
            rq.partition.names = vec![qname.to_string()];
        }
        let w = pp.create_publisher(pub_qos).create_datawriter::<Reading>(&pt, wq).unwrap();
        let rd = sp.create_subscriber(sub_qos).create_datareader::<Reading>(&st, rq).unwrap();
        let _ = w.wait_for_matched_subscription(1, StdDuration::from_secs(2));
        w.write(&r(1, 0, 0.0)).unwrap();
        let delivered = rd.wait_for_data(StdDuration::from_secs(1)).is_ok();
        // keep entities alive until measured
        drop(rd); drop(w); drop(pp); drop(sp);
        delivered
    };
    let matched = mk(base_domain, "A", "A", "PartM");
    let mismatched = mk(base_domain + 1, "X", "Y", "PartX");
    (matched, mismatched)
}

fn check_partition() -> Outcome {
    // DDS spec puts PARTITION on the Publisher/Subscriber.
    let (ps_match, ps_mism) = partition_pair(70, "pub_sub");
    // The runtime, however, reads partition from the DataWriter/DataReader QoS.
    let (wr_match, wr_mism) = partition_pair(72, "writer_reader");

    if wr_match && !wr_mism && ps_match && ps_mism {
        out!("partition", "UNSUPPORTED",
            "PARTITION honored ONLY on DataWriter/DataReader QoS (match={wr_match} mismatch_blocked={}), but IGNORED on the spec-correct Publisher/Subscriber QoS (mismatched 'X'/'Y' STILL delivered: ps_match={ps_match} ps_mism={ps_mism})", !wr_mism)
    } else if wr_match && !wr_mism && !ps_mism {
        out!("partition", "VERIFIED",
            "PARTITION enforced on both placements: matched delivered, mismatched blocked (ps_match={ps_match} wr_match={wr_match})")
    } else if ps_match && !ps_mism {
        out!("partition", "VERIFIED",
            "PARTITION enforced on Publisher/Subscriber QoS: matched delivered, mismatched blocked")
    } else {
        out!("partition", "PARTIAL",
            "pub/sub: match={ps_match} mismatch={ps_mism}; writer/reader: match={wr_match} mismatch={wr_mism}")
    }
}

// 8. CONTENT-FILTERED-TOPIC ------------------------------------------------
fn check_cft() -> Outcome {
    let dom = 80;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("Cft", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("Cft", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.history.kind = HistoryKind::KeepAll;
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.history.kind = HistoryKind::KeepAll;
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    // Filter: only value > 10.0 survives.
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap()
        .with_filter(|s: &Reading| s.value > 10.0);
    w.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();

    // 10 samples: values 0..10 -> only those > 10 (none of 0..10) ... use 0..20.
    for i in 0..20 { w.write(&r(1, i, i as f64)).unwrap(); }
    let mut got = Vec::new();
    let deadline = std::time::Instant::now() + StdDuration::from_secs(2);
    while std::time::Instant::now() < deadline {
        if rd.wait_for_data(StdDuration::from_millis(200)).is_ok() {
            got.extend(rd.take().unwrap());
        }
    }
    let all_match = got.iter().all(|x| x.value > 10.0);
    let any_below = got.iter().any(|x| x.value <= 10.0);

    if !got.is_empty() && all_match && !any_below {
        out!("content_filtered_topic", "VERIFIED",
            "with_filter(value>10.0): reader received {} samples, ALL with value>10 (values 0..=10 filtered out)", got.len())
    } else if got.is_empty() {
        out!("content_filtered_topic", "PARTIAL",
            "filter dropped EVERYTHING incl. matching samples (received 0)")
    } else {
        out!("content_filtered_topic", "UNSUPPORTED",
            "filter not applied: {} samples, any value<=10 present={any_below}", got.len())
    }
}

// 9. KEYED LIFECYCLE -------------------------------------------------------
fn check_keyed_lifecycle() -> Outcome {
    use zerodds_dcps::sample_info::InstanceStateKind;
    let dom = 90;
    let pp = participant(dom);
    let sp = participant(dom);
    let pt = pp.create_topic::<Reading>("Life", TopicQos::default()).unwrap();
    let st = sp.create_topic::<Reading>("Life", TopicQos::default()).unwrap();
    let mut wq = DataWriterQos::default();
    wq.reliability.kind = ReliabilityKind::Reliable;
    wq.history.kind = HistoryKind::KeepAll;
    let mut rq = DataReaderQos::default();
    rq.reliability.kind = ReliabilityKind::Reliable;
    rq.history.kind = HistoryKind::KeepAll;
    let w = pp.create_publisher(PublisherQos::default())
        .create_datawriter::<Reading>(&pt, wq).unwrap();
    let rd = sp.create_subscriber(SubscriberQos::default())
        .create_datareader::<Reading>(&st, rq).unwrap();
    w.wait_for_matched_subscription(1, StdDuration::from_secs(5)).ok();
    rd.wait_for_matched_publication(1, StdDuration::from_secs(5)).ok();

    // NOTE: lifecycle markers (dispose/unregister) are pushed to the reader's
    // `cache` (valid_data=false), NOT to the data channel that `wait_for_data`
    // waits on. So we poll `take_with_info()` directly with short sleeps —
    // relying on `wait_for_data` would miss cache-only lifecycle samples.
    let drain_states = |label: &str| -> Vec<(i32, InstanceStateKind)> {
        let mut acc = Vec::new();
        for _ in 0..25 {
            std::thread::sleep(StdDuration::from_millis(40));
            rd.drive_listeners();
            if let Ok(samples) = rd.take_with_info() {
                for s in samples {
                    // `data` carries the key portion even for invalid (lifecycle) samples.
                    acc.push((s.data.id, s.info().instance_state));
                }
            }
        }
        eprintln!("  [{label}] states: {:?}", acc);
        acc
    };

    // Two instances by key.
    let k1 = w.register_instance(&r(1, 0, 0.0)).ok();
    let k2 = w.register_instance(&r(2, 0, 0.0)).ok();
    let _ = (k1, k2);
    w.write(&r(1, 1, 1.0)).unwrap();
    w.write(&r(2, 1, 2.0)).unwrap();
    let s_alive = drain_states("alive");
    let saw_alive = s_alive.iter().any(|(_, st)| *st == InstanceStateKind::Alive);

    // dispose key 1 -> NOT_ALIVE_DISPOSED
    let h1 = w.lookup_instance(&r(1, 0, 0.0));
    let disp_ok = w.dispose(&r(1, 0, 0.0), h1).is_ok();
    let s_disp = drain_states("dispose");
    let saw_disposed = s_disp.iter().any(|(_, st)| *st == InstanceStateKind::NotAliveDisposed);

    // new sample on key 1 -> back to ALIVE
    w.write(&r(1, 9, 9.0)).unwrap();
    let s_revive = drain_states("revive");
    let saw_revive = s_revive.iter().any(|(_, st)| *st == InstanceStateKind::Alive);

    // unregister key 2 -> NOT_ALIVE_NO_WRITERS
    let h2 = w.lookup_instance(&r(2, 0, 0.0));
    let unreg_ok = w.unregister_instance(&r(2, 0, 0.0), h2).is_ok();
    let s_unreg = drain_states("unregister");
    let saw_no_writers = s_unreg.iter().any(|(_, st)| *st == InstanceStateKind::NotAliveNoWriters);

    let parts = format!(
        "alive={saw_alive} dispose(ok={disp_ok})={saw_disposed} revive={saw_revive} unregister(ok={unreg_ok})_no_writers={saw_no_writers}");
    if saw_alive && saw_disposed && saw_no_writers {
        out!("keyed_lifecycle", "VERIFIED",
            "instance_state transitions observed: ALIVE -> NOT_ALIVE_DISPOSED -> (ALIVE on new sample={saw_revive}) and NOT_ALIVE_NO_WRITERS on unregister. {parts}")
    } else if saw_alive && (saw_disposed || saw_no_writers) {
        out!("keyed_lifecycle", "PARTIAL",
            "some lifecycle states observed but not all. {parts}")
    } else {
        out!("keyed_lifecycle", "UNSUPPORTED",
            "lifecycle instance_state transitions not observable. {parts}")
    }
}

fn main() {
    let checks: Vec<fn() -> Outcome> = vec![
        check_reliability,
        check_durability,
        check_history,
        check_deadline,
        check_liveliness,
        check_ownership,
        check_partition,
        check_cft,
        check_keyed_lifecycle,
    ];
    let mut results = Vec::new();
    for c in checks {
        let o = c();
        println!("[{:>11}] {} :: {}", o.status, o.name, o.note);
        results.push(o);
    }
    println!("\n==== SUMMARY ====");
    for o in &results {
        println!("{:>11}  {}", o.status, o.name);
    }
}
