# SPDX-License-Identifier: Apache-2.0
# Auto-generated by `zerodds-idl-python`. Do not edit by hand.

from dataclasses import dataclass
from enum import IntEnum
from typing import Dict, List, TypeAlias
from zerodds.idl import idl_struct, Float64, Int32, String

class Mode(IntEnum):
    MODE_IDLE = 0
    MODE_ACTIVE = 1
    MODE_FAULT = 2

CurrentInAmpsType: TypeAlias = Float64

@idl_struct(typename="Sample")
@dataclass
class Sample:
    seq: Int32
    value: Float64

@idl_struct(typename="Telemetry")
@dataclass
class Telemetry:
    unitId: Int32
    region: String
    mode: Mode
    batteryCurrent: CurrentInAmpsType
    history: List[Sample]
    counters: Dict[String, Int32]
    window: List[Int32]

