#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""IDL-conformance DCPS roundtrip for the ZeroDDS Python PSM.

Publishes one fully-populated sample of typed IDL data per topic over a REAL
DomainParticipant + publisher/subscriber loopback, then reads it back and
asserts the recovered sample equals what was published.

Topics
------
1. Telemetry  (combo subset) — enum + nested struct + sequence-of-struct +
   bounded string + map + array + typedef + @key.  Generated from
   `combo_telemetry.idl` by `zerodds-idlc --python`.
2. Reading    — a standalone union topic (enum discriminator + default case).
   Generated from `reading_union.idl`.  Carried over a raw BytesTopic because
   `IdlTopic` requires an @idl_struct dataclass and a union is not one.
3. Optionals  — @optional members.  Uses a hand-written type because the
   Python backend currently drops the @optional annotation (see README).

See README.md "Known limitations" for the features that could NOT be exercised
end-to-end because of real codegen/runtime bugs (union-as-struct-member,
@optional codegen drop, fixed-array -> sequence brand).
"""

import sys

import zerodds

# Generated by zerodds-idlc --python (top-level, no IDL module):
from combo_telemetry import Mode, Sample, Telemetry
from reading_union import Mode as RMode, Reading
from optionals_handwritten import Optionals


def _section(title):
    print("=" * 64)
    print(title)
    print("=" * 64)


def roundtrip_telemetry(participant):
    _section("Topic 1: Telemetry (combo subset)")
    topic = zerodds.IdlTopic(participant, "ConformanceTelemetry", Telemetry)
    writer = topic.create_writer(participant.create_publisher())
    reader = topic.create_reader(participant.create_subscriber())

    writer.wait_for_matched_subscription(1, 5.0)
    reader.wait_for_matched_publication(1, 5.0)

    sent = Telemetry(
        unitId=42,
        region="eu-central-mission-1",
        mode=Mode.MODE_ACTIVE,
        batteryCurrent=3.14159,
        history=[Sample(seq=1, value=1.5), Sample(seq=2, value=2.5),
                 Sample(seq=3, value=-9.0)],
        counters={"frames": 1000, "drops": 0, "retries": 7},
        window=[10, 20, 30, 40],
    )
    print("PUB:", sent)
    writer.write(sent)

    reader.wait_for_data(3.0)
    got = reader.take()
    assert got, "no Telemetry sample received"
    recovered = got[0]
    print("SUB:", recovered)
    assert recovered == sent, f"Telemetry mismatch:\n  sent={sent}\n  got ={recovered}"
    # Spot-check the cross-feature interactions explicitly.
    assert recovered.mode is Mode.MODE_ACTIVE
    assert recovered.history[2].value == -9.0
    assert recovered.counters["retries"] == 7
    assert recovered.window == [10, 20, 30, 40]
    print("OK: enum + nested struct + seq<struct> + bounded string + map + "
          "array + typedef survived the wire.\n")


def roundtrip_reading(participant):
    _section("Topic 2: Reading (standalone union)")
    topic = participant.create_bytes_topic("ConformanceReading")
    writer = participant.create_publisher().create_bytes_writer(topic)
    reader = participant.create_subscriber().create_bytes_reader(topic)

    writer.wait_for_matched_subscription(1, 5.0)
    reader.wait_for_matched_publication(1, 5.0)

    sent = Reading.make(RMode.MODE_ACTIVE, 9.81)
    print("PUB: Reading(discriminator=%r, value=%r)"
          % (sent.discriminator, sent.value))
    writer.write(Reading.encode(sent))

    reader.wait_for_data(3.0)
    raw = reader.take()
    assert raw, "no Reading sample received"
    recovered = Reading.decode(raw[0])
    print("SUB: Reading(discriminator=%r, value=%r)"
          % (recovered.discriminator, recovered.value))
    assert recovered == sent, f"Reading mismatch: {recovered} != {sent}"

    # Exercise the default case too.
    sent2 = Reading.make(RMode.MODE_FAULT, "E_OVERHEAT")
    writer.write(Reading.encode(sent2))
    reader.wait_for_data(3.0)
    recovered2 = Reading.decode(reader.take()[0])
    assert recovered2 == sent2, f"Reading default mismatch: {recovered2} != {sent2}"
    print("SUB(default): %r" % (recovered2.value,))
    print("OK: union (enum discriminator + active case + default case) "
          "survived the wire.\n")


def roundtrip_optionals(participant):
    _section("Topic 3: Optionals (@optional members)")
    topic = zerodds.IdlTopic(participant, "ConformanceOptionals", Optionals)
    writer = topic.create_writer(participant.create_publisher())
    reader = topic.create_reader(participant.create_subscriber())

    writer.wait_for_matched_subscription(1, 5.0)
    reader.wait_for_matched_publication(1, 5.0)

    # Present case.
    sent = Optionals(required=7, maybe=99, note="calibrated")
    print("PUB:", sent)
    writer.write(sent)
    reader.wait_for_data(3.0)
    recovered = reader.take()[0]
    print("SUB:", recovered)
    assert recovered == sent, f"Optionals(present) mismatch: {recovered} != {sent}"

    # Absent case (None present-flags).
    sent2 = Optionals(required=1, maybe=None, note=None)
    print("PUB:", sent2)
    writer.write(sent2)
    reader.wait_for_data(3.0)
    recovered2 = reader.take()[0]
    print("SUB:", recovered2)
    assert recovered2 == sent2, f"Optionals(absent) mismatch: {recovered2} != {sent2}"
    print("OK: @optional present + absent present-flags survived the wire.\n")


def main():
    factory = zerodds.DomainParticipantFactory.instance()
    participant = factory.create_participant(0)

    roundtrip_telemetry(participant)
    roundtrip_reading(participant)
    roundtrip_optionals(participant)

    _section("ALL ROUNDTRIPS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
