/* Generated by zerodds idl-cpp c_mode. Do not edit. */
#ifndef ZERODDS_GENERATED_H
#define ZERODDS_GENERATED_H
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "zerodds_xcdr2.h"
#ifdef __cplusplus
extern "C" {
#endif

#ifndef ZERODDS_X2_ALIGN4_8BYTE
#define ZERODDS_X2_ALIGN4_8BYTE
static inline int zd_x2_write_u64(uint8_t** buf, size_t* len, size_t* cap, uint64_t v) {
    if (zerodds_xcdr2_c_pad_to(buf, len, cap, 4) != 0) return -1;
    if (zerodds_xcdr2_c_grow(buf, cap, *len + 8) != 0) return -1;
    for (int i = 0; i < 8; ++i) { (*buf)[(*len)++] = (uint8_t)((v >> (8 * i)) & 0xFFu); }
    return 0;
}
static inline int zd_x2_write_i64(uint8_t** buf, size_t* len, size_t* cap, int64_t v) { return zd_x2_write_u64(buf, len, cap, (uint64_t)v); }
static inline int zd_x2_write_f64(uint8_t** buf, size_t* len, size_t* cap, double v) { uint64_t u; memcpy(&u, &v, sizeof(u)); return zd_x2_write_u64(buf, len, cap, u); }
static inline int zd_x2_read_u64(const uint8_t* buf, size_t len, size_t* pos, uint64_t* out, int big_endian) {
    if (zerodds_xcdr2_c_pad_read(buf, len, pos, 4) != 0) return -1;
    if (*pos + 8 > len) return -1;
    uint64_t v = 0;
    for (int i = 0; i < 8; ++i) { int sh = big_endian ? (8 * (7 - i)) : (8 * i); v |= (uint64_t)buf[*pos + (size_t)i] << sh; }
    *pos += 8; *out = v; return 0;
}
static inline int zd_x2_read_i64(const uint8_t* buf, size_t len, size_t* pos, int64_t* out, int big_endian) { uint64_t u; int rc = zd_x2_read_u64(buf, len, pos, &u, big_endian); if (rc != 0) return rc; *out = (int64_t)u; return 0; }
static inline int zd_x2_read_f64(const uint8_t* buf, size_t len, size_t* pos, double* out, int big_endian) { uint64_t u; int rc = zd_x2_read_u64(buf, len, pos, &u, big_endian); if (rc != 0) return rc; memcpy(out, &u, sizeof(*out)); return 0; }
#endif

typedef int32_t feat_Hue_t;
enum { feat_Hue_H_RED = 0 };
enum { feat_Hue_H_GREEN = 1 };
enum { feat_Hue_H_BLUE = 2 };

typedef uint32_t feat_Perm_t;
enum { feat_Perm_READ = (1u << 0) };
enum { feat_Perm_WRITE = (1u << 1) };
enum { feat_Perm_EXEC = (1u << 2) };

typedef uint8_t feat_Flags_t;
enum { feat_Flags_kind_SHIFT = 0 };
#define feat_Flags_kind_MASK 0x7u
enum { feat_Flags_prio_SHIFT = 3 };
#define feat_Flags_prio_MASK 0x1Fu

typedef struct feat_WStr_s {
    uint16_t* label;
    uint16_t* text;
} feat_WStr_t;

typedef struct feat_Mut_s {
    int32_t a;
    double b;
    char* c;
} feat_Mut_t;

typedef struct feat_MutLeaf_s {
    int32_t u;
    double v;
} feat_MutLeaf_t;

typedef struct feat_MutNest_s {
    int32_t tag;
    feat_MutLeaf_t leaf;
    struct { uint32_t len; feat_MutLeaf_t* elems; } list;
} feat_MutNest_t;

typedef struct feat_NestedKey_s {
    int32_t hi;
    int32_t lo;
} feat_NestedKey_t;

typedef struct feat_OuterKey_s {
    feat_NestedKey_t k;
    int32_t payload;
} feat_OuterKey_t;

typedef struct feat_Bits_s {
    feat_Perm_t perm;
    feat_Flags_t flags;
} feat_Bits_t;

typedef struct feat_Tree_s {
    int32_t value;
    struct { uint32_t len; struct feat_Tree_s* elems; } kids;
} feat_Tree_t;

typedef struct feat_Pt_s {
    int32_t x;
    int32_t y;
} feat_Pt_t;

typedef struct feat_Arr_s {
    int32_t grid[2][3];
    feat_Pt_t shape[2];
} feat_Arr_t;

typedef struct feat_Sel_s {
    int32_t _d;
    union {
        feat_Pt_t p;
        int32_t n;
        uint8_t z;
    } _u;
} feat_Sel_t;

typedef struct feat_MapEnum_s {
    feat_Hue_t h;
    struct { uint32_t len; int32_t* keys; feat_Pt_t* vals; } m;
    struct { uint32_t len; feat_Sel_t* elems; } sels;
} feat_MapEnum_t;

typedef struct feat_Prim_s {
    int8_t i8;
    uint8_t u8;
    int16_t i16;
    uint16_t u16;
    int32_t i32;
    uint32_t u32;
    int64_t i64;
    uint64_t u64;
    float f32;
    double f64;
    uint8_t b;
    uint8_t o;
    char ch;
} feat_Prim_t;

static int feat_Tree_write_body(const feat_Tree_t* v, uint8_t** w_buf_pp, size_t* w_len_pp, size_t* w_cap_pp);
static int feat_Tree_read_body(const uint8_t* buf, size_t len, size_t* pos_pp, feat_Tree_t* v, int zd_be);

static int feat_Tree_write_body(const feat_Tree_t* v, uint8_t** w_buf_pp, size_t* w_len_pp, size_t* w_cap_pp) {
#define w_buf (*w_buf_pp)
#define w_len (*w_len_pp)
#define w_cap (*w_cap_pp)
    const feat_Tree_t* s = v; (void)s;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->value) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t seq_dheader_pos = w_len;
    w_len += 4;
    size_t seq_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->kids).len) != 0) goto fail;
    for (uint32_t i0 = 0; i0 < (s->kids).len; ++i0) {
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t rec_dheader_pos = w_len;
    w_len += 4;
    size_t rec_body_start = w_len;
    if (feat_Tree_write_body(&((s->kids).elems[i0]), &w_buf, &w_len, &w_cap) != 0) goto fail;
    { uint32_t rec_dheader_len = (uint32_t)(w_len - rec_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, rec_dheader_pos, rec_dheader_len); }
    }
    }
    uint32_t seq_dheader_len = (uint32_t)(w_len - seq_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, seq_dheader_pos, seq_dheader_len);
    }
    return 0;
fail:
    return -1;
#undef w_buf
#undef w_len
#undef w_cap
}

static int feat_Tree_read_body(const uint8_t* buf, size_t len, size_t* pos_pp, feat_Tree_t* v, int zd_be) {
#define pos (*pos_pp)
    feat_Tree_t* s = v; (void)s;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->value), zd_be) != 0) return -7;
    {
        uint32_t seq_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_dheader, zd_be) != 0) return -7;
        (void)seq_dheader;
        uint32_t seq_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_len, zd_be) != 0) return -7;
        (s->kids).len = seq_len;
        (s->kids).elems = (struct feat_Tree_s*)calloc(seq_len ? seq_len : 1, sizeof(struct feat_Tree_s));
        if ((s->kids).elems == NULL && seq_len > 0) return -7;
        for (uint32_t i0 = 0; i0 < seq_len; ++i0) {
    { uint32_t rec_dheader = 0; if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &rec_dheader, zd_be) != 0) return -7; (void)rec_dheader; }
    if (feat_Tree_read_body(buf, len, &pos, &((s->kids).elems[i0]), zd_be) != 0) return -7;
        }
    }
    return 0;
#undef pos
}

static int feat_WStr_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_WStr_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_WStr_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_WStr_sample_free(void* sample);

static const char feat_WStr_type_name[] = "feat::WStr";
static const zerodds_typesupport_t feat_WStr_typesupport = {
    .type_hash = {0},
    .type_name = feat_WStr_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_WStr_encode,
    .decode = feat_WStr_decode,
    .key_hash = NULL,
    .sample_free = feat_WStr_sample_free,
};

static int feat_WStr_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_WStr_t* s = (const feat_WStr_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    {
        const uint16_t* ws_p = (const uint16_t*)(s->label);
        uint32_t ws_n = 0;
        if (ws_p) while (ws_p[ws_n]) ++ws_n;
        if (ws_n > 16u) goto fail;
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, ws_n * 2u) != 0) goto fail;
        for (uint32_t wi = 0; wi < ws_n; ++wi) { if (zerodds_xcdr2_c_write_u16(&w_buf, &w_len, &w_cap, ws_p[wi]) != 0) goto fail; }
    }
    {
        const uint16_t* ws_p = (const uint16_t*)(s->text);
        uint32_t ws_n = 0;
        if (ws_p) while (ws_p[ws_n]) ++ws_n;
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, ws_n * 2u) != 0) goto fail;
        for (uint32_t wi = 0; wi < ws_n; ++wi) { if (zerodds_xcdr2_c_write_u16(&w_buf, &w_len, &w_cap, ws_p[wi]) != 0) goto fail; }
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_WStr_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_WStr_decode_e(buf, len, out_sample, 0); }
static int feat_WStr_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_WStr_t* s = (feat_WStr_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    {
        uint32_t ws_bytes = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &ws_bytes, zd_be) != 0) return -7;
        uint32_t ws_n = ws_bytes / 2u;
        uint16_t* ws_p = (uint16_t*)malloc(((size_t)ws_n + 1) * sizeof(uint16_t));
        if (ws_p == NULL) return -7;
        for (uint32_t wi = 0; wi < ws_n; ++wi) { if (zerodds_xcdr2_c_read_u16(buf, len, &pos, &ws_p[wi], zd_be) != 0) { free(ws_p); return -7; } }
        ws_p[ws_n] = 0;
        (s->label) = ws_p;
    }
    {
        uint32_t ws_bytes = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &ws_bytes, zd_be) != 0) return -7;
        uint32_t ws_n = ws_bytes / 2u;
        uint16_t* ws_p = (uint16_t*)malloc(((size_t)ws_n + 1) * sizeof(uint16_t));
        if (ws_p == NULL) return -7;
        for (uint32_t wi = 0; wi < ws_n; ++wi) { if (zerodds_xcdr2_c_read_u16(buf, len, &pos, &ws_p[wi], zd_be) != 0) { free(ws_p); return -7; } }
        ws_p[ws_n] = 0;
        (s->text) = ws_p;
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_WStr_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_WStr_t* s = (feat_WStr_t*)sample;
    (void)s;
    free(s->label); s->label = NULL;
    free(s->text); s->text = NULL;
}

static int feat_Mut_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Mut_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Mut_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Mut_sample_free(void* sample);

static const char feat_Mut_type_name[] = "feat::Mut";
static const zerodds_typesupport_t feat_Mut_typesupport = {
    .type_hash = {0},
    .type_name = feat_Mut_type_name,
    .is_keyed = 0,
    .extensibility = 2,
    ._reserved = {0},
    .encode = feat_Mut_encode,
    .decode = feat_Mut_decode,
    .key_hash = NULL,
    .sample_free = feat_Mut_sample_free,
};

static int feat_Mut_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Mut_t* s = (const feat_Mut_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t mut_body_start = w_len;
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x2000000Au) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->a) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x30000014u) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->b) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x5000001Eu) != 0) goto fail;
    if ((s->c) != NULL && strlen(s->c) > 8u) goto fail;
    if (zerodds_xcdr2_c_write_string(&w_buf, &w_len, &w_cap, s->c) != 0) goto fail;
    }
    uint32_t dheader_len = (uint32_t)(w_len - mut_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Mut_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Mut_decode_e(buf, len, out_sample, 0); }
static int feat_Mut_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Mut_t* s = (feat_Mut_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    while (pos < body_end) {
        uint32_t emheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &emheader, zd_be) != 0) return -7;
        uint32_t mid = emheader & 0x0FFFFFFFu;
        uint32_t lc = (emheader >> 28) & 0x7u;
        uint32_t nextint = 0;
        size_t body_len = 0;
        if (lc == 0) body_len = 1; else if (lc == 1) body_len = 2; else if (lc == 2) body_len = 4; else if (lc == 3) body_len = 8;
        else if (lc == 5) {
            size_t peek_pos = pos;
            if (zerodds_xcdr2_c_read_u32(buf, len, &peek_pos, &nextint, zd_be) != 0) return -7;
            body_len = 4u + (size_t)nextint;
        } else {
            if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nextint, zd_be) != 0) return -7;
            body_len = nextint;
        }
        if (pos + body_len > body_end) return -7;
        switch (mid) {
        case 10: {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->a), zd_be) != 0) return -7;
            break;
        }
        case 20: {
    if (zd_x2_read_f64(buf, len, &pos, &(s->b), zd_be) != 0) return -7;
            break;
        }
        case 30: {
    if (zerodds_xcdr2_c_read_string(buf, len, &pos, &(s->c), zd_be) != 0) return -7;
            break;
        }
        default: pos += body_len; break;
        }
    }
    (void)s;
    return 0;
}

static void feat_Mut_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Mut_t* s = (feat_Mut_t*)sample;
    (void)s;
    free(s->c); s->c = NULL;
}

static int feat_MutLeaf_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_MutLeaf_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_MutLeaf_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_MutLeaf_sample_free(void* sample);

static const char feat_MutLeaf_type_name[] = "feat::MutLeaf";
static const zerodds_typesupport_t feat_MutLeaf_typesupport = {
    .type_hash = {0},
    .type_name = feat_MutLeaf_type_name,
    .is_keyed = 0,
    .extensibility = 2,
    ._reserved = {0},
    .encode = feat_MutLeaf_encode,
    .decode = feat_MutLeaf_decode,
    .key_hash = NULL,
    .sample_free = feat_MutLeaf_sample_free,
};

static int feat_MutLeaf_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_MutLeaf_t* s = (const feat_MutLeaf_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t mut_body_start = w_len;
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x20000001u) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->u) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x30000002u) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->v) != 0) goto fail;
    }
    uint32_t dheader_len = (uint32_t)(w_len - mut_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_MutLeaf_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_MutLeaf_decode_e(buf, len, out_sample, 0); }
static int feat_MutLeaf_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_MutLeaf_t* s = (feat_MutLeaf_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    while (pos < body_end) {
        uint32_t emheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &emheader, zd_be) != 0) return -7;
        uint32_t mid = emheader & 0x0FFFFFFFu;
        uint32_t lc = (emheader >> 28) & 0x7u;
        uint32_t nextint = 0;
        size_t body_len = 0;
        if (lc == 0) body_len = 1; else if (lc == 1) body_len = 2; else if (lc == 2) body_len = 4; else if (lc == 3) body_len = 8;
        else if (lc == 5) {
            size_t peek_pos = pos;
            if (zerodds_xcdr2_c_read_u32(buf, len, &peek_pos, &nextint, zd_be) != 0) return -7;
            body_len = 4u + (size_t)nextint;
        } else {
            if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nextint, zd_be) != 0) return -7;
            body_len = nextint;
        }
        if (pos + body_len > body_end) return -7;
        switch (mid) {
        case 1: {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->u), zd_be) != 0) return -7;
            break;
        }
        case 2: {
    if (zd_x2_read_f64(buf, len, &pos, &(s->v), zd_be) != 0) return -7;
            break;
        }
        default: pos += body_len; break;
        }
    }
    (void)s;
    return 0;
}

static void feat_MutLeaf_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_MutLeaf_t* s = (feat_MutLeaf_t*)sample;
    (void)s;
}

static int feat_MutNest_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_MutNest_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_MutNest_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_MutNest_sample_free(void* sample);

static const char feat_MutNest_type_name[] = "feat::MutNest";
static const zerodds_typesupport_t feat_MutNest_typesupport = {
    .type_hash = {0},
    .type_name = feat_MutNest_type_name,
    .is_keyed = 0,
    .extensibility = 2,
    ._reserved = {0},
    .encode = feat_MutNest_encode,
    .decode = feat_MutNest_decode,
    .key_hash = NULL,
    .sample_free = feat_MutNest_sample_free,
};

static int feat_MutNest_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_MutNest_t* s = (const feat_MutNest_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t mut_body_start = w_len;
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x2000000Au) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->tag) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x50000014u) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x20000001u) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->leaf).u) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x30000002u) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, (s->leaf).v) != 0) goto fail;
    }
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x5000001Eu) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t seq_dheader_pos = w_len;
    w_len += 4;
    size_t seq_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->list).len) != 0) goto fail;
    for (uint32_t i0 = 0; i0 < (s->list).len; ++i0) {
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x20000001u) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->list).elems[i0]).u) != 0) goto fail;
    }
    {
        if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, 0x30000002u) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, ((s->list).elems[i0]).v) != 0) goto fail;
    }
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
    }
    uint32_t seq_dheader_len = (uint32_t)(w_len - seq_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, seq_dheader_pos, seq_dheader_len);
    }
    }
    uint32_t dheader_len = (uint32_t)(w_len - mut_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_MutNest_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_MutNest_decode_e(buf, len, out_sample, 0); }
static int feat_MutNest_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_MutNest_t* s = (feat_MutNest_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    while (pos < body_end) {
        uint32_t emheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &emheader, zd_be) != 0) return -7;
        uint32_t mid = emheader & 0x0FFFFFFFu;
        uint32_t lc = (emheader >> 28) & 0x7u;
        uint32_t nextint = 0;
        size_t body_len = 0;
        if (lc == 0) body_len = 1; else if (lc == 1) body_len = 2; else if (lc == 2) body_len = 4; else if (lc == 3) body_len = 8;
        else if (lc == 5) {
            size_t peek_pos = pos;
            if (zerodds_xcdr2_c_read_u32(buf, len, &peek_pos, &nextint, zd_be) != 0) return -7;
            body_len = 4u + (size_t)nextint;
        } else {
            if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nextint, zd_be) != 0) return -7;
            body_len = nextint;
        }
        if (pos + body_len > body_end) return -7;
        switch (mid) {
        case 10: {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->tag), zd_be) != 0) return -7;
            break;
        }
        case 20: {
    {
        uint32_t nst_dheader0 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader0, zd_be) != 0) return -7;
        size_t nst_end0 = pos + nst_dheader0;
        if (nst_end0 > len) return -7;
        while (pos < nst_end0) {
            uint32_t emheader0 = 0;
            if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &emheader0, zd_be) != 0) return -7;
            uint32_t mid0 = emheader0 & 0x0FFFFFFFu;
            uint32_t lc0 = (emheader0 >> 28) & 0x7u;
            uint32_t nextint0 = 0;
            size_t body_len0 = 0;
            if (lc0 == 0) body_len0 = 1; else if (lc0 == 1) body_len0 = 2; else if (lc0 == 2) body_len0 = 4; else if (lc0 == 3) body_len0 = 8;
            else if (lc0 == 5) {
                size_t peek_pos0 = pos;
                if (zerodds_xcdr2_c_read_u32(buf, len, &peek_pos0, &nextint0, zd_be) != 0) return -7;
                body_len0 = 4u + (size_t)nextint0;
            } else {
                if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nextint0, zd_be) != 0) return -7;
                body_len0 = nextint0;
            }
            if (pos + body_len0 > nst_end0) return -7;
        switch (mid0) {
        case 1: {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->leaf).u), zd_be) != 0) return -7;
            break;
        }
        case 2: {
    if (zd_x2_read_f64(buf, len, &pos, &((s->leaf).v), zd_be) != 0) return -7;
            break;
        }
        default: pos += body_len0; break;
        }
        }
    }
            break;
        }
        case 30: {
    {
        uint32_t seq_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_dheader, zd_be) != 0) return -7;
        (void)seq_dheader;
        uint32_t seq_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_len, zd_be) != 0) return -7;
        (s->list).len = seq_len;
        (s->list).elems = (feat_MutLeaf_t*)calloc(seq_len ? seq_len : 1, sizeof(feat_MutLeaf_t));
        if ((s->list).elems == NULL && seq_len > 0) return -7;
        for (uint32_t i0 = 0; i0 < seq_len; ++i0) {
    {
        uint32_t nst_dheader1 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader1, zd_be) != 0) return -7;
        size_t nst_end1 = pos + nst_dheader1;
        if (nst_end1 > len) return -7;
        while (pos < nst_end1) {
            uint32_t emheader1 = 0;
            if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &emheader1, zd_be) != 0) return -7;
            uint32_t mid1 = emheader1 & 0x0FFFFFFFu;
            uint32_t lc1 = (emheader1 >> 28) & 0x7u;
            uint32_t nextint1 = 0;
            size_t body_len1 = 0;
            if (lc1 == 0) body_len1 = 1; else if (lc1 == 1) body_len1 = 2; else if (lc1 == 2) body_len1 = 4; else if (lc1 == 3) body_len1 = 8;
            else if (lc1 == 5) {
                size_t peek_pos1 = pos;
                if (zerodds_xcdr2_c_read_u32(buf, len, &peek_pos1, &nextint1, zd_be) != 0) return -7;
                body_len1 = 4u + (size_t)nextint1;
            } else {
                if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nextint1, zd_be) != 0) return -7;
                body_len1 = nextint1;
            }
            if (pos + body_len1 > nst_end1) return -7;
        switch (mid1) {
        case 1: {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->list).elems[i0]).u), zd_be) != 0) return -7;
            break;
        }
        case 2: {
    if (zd_x2_read_f64(buf, len, &pos, &(((s->list).elems[i0]).v), zd_be) != 0) return -7;
            break;
        }
        default: pos += body_len1; break;
        }
        }
    }
        }
    }
            break;
        }
        default: pos += body_len; break;
        }
    }
    (void)s;
    return 0;
}

static void feat_MutNest_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_MutNest_t* s = (feat_MutNest_t*)sample;
    (void)s;
    free((s->list).elems); (s->list).elems = NULL; (s->list).len = 0;
}

static int feat_NestedKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_NestedKey_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_NestedKey_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_NestedKey_sample_free(void* sample);
static int feat_NestedKey_key_hash(const void* sample, uint8_t out_hash[16]);

static const char feat_NestedKey_type_name[] = "feat::NestedKey";
static const zerodds_typesupport_t feat_NestedKey_typesupport = {
    .type_hash = {0},
    .type_name = feat_NestedKey_type_name,
    .is_keyed = 1,
    .extensibility = 0,
    ._reserved = {0},
    .encode = feat_NestedKey_encode,
    .decode = feat_NestedKey_decode,
    .key_hash = feat_NestedKey_key_hash,
    .sample_free = feat_NestedKey_sample_free,
};

static int feat_NestedKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_NestedKey_t* s = (const feat_NestedKey_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->hi) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->lo) != 0) goto fail;
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_NestedKey_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_NestedKey_decode_e(buf, len, out_sample, 0); }
static int feat_NestedKey_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_NestedKey_t* s = (feat_NestedKey_t*)out_sample;
    size_t pos = 0;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->hi), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->lo), zd_be) != 0) return -7;
    (void)s;
    return 0;
}

static void feat_NestedKey_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_NestedKey_t* s = (feat_NestedKey_t*)sample;
    (void)s;
}

static int feat_NestedKey_key_hash(const void* sample, uint8_t out_hash[16]) {
    const feat_NestedKey_t* s = (const feat_NestedKey_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->hi) != 0) { free(kh_buf); return -1; }
    if (zerodds_xcdr2_c_kh_write_i32(&kh_buf, &kh_len, &kh_cap, s->lo) != 0) { free(kh_buf); return -1; }
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

static int feat_OuterKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_OuterKey_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_OuterKey_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_OuterKey_sample_free(void* sample);
static int feat_OuterKey_key_hash(const void* sample, uint8_t out_hash[16]);

static const char feat_OuterKey_type_name[] = "feat::OuterKey";
static const zerodds_typesupport_t feat_OuterKey_typesupport = {
    .type_hash = {0},
    .type_name = feat_OuterKey_type_name,
    .is_keyed = 1,
    .extensibility = 0,
    ._reserved = {0},
    .encode = feat_OuterKey_encode,
    .decode = feat_OuterKey_decode,
    .key_hash = feat_OuterKey_key_hash,
    .sample_free = feat_OuterKey_sample_free,
};

static int feat_OuterKey_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_OuterKey_t* s = (const feat_OuterKey_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->k).hi) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->k).lo) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->payload) != 0) goto fail;
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_OuterKey_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_OuterKey_decode_e(buf, len, out_sample, 0); }
static int feat_OuterKey_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_OuterKey_t* s = (feat_OuterKey_t*)out_sample;
    size_t pos = 0;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->k).hi), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->k).lo), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->payload), zd_be) != 0) return -7;
    (void)s;
    return 0;
}

static void feat_OuterKey_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_OuterKey_t* s = (feat_OuterKey_t*)sample;
    (void)s;
}

static int feat_OuterKey_key_hash(const void* sample, uint8_t out_hash[16]) {
    const feat_OuterKey_t* s = (const feat_OuterKey_t*)sample;
    uint8_t* kh_buf = NULL;
    size_t kh_len = 0;
    size_t kh_cap = 0;
    zerodds_xcdr2_c_compute_key_hash(kh_buf, kh_len, /*max_size_static=*/0, out_hash);
    free(kh_buf);
    return 0;
}

static int feat_Bits_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Bits_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Bits_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Bits_sample_free(void* sample);

static const char feat_Bits_type_name[] = "feat::Bits";
static const zerodds_typesupport_t feat_Bits_typesupport = {
    .type_hash = {0},
    .type_name = feat_Bits_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Bits_encode,
    .decode = feat_Bits_decode,
    .key_hash = NULL,
    .sample_free = feat_Bits_sample_free,
};

static int feat_Bits_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Bits_t* s = (const feat_Bits_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, s->perm) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->flags) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Bits_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Bits_decode_e(buf, len, out_sample, 0); }
static int feat_Bits_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Bits_t* s = (feat_Bits_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &(s->perm), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(s->flags), zd_be) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_Bits_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Bits_t* s = (feat_Bits_t*)sample;
    (void)s;
}

static int feat_Tree_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Tree_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Tree_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Tree_sample_free(void* sample);

static const char feat_Tree_type_name[] = "feat::Tree";
static const zerodds_typesupport_t feat_Tree_typesupport = {
    .type_hash = {0},
    .type_name = feat_Tree_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Tree_encode,
    .decode = feat_Tree_decode,
    .key_hash = NULL,
    .sample_free = feat_Tree_sample_free,
};

static int feat_Tree_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Tree_t* s = (const feat_Tree_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->value) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t seq_dheader_pos = w_len;
    w_len += 4;
    size_t seq_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->kids).len) != 0) goto fail;
    for (uint32_t i0 = 0; i0 < (s->kids).len; ++i0) {
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t rec_dheader_pos = w_len;
    w_len += 4;
    size_t rec_body_start = w_len;
    if (feat_Tree_write_body(&((s->kids).elems[i0]), &w_buf, &w_len, &w_cap) != 0) goto fail;
    { uint32_t rec_dheader_len = (uint32_t)(w_len - rec_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, rec_dheader_pos, rec_dheader_len); }
    }
    }
    uint32_t seq_dheader_len = (uint32_t)(w_len - seq_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, seq_dheader_pos, seq_dheader_len);
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Tree_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Tree_decode_e(buf, len, out_sample, 0); }
static int feat_Tree_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Tree_t* s = (feat_Tree_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->value), zd_be) != 0) return -7;
    {
        uint32_t seq_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_dheader, zd_be) != 0) return -7;
        (void)seq_dheader;
        uint32_t seq_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_len, zd_be) != 0) return -7;
        (s->kids).len = seq_len;
        (s->kids).elems = (struct feat_Tree_s*)calloc(seq_len ? seq_len : 1, sizeof(struct feat_Tree_s));
        if ((s->kids).elems == NULL && seq_len > 0) return -7;
        for (uint32_t i0 = 0; i0 < seq_len; ++i0) {
    { uint32_t rec_dheader = 0; if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &rec_dheader, zd_be) != 0) return -7; (void)rec_dheader; }
    if (feat_Tree_read_body(buf, len, &pos, &((s->kids).elems[i0]), zd_be) != 0) return -7;
        }
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_Tree_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Tree_t* s = (feat_Tree_t*)sample;
    (void)s;
    free((s->kids).elems); (s->kids).elems = NULL; (s->kids).len = 0;
}

static int feat_Pt_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Pt_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Pt_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Pt_sample_free(void* sample);

static const char feat_Pt_type_name[] = "feat::Pt";
static const zerodds_typesupport_t feat_Pt_typesupport = {
    .type_hash = {0},
    .type_name = feat_Pt_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Pt_encode,
    .decode = feat_Pt_decode,
    .key_hash = NULL,
    .sample_free = feat_Pt_sample_free,
};

static int feat_Pt_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Pt_t* s = (const feat_Pt_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->x) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->y) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Pt_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Pt_decode_e(buf, len, out_sample, 0); }
static int feat_Pt_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Pt_t* s = (feat_Pt_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->x), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->y), zd_be) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_Pt_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Pt_t* s = (feat_Pt_t*)sample;
    (void)s;
}

static int feat_Arr_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Arr_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Arr_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Arr_sample_free(void* sample);

static const char feat_Arr_type_name[] = "feat::Arr";
static const zerodds_typesupport_t feat_Arr_typesupport = {
    .type_hash = {0},
    .type_name = feat_Arr_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Arr_encode,
    .decode = feat_Arr_decode,
    .key_hash = NULL,
    .sample_free = feat_Arr_sample_free,
};

static int feat_Arr_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Arr_t* s = (const feat_Arr_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    for (uint32_t ai0 = 0; ai0 < 2; ++ai0) {
    for (uint32_t ai1 = 0; ai1 < 3; ++ai1) {
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->grid[ai0][ai1]) != 0) goto fail;
    }
    }
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t arr_dheader_pos = w_len;
    w_len += 4;
    size_t arr_body_start = w_len;
    for (uint32_t ai0 = 0; ai0 < 2; ++ai0) {
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->shape[ai0]).x) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->shape[ai0]).y) != 0) goto fail;
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
    }
    { uint32_t arr_dheader_len = (uint32_t)(w_len - arr_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, arr_dheader_pos, arr_dheader_len); }
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Arr_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Arr_decode_e(buf, len, out_sample, 0); }
static int feat_Arr_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Arr_t* s = (feat_Arr_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    for (uint32_t ri0 = 0; ri0 < 2; ++ri0) {
    for (uint32_t ri1 = 0; ri1 < 3; ++ri1) {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->grid[ri0][ri1]), zd_be) != 0) return -7;
    }
    }
    { uint32_t arr_dheader = 0; if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &arr_dheader, zd_be) != 0) return -7; (void)arr_dheader; }
    for (uint32_t ri0 = 0; ri0 < 2; ++ri0) {
    {
        uint32_t nst_dheader0 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader0, zd_be) != 0) return -7;
        size_t nst_end0 = pos + nst_dheader0;
        if (nst_end0 > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->shape[ri0]).x), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->shape[ri0]).y), zd_be) != 0) return -7;
        pos = nst_end0;
    }
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_Arr_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Arr_t* s = (feat_Arr_t*)sample;
    (void)s;
    for (uint32_t fi0 = 0; fi0 < 2; ++fi0) {
    for (uint32_t fi1 = 0; fi1 < 3; ++fi1) {
    }
    }
    for (uint32_t fi0 = 0; fi0 < 2; ++fi0) {
    }
}

static int feat_Sel_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Sel_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Sel_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Sel_sample_free(void* sample);

static const char feat_Sel_type_name[] = "feat::Sel";
static const zerodds_typesupport_t feat_Sel_typesupport = {
    .type_hash = {0},
    .type_name = feat_Sel_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Sel_encode,
    .decode = feat_Sel_decode,
    .key_hash = NULL,
    .sample_free = feat_Sel_sample_free,
};

static int feat_Sel_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Sel_t* s = (const feat_Sel_t*)sample;
    (void)s;
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    {
    if (zerodds_xcdr2_c_pad_to(&w_buf, &w_len, &w_cap, 4) != 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t u_dheader_pos = w_len; w_len += 4;
    size_t u_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((*s))._d) != 0) goto fail;
    switch (((*s))._d) {
    case 1:
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (((*s))._u.p).x) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (((*s))._u.p).y) != 0) goto fail;
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
        break;
    case 2:
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((*s))._u.n) != 0) goto fail;
        break;
    default:
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, ((*s))._u.z) != 0) goto fail;
        break;
    }
    { uint32_t u_dheader_len = (uint32_t)(w_len - u_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, u_dheader_pos, u_dheader_len); }
    }
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Sel_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Sel_decode_e(buf, len, out_sample, 0); }
static int feat_Sel_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Sel_t* s = (feat_Sel_t*)out_sample;
    size_t pos = 0;
    if (zerodds_xcdr2_c_pad_read(buf, len, &pos, 4) != 0) return -1;
    { uint32_t u_dh = 0; if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &u_dh, zd_be) != 0) return -7; (void)u_dh; }
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((*s))._d), zd_be) != 0) return -7;
    switch (((*s))._d) {
    case 1:
    {
        uint32_t nst_dheader0 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader0, zd_be) != 0) return -7;
        size_t nst_end0 = pos + nst_dheader0;
        if (nst_end0 > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((((*s))._u.p).x), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((((*s))._u.p).y), zd_be) != 0) return -7;
        pos = nst_end0;
    }
        break;
    case 2:
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((*s))._u.n), zd_be) != 0) return -7;
        break;
    default:
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(((*s))._u.z), zd_be) != 0) return -7;
        break;
    }
    (void)s;
    return 0;
}

static void feat_Sel_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Sel_t* s = (feat_Sel_t*)sample;
    (void)s;
}

static int feat_MapEnum_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_MapEnum_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_MapEnum_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_MapEnum_sample_free(void* sample);

static const char feat_MapEnum_type_name[] = "feat::MapEnum";
static const zerodds_typesupport_t feat_MapEnum_typesupport = {
    .type_hash = {0},
    .type_name = feat_MapEnum_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_MapEnum_encode,
    .decode = feat_MapEnum_decode,
    .key_hash = NULL,
    .sample_free = feat_MapEnum_sample_free,
};

static int feat_MapEnum_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_MapEnum_t* s = (const feat_MapEnum_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_u16(&w_buf, &w_len, &w_cap, (uint16_t)(s->h)) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_pad_to(&w_buf, &w_len, &w_cap, 4) != 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t map_dheader_pos = w_len;
    w_len += 4;
    size_t map_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->m).len) != 0) goto fail;
    for (uint32_t mi0 = 0; mi0 < (s->m).len; ++mi0) {
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (s->m).keys[mi0]) != 0) goto fail;
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->m).vals[mi0]).x) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->m).vals[mi0]).y) != 0) goto fail;
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
    }
    uint32_t map_dheader_len = (uint32_t)(w_len - map_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, map_dheader_pos, map_dheader_len);
    }
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t seq_dheader_pos = w_len;
    w_len += 4;
    size_t seq_body_start = w_len;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, (s->sels).len) != 0) goto fail;
    for (uint32_t i0 = 0; i0 < (s->sels).len; ++i0) {
    {
    if (zerodds_xcdr2_c_pad_to(&w_buf, &w_len, &w_cap, 4) != 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t u_dheader_pos = w_len; w_len += 4;
    size_t u_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->sels).elems[i0])._d) != 0) goto fail;
    switch (((s->sels).elems[i0])._d) {
    case 1:
    {
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t nst_dheader_pos = w_len;
    w_len += 4;
    size_t nst_body_start = w_len;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (((s->sels).elems[i0])._u.p).x) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, (((s->sels).elems[i0])._u.p).y) != 0) goto fail;
    { uint32_t nst_dheader_len = (uint32_t)(w_len - nst_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, nst_dheader_pos, nst_dheader_len); }
    }
        break;
    case 2:
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, ((s->sels).elems[i0])._u.n) != 0) goto fail;
        break;
    default:
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, ((s->sels).elems[i0])._u.z) != 0) goto fail;
        break;
    }
    { uint32_t u_dheader_len = (uint32_t)(w_len - u_body_start);
      zerodds_xcdr2_c_put_u32_at(w_buf, u_dheader_pos, u_dheader_len); }
    }
    }
    uint32_t seq_dheader_len = (uint32_t)(w_len - seq_body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, seq_dheader_pos, seq_dheader_len);
    }
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_MapEnum_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_MapEnum_decode_e(buf, len, out_sample, 0); }
static int feat_MapEnum_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_MapEnum_t* s = (feat_MapEnum_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    { uint16_t zd_e16 = 0; if (zerodds_xcdr2_c_read_u16(buf, len, &pos, &zd_e16, zd_be) != 0) return -7; (s->h) = (int32_t)(int16_t)zd_e16; }
    {
        if (zerodds_xcdr2_c_pad_read(buf, len, &pos, 4) != 0) return -1;
        uint32_t map_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &map_dheader, zd_be) != 0) return -7;
        (void)map_dheader;
        uint32_t map_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &map_len, zd_be) != 0) return -7;
        (s->m).len = map_len;
        (s->m).keys = (int32_t*)calloc(map_len ? map_len : 1, sizeof(int32_t));
        (s->m).vals = (feat_Pt_t*)calloc(map_len ? map_len : 1, sizeof(feat_Pt_t));
        if ((((s->m).keys == NULL) || ((s->m).vals == NULL)) && map_len > 0) return -7;
        for (uint32_t mi0 = 0; mi0 < map_len; ++mi0) {
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((s->m).keys[mi0]), zd_be) != 0) return -7;
    {
        uint32_t nst_dheader1 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader1, zd_be) != 0) return -7;
        size_t nst_end1 = pos + nst_dheader1;
        if (nst_end1 > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->m).vals[mi0]).x), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->m).vals[mi0]).y), zd_be) != 0) return -7;
        pos = nst_end1;
    }
        }
    }
    {
        uint32_t seq_dheader = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_dheader, zd_be) != 0) return -7;
        (void)seq_dheader;
        uint32_t seq_len = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &seq_len, zd_be) != 0) return -7;
        (s->sels).len = seq_len;
        (s->sels).elems = (feat_Sel_t*)calloc(seq_len ? seq_len : 1, sizeof(feat_Sel_t));
        if ((s->sels).elems == NULL && seq_len > 0) return -7;
        for (uint32_t i0 = 0; i0 < seq_len; ++i0) {
    if (zerodds_xcdr2_c_pad_read(buf, len, &pos, 4) != 0) return -1;
    { uint32_t u_dh = 0; if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &u_dh, zd_be) != 0) return -7; (void)u_dh; }
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->sels).elems[i0])._d), zd_be) != 0) return -7;
    switch (((s->sels).elems[i0])._d) {
    case 1:
    {
        uint32_t nst_dheader1 = 0;
        if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &nst_dheader1, zd_be) != 0) return -7;
        size_t nst_end1 = pos + nst_dheader1;
        if (nst_end1 > len) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((((s->sels).elems[i0])._u.p).x), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &((((s->sels).elems[i0])._u.p).y), zd_be) != 0) return -7;
        pos = nst_end1;
    }
        break;
    case 2:
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(((s->sels).elems[i0])._u.n), zd_be) != 0) return -7;
        break;
    default:
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(((s->sels).elems[i0])._u.z), zd_be) != 0) return -7;
        break;
    }
        }
    }
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_MapEnum_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_MapEnum_t* s = (feat_MapEnum_t*)sample;
    (void)s;
    free((s->m).keys); (s->m).keys = NULL;
    free((s->m).vals); (s->m).vals = NULL; (s->m).len = 0;
    free((s->sels).elems); (s->sels).elems = NULL; (s->sels).len = 0;
}

static int feat_Prim_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len);
static int feat_Prim_decode(const uint8_t* buf, size_t len, void* out_sample);
static int feat_Prim_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be);
static void feat_Prim_sample_free(void* sample);

static const char feat_Prim_type_name[] = "feat::Prim";
static const zerodds_typesupport_t feat_Prim_typesupport = {
    .type_hash = {0},
    .type_name = feat_Prim_type_name,
    .is_keyed = 0,
    .extensibility = 1,
    ._reserved = {0},
    .encode = feat_Prim_encode,
    .decode = feat_Prim_decode,
    .key_hash = NULL,
    .sample_free = feat_Prim_sample_free,
};

static int feat_Prim_encode(const void* sample, uint8_t* out_buf, size_t out_cap, size_t* out_len) {
    const feat_Prim_t* s = (const feat_Prim_t*)sample;
    (void)s;
    /* Two-pass: grow the buffer, then copy. */
    uint8_t* w_buf = NULL;
    size_t w_len = 0;
    size_t w_cap = 0;
    if (out_buf == NULL && out_cap > 0) goto fail;
    if (zerodds_xcdr2_c_grow(&w_buf, &w_cap, w_len + 4) != 0) goto fail;
    size_t dheader_pos = w_len;
    w_len += 4;
    size_t body_start = w_len;
    if (zerodds_xcdr2_c_write_i8(&w_buf, &w_len, &w_cap, s->i8) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->u8) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i16(&w_buf, &w_len, &w_cap, s->i16) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u16(&w_buf, &w_len, &w_cap, s->u16) != 0) goto fail;
    if (zerodds_xcdr2_c_write_i32(&w_buf, &w_len, &w_cap, s->i32) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u32(&w_buf, &w_len, &w_cap, s->u32) != 0) goto fail;
    if (zd_x2_write_i64(&w_buf, &w_len, &w_cap, s->i64) != 0) goto fail;
    if (zd_x2_write_u64(&w_buf, &w_len, &w_cap, s->u64) != 0) goto fail;
    if (zerodds_xcdr2_c_write_f32(&w_buf, &w_len, &w_cap, s->f32) != 0) goto fail;
    if (zd_x2_write_f64(&w_buf, &w_len, &w_cap, s->f64) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->b) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->o) != 0) goto fail;
    if (zerodds_xcdr2_c_write_u8(&w_buf, &w_len, &w_cap, s->ch) != 0) goto fail;
    uint32_t dheader_len = (uint32_t)(w_len - body_start);
    zerodds_xcdr2_c_put_u32_at(w_buf, dheader_pos, dheader_len);
    if (out_len) *out_len = w_len;
    if (out_buf == NULL || out_cap < w_len) { free(w_buf); return -13; }
    if (w_len > 0) memcpy(out_buf, w_buf, w_len);
    free(w_buf);
    return 0;
fail:
    free(w_buf);
    return -1;
}

static int feat_Prim_decode(const uint8_t* buf, size_t len, void* out_sample) { return feat_Prim_decode_e(buf, len, out_sample, 0); }
static int feat_Prim_decode_e(const uint8_t* buf, size_t len, void* out_sample, int zd_be) {
    feat_Prim_t* s = (feat_Prim_t*)out_sample;
    size_t pos = 0;
    uint32_t dheader = 0;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &dheader, zd_be) != 0) return -7;
    size_t body_end = pos + dheader;
    if (body_end > len) return -7;
    if (zerodds_xcdr2_c_read_i8(buf, len, &pos, &(s->i8), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(s->u8), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i16(buf, len, &pos, &(s->i16), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u16(buf, len, &pos, &(s->u16), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_i32(buf, len, &pos, &(s->i32), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u32(buf, len, &pos, &(s->u32), zd_be) != 0) return -7;
    if (zd_x2_read_i64(buf, len, &pos, &(s->i64), zd_be) != 0) return -7;
    if (zd_x2_read_u64(buf, len, &pos, &(s->u64), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_f32(buf, len, &pos, &(s->f32), zd_be) != 0) return -7;
    if (zd_x2_read_f64(buf, len, &pos, &(s->f64), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(s->b), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(s->o), zd_be) != 0) return -7;
    if (zerodds_xcdr2_c_read_u8(buf, len, &pos, &(s->ch), zd_be) != 0) return -7;
    pos = body_end;
    (void)s;
    return 0;
}

static void feat_Prim_sample_free(void* sample) {
    if (sample == NULL) return;
    feat_Prim_t* s = (feat_Prim_t*)sample;
    (void)s;
}

#ifdef __cplusplus
}
#endif
#endif
