// Generated by zerodds idl-csharp. Do not edit.
// Target: C# 12.0 / .NET 8+
#nullable enable

using Omg.Types;
using System;
using System.Collections.Generic;
using ZeroDDS.Cdr;

namespace confcombo
{
    public enum Mode : int
    {
        MODE_IDLE,
        MODE_ACTIVE,
        MODE_FAULT,
    }

    [Extensibility(ExtensibilityKind.Appendable)]
    public partial record class Telemetry : ITopicType<Telemetry>
    {
        [Key]
        public int UnitId { get; init; } = default!;
        [Key]
        public string Region { get; init; } = default!;
        public Mode Mode { get; init; } = default!;
        public double BatteryVolts { get; init; } = default!;
        public ISequence<int> Samples { get; init; } = default!;
        public IBoundedSequence<int> RecentCodes { get; init; } = default!;
        public ISequence<string> Tags { get; init; } = default!;
        [Optional]
        public double? Calibration { get; init; } = default!;
    }

    public sealed class TelemetryTypeSupport : IDdsTopicType<Telemetry>
    {
        public static readonly TelemetryTypeSupport Instance = new();

        public string TypeName => "confcombo::Telemetry";
        public bool IsKeyed => true;
        public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

        public byte[] Encode(Telemetry sample) => Encode(sample, EndianMode.LittleEndian);

        public byte[] Encode(Telemetry sample, EndianMode endian)
        {
            var w = new Xcdr2Writer(endian);
            EncodeInto(w, sample);
            return w.ToArray();
        }

        public void EncodeInto(Xcdr2Writer w, Telemetry sample)
        {
            using (var __scope = w.BeginAppendable())
            {
                w.WriteInt32(sample.UnitId);
                if ((sample.Region) != null && System.Text.Encoding.UTF8.GetByteCount(sample.Region) > 32) throw new System.ArgumentException("bounded string length exceeds its IDL bound (32)");
                w.WriteString(sample.Region);
                w.WriteInt32((int)sample.Mode);
                w.WriteFloat64(sample.BatteryVolts);
                {
                    var __seq = (sample.Samples) as System.Collections.Generic.IEnumerable<int>;
                    var __mat = __seq is null ? new System.Collections.Generic.List<int>() : new System.Collections.Generic.List<int>(__seq);
                    w.WriteSequenceLength(__mat.Count);
                    foreach (var __item in __mat)
                    {
                        w.WriteInt32(__item);
                    }
                }
                {
                    var __seq = (sample.RecentCodes) as System.Collections.Generic.IEnumerable<int>;
                    var __mat = __seq is null ? new System.Collections.Generic.List<int>() : new System.Collections.Generic.List<int>(__seq);
                    if (__mat.Count > 8) throw new System.ArgumentException("bounded sequence length exceeds its IDL bound (8)");
                    w.WriteSequenceLength(__mat.Count);
                    foreach (var __item in __mat)
                    {
                        w.WriteInt32(__item);
                    }
                }
                {
                    var __seq = (sample.Tags) as System.Collections.Generic.IEnumerable<string>;
                    var __mat = __seq is null ? new System.Collections.Generic.List<string>() : new System.Collections.Generic.List<string>(__seq);
                    using (var __seqdh = w.BeginAppendable())
                    {
                        w.WriteSequenceLength(__mat.Count);
                        foreach (var __item in __mat)
                        {
                            w.WriteString(__item);
                        }
                    }
                }
                if (sample.Calibration is null) { w.WriteOctet(0); }
                else
                {
                    w.WriteOctet(1);
                    w.WriteFloat64(sample.Calibration.Value);
                }
            }
        }

        public Telemetry Decode(ReadOnlySpan<byte> bytes)
        {
            var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
            return DecodeFrom(r);
        }

        public Telemetry DecodeFrom(Xcdr2Reader r)
        {
            var __scope = r.BeginDHeader();
            int __m0 = default;
            __m0 = r.ReadInt32();
            string __m1 = default;
            __m1 = r.ReadString();
            Mode __m2 = default;
            __m2 = (Mode)r.ReadInt32();
            double __m3 = default;
            __m3 = r.ReadFloat64();
            Omg.Types.ISequence<int> __m4 = default;
            {
                int __cnt = r.ReadSequenceLength();
                var __list = new Omg.Types.SequenceList<int>();
                for (int __i = 0; __i < __cnt; __i++)
                {
                    int __e;
                    __e = r.ReadInt32();
                    __list.Add(__e);
                }
                __m4 = __list;
            }
            Omg.Types.ISequence<int> __m5 = default;
            {
                int __cnt = r.ReadSequenceLength();
                var __list = new Omg.Types.SequenceList<int>();
                for (int __i = 0; __i < __cnt; __i++)
                {
                    int __e;
                    __e = r.ReadInt32();
                    __list.Add(__e);
                }
                __m5 = __list;
            }
            Omg.Types.ISequence<string> __m6 = default;
            {
                var __seqdh = r.BeginDHeader();
                int __cnt = r.ReadSequenceLength();
                var __list = new Omg.Types.SequenceList<string>();
                for (int __i = 0; __i < __cnt; __i++)
                {
                    string __e;
                    __e = r.ReadString();
                    __list.Add(__e);
                }
                r.EndDHeader(__seqdh);
                __m6 = __list;
            }
            double? __m7 = default;
            {
                byte __present = r.ReadOctet();
                if (__present != 0)
                {
                    __m7 = r.ReadFloat64();
                }
            }
            r.EndDHeader(__scope);
            return new Telemetry
            {
                UnitId = __m0!,
                Region = __m1!,
                Mode = __m2!,
                BatteryVolts = __m3!,
                Samples = __m4!,
                RecentCodes = __m5!,
                Tags = __m6!,
                Calibration = __m7!,
            };
        }

        public byte[] KeyHash(Telemetry sample)
        {
            var __kw = new Xcdr2Writer(EndianMode.BigEndian);
            __kw.WriteInt32(sample.UnitId);
            __kw.WriteString(sample.Region);
            var __kb = __kw.ToArray();
            if (__kb.Length > 16) { return Md5.Hash(__kb); }
            var __h = new byte[16];
            System.Array.Copy(__kb, 0, __h, 0, __kb.Length);
            return __h;
        }
    }

} // namespace confcombo

// XTypes 1.3 Minimal TypeObjects (XCDR2-LE serialised)
public static class TypeObjects
{
    /// <summary>Minimal TypeObject for confcombo::Mode.</summary>
    public static readonly byte[] confcombo_Mode = {
        0x40, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xdb, 0x78, 0xd3, 0x17, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x15, 0xd1, 0xdf, 0x00, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0xb2, 0xc5, 0xb2, 0x9f,
    };
    /// <summary>Minimal TypeObject for confcombo::Telemetry.</summary>
    public static readonly byte[] confcombo_Telemetry = {
        0x50, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x20, 0x00, 0x04, 0x3a, 0xe0, 0xf2, 0xbc, 0x00,
        0x02, 0x00, 0x00, 0x00, 0x20, 0x00, 0x70, 0x20, 0x96, 0x0d, 0xb2, 0xed,
        0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf1, 0x31, 0xcc, 0xe6, 0x28, 0xbb,
        0xdf, 0x5a, 0xc9, 0x28, 0x23, 0xc7, 0x8a, 0x34, 0x7c, 0x15, 0xd6, 0x17,
        0x12, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x93,
        0x2e, 0xd1, 0x17, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00,
        0x00, 0x00, 0x00, 0x04, 0x6e, 0xf9, 0x16, 0x1b, 0x06, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x08, 0x04, 0x3d, 0xef, 0xf6, 0xb6,
        0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x70,
        0x00, 0xd5, 0x7a, 0xc4, 0x52, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
        0x08, 0x00, 0x0a, 0x0b, 0xf7, 0x19, 0xdf,
    };
}
