// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class Arr implements org.omg.dds.topic.TopicType<Arr> {
    private int[][] grid;
    private Pt[] shape;

    public Arr() {}

    public int[][] getGrid() { return grid; }
    public void setGrid(int[][] grid) { this.grid = grid; }
    public Pt[] getShape() { return shape; }
    public void setShape(Pt[] shape) { this.shape = shape; }
}
