// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Arr. Generated by zerodds idl-java. */
public final class ArrTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Arr> {
    public static final ArrTypeSupport INSTANCE = new ArrTypeSupport();

    private ArrTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Arr"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Arr sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Arr sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Arr sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        for (int __ai0 = 0; __ai0 < 2; __ai0++) {
            for (int __ai1 = 0; __ai1 < 3; __ai1++) {
                w.writeInt32(sample.getGrid()[__ai0][__ai1]);
            }
        }
        {
            int __adh0 = w.beginAppendable();
            for (int __ai0 = 0; __ai0 < 2; __ai0++) {
                w.align(4);
                w.writeBytes(PtTypeSupport.INSTANCE.encode(sample.getShape()[__ai0], endian, w.isXcdr1() ? 0 : 1));
            }
            w.endDelimited(__adh0);
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Arr decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Arr decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Arr decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Arr decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Arr decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Arr v = new Arr();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            int[][] __arr = new int[2][3];
            for (int __ad0 = 0; __ad0 < 2; __ad0++) {
                for (int __ad1 = 0; __ad1 < 3; __ad1++) {
                    int __av1 = r.readInt32();
                    __arr[__ad0][__ad1] = __av1;
                }
            }
            v.setGrid(__arr);
        }
        {
            Pt[] __arr = new Pt[2];
            r.readDHeader();
            for (int __ad0 = 0; __ad0 < 2; __ad0++) {
                Pt __av0 = PtTypeSupport.decodeFrom(r);
                __arr[__ad0] = __av0;
            }
            v.setShape(__arr);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(Arr sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
