// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class Bits implements org.omg.dds.topic.TopicType<Bits> {
    private Perm perm;
    private Flags flags;

    public Bits() {}

    public Perm getPerm() { return perm; }
    public void setPerm(Perm perm) { this.perm = perm; }
    public Flags getFlags() { return flags; }
    public void setFlags(Flags flags) { this.flags = flags; }
}
