// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Bits. Generated by zerodds idl-java. */
public final class BitsTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Bits> {
    public static final BitsTypeSupport INSTANCE = new BitsTypeSupport();

    private BitsTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Bits"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Bits sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Bits sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Bits sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        {
            long __bm = 0L;
            if (sample.getPerm() != null) for (Perm.Flag __f : (sample.getPerm()).bits()) { __bm |= (1L << __f.position()); }
            w.writeUInt32(__bm & 0xFFFFFFFFL);
        }
        {
            long __bs = (sample.getFlags()).rawBits();
            w.writeUInt8((int) (__bs & 0xFFL));
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Bits decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Bits decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Bits decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Bits decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Bits decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Bits v = new Bits();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            long __bmh0 = r.readUInt32();
            Perm __rv = new Perm();
            for (Perm.Flag __bf0 : Perm.Flag.values()) { if ((__bmh0 & (1L << __bf0.position())) != 0) { __rv.set(__bf0); } }
            v.setPerm(__rv);
        }
        {
            Flags __rv = new Flags((long) r.readUInt8());
            v.setFlags(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(Bits sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
