// Generated by zerodds idl-java. Do not edit.
package feat;

public final class Flags {
    /** Cumulative bit-storage (width = 8). */
    public static final int BIT_WIDTH = 8;
    private long bits;

    public Flags() {}
    public Flags(long bits) { this.bits = bits; }
    public long rawBits() { return bits; }
    public void setRawBits(long bits) { this.bits = bits; }

    /** width=3 offset=0 */
    public int getKind() { return (int)((bits >>> 0) & 0x7L); }
    public void setKind(int value) { bits = (bits & ~(0x7L << 0)) | ((((long)value) & 0x7L) << 0); }
    /** width=5 offset=3 */
    public int getPrio() { return (int)((bits >>> 3) & 0x1FL); }
    public void setPrio(int value) { bits = (bits & ~(0x1FL << 3)) | ((((long)value) & 0x1FL) << 3); }
}
