// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public enum Hue {
    H_RED(0),
    H_GREEN(1),
    H_BLUE(2);

    private final int value;
    Hue(int value) { this.value = value; }
    public int value() { return value; }
}
