// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class MapEnum implements org.omg.dds.topic.TopicType<MapEnum> {
    private Hue h;
    private java.util.Map<Integer, Pt> m;
    private java.util.List<Sel> sels;

    public MapEnum() {}

    public Hue getH() { return h; }
    public void setH(Hue h) { this.h = h; }
    public java.util.Map<Integer, Pt> getM() { return m; }
    public void setM(java.util.Map<Integer, Pt> m) { this.m = m; }
    public java.util.List<Sel> getSels() { return sels; }
    public void setSels(java.util.List<Sel> sels) { this.sels = sels; }
}
