// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for MapEnum. Generated by zerodds idl-java. */
public final class MapEnumTypeSupport implements org.zerodds.cdr.TopicTypeSupport<MapEnum> {
    public static final MapEnumTypeSupport INSTANCE = new MapEnumTypeSupport();

    private MapEnumTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::MapEnum"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(MapEnum sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(MapEnum sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(MapEnum sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        w.writeInt16((short)((sample.getH()).value()));
        {
            java.util.Map<Integer, Pt> __map0 = (sample.getM() == null) ? java.util.Collections.<Integer, Pt>emptyMap() : (sample.getM());
            int __mapdh0 = w.beginAppendable();
            w.writeSequenceCount(__map0.size());
            for (java.util.Map.Entry<Integer, Pt> __ment0 : __map0.entrySet()) {
                w.writeInt32(__ment0.getKey());
                w.align(4);
                w.writeBytes(PtTypeSupport.INSTANCE.encode(__ment0.getValue(), endian, w.isXcdr1() ? 0 : 1));
            }
            w.endDelimited(__mapdh0);
        }
        {
            java.util.List<Sel> __seq0 = (sample.getSels() == null) ? java.util.Collections.<Sel>emptyList() : (sample.getSels());
            int __seqdh0 = w.beginAppendable();
            w.writeSequenceCount(__seq0.size());
            for (Sel __el0 : __seq0) {
                w.align(4);
                w.writeBytes(SelTypeSupport.INSTANCE.encode(__el0, endian, w.isXcdr1() ? 0 : 1));
            }
            w.endDelimited(__seqdh0);
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public MapEnum decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public MapEnum decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public MapEnum decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public MapEnum decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static MapEnum decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        MapEnum v = new MapEnum();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            int __ord0 = r.readInt16();
            Hue __rv = null;
            for (Hue __ec0 : Hue.values()) { if (__ec0.value() == __ord0) { __rv = __ec0; break; } }
            v.setH(__rv);
        }
        {
            java.util.Map<Integer, Pt> __rv;
            {
                r.readDHeader();
                int __mcnt0 = r.readSequenceCount();
                java.util.Map<Integer, Pt> __mout0 = new java.util.LinkedHashMap<>();
                for (int __mi0 = 0; __mi0 < __mcnt0; __mi0++) {
                    Integer __mk0 = r.readInt32();
                    Pt __mv0 = PtTypeSupport.decodeFrom(r);
                    __mout0.put(__mk0, __mv0);
                }
                __rv = __mout0;
            }
            v.setM(__rv);
        }
        {
            java.util.List<Sel> __rv;
            {
                r.readDHeader();
                int __cnt0 = r.readSequenceCount();
                java.util.List<Sel> __out0 = new java.util.ArrayList<>(__cnt0);
                for (int __si0 = 0; __si0 < __cnt0; __si0++) {
                    Sel __se0 = SelTypeSupport.decodeFrom(r);
                    __out0.add(__se0);
                }
                __rv = __out0;
            }
            v.setSels(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(MapEnum sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
