// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class MapPrim implements org.omg.dds.topic.TopicType<MapPrim> {
    private java.util.Map<Integer, Integer> m;

    public MapPrim() {}

    public java.util.Map<Integer, Integer> getM() { return m; }
    public void setM(java.util.Map<Integer, Integer> m) { this.m = m; }
}
