// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for MapPrim. Generated by zerodds idl-java. */
public final class MapPrimTypeSupport implements org.zerodds.cdr.TopicTypeSupport<MapPrim> {
    public static final MapPrimTypeSupport INSTANCE = new MapPrimTypeSupport();

    private MapPrimTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::MapPrim"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(MapPrim sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(MapPrim sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(MapPrim sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        {
            java.util.Map<Integer, Integer> __map0 = (sample.getM() == null) ? java.util.Collections.<Integer, Integer>emptyMap() : (sample.getM());
            w.writeSequenceCount(__map0.size());
            for (java.util.Map.Entry<Integer, Integer> __ment0 : __map0.entrySet()) {
                w.writeInt32(__ment0.getKey());
                w.writeInt32(__ment0.getValue());
            }
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public MapPrim decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public MapPrim decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public MapPrim decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public MapPrim decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static MapPrim decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        MapPrim v = new MapPrim();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            java.util.Map<Integer, Integer> __rv;
            {
                int __mcnt0 = r.readSequenceCount();
                java.util.Map<Integer, Integer> __mout0 = new java.util.LinkedHashMap<>();
                for (int __mi0 = 0; __mi0 < __mcnt0; __mi0++) {
                    Integer __mk0 = r.readInt32();
                    Integer __mv0 = r.readInt32();
                    __mout0.put(__mk0, __mv0);
                }
                __rv = __mout0;
            }
            v.setM(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(MapPrim sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
