// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class Money implements org.omg.dds.topic.TopicType<Money> {
    private java.math.BigDecimal price;
    private java.math.BigDecimal qty;

    public Money() {}

    public java.math.BigDecimal getPrice() { return price; }
    public void setPrice(java.math.BigDecimal price) { this.price = price; }
    public java.math.BigDecimal getQty() { return qty; }
    public void setQty(java.math.BigDecimal qty) { this.qty = qty; }
}
