// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.MUTABLE)
public class Mut implements org.omg.dds.topic.TopicType<Mut> {
    @org.zerodds.types.Id(10)
    private int a;
    @org.zerodds.types.Id(20)
    private double b;
    @org.zerodds.types.Id(30)
    private String c;

    public Mut() {}

    public int getA() { return a; }
    public void setA(int a) { this.a = a; }
    public double getB() { return b; }
    public void setB(double b) { this.b = b; }
    public String getC() { return c; }
    public void setC(String c) { this.c = c; }
}
