// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for MutLeaf. Generated by zerodds idl-java. */
public final class MutLeafTypeSupport implements org.zerodds.cdr.TopicTypeSupport<MutLeaf> {
    public static final MutLeafTypeSupport INSTANCE = new MutLeafTypeSupport();

    private MutLeafTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::MutLeaf"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.MUTABLE; }

    @Override
    public byte[] encode(MutLeaf sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(MutLeaf sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(MutLeaf sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        if (w.isXcdr1()) {
            {
                org.zerodds.cdr.Xcdr2Writer __plw1 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw1.writeInt32(sample.getU());
                w.writePlCdr1Member(1, __plw1.toByteArray());
            }
            {
                org.zerodds.cdr.Xcdr2Writer __plw2 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw2.writeFloat64(sample.getV());
                w.writePlCdr1Member(2, __plw2.toByteArray());
            }
            w.writePlCdr1Sentinel();
        } else {
            int __dh = w.beginMutable();
            w.writeEmHeader(1, org.zerodds.cdr.Xcdr2Writer.LC_INT32, false);
            w.writeInt32(sample.getU());
            w.writeEmHeader(2, org.zerodds.cdr.Xcdr2Writer.LC_INT64, false);
            w.writeFloat64(sample.getV());
            w.endDelimited(__dh);
        }
        return w.toByteArray();
    }

    @Override
    public MutLeaf decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public MutLeaf decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public MutLeaf decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public MutLeaf decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static MutLeaf decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        MutLeaf v = new MutLeaf();
        if (r.isXcdr1()) {
            org.zerodds.cdr.Xcdr2Reader.PlCdr1Member __plm;
            while ((__plm = r.beginPlCdr1Member()) != null) {
            if (__plm.memberId == 1) {
                {
                    int __rv = r.readInt32();
                    v.setU(__rv);
                }
            }
            else if (__plm.memberId == 2) {
                {
                    double __rv = r.readFloat64();
                    v.setV(__rv);
                }
            }
                r.endPlCdr1Member(__plm);
            }
            return v;
        }
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        while (r.position() < __endPos) {
            org.zerodds.cdr.Xcdr2Reader.EmHeader __em = r.readEmHeader();
            int __ni = (__em.lc == 4) ? r.readNextInt() : -1;
            if (__em.memberId == 1) {
                {
                    int __rv = r.readInt32();
                    v.setU(__rv);
                }
            }
            else if (__em.memberId == 2) {
                {
                    double __rv = r.readFloat64();
                    v.setV(__rv);
                }
            }
            else {
                if (__ni >= 0) { r.skip(__ni); }
                else { skipByLc(r, __em.lc); }
            }
        }
        return v;
    }

    @Override
    public byte[] keyHash(MutLeaf sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
