// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.MUTABLE)
public class MutLeaf implements org.omg.dds.topic.TopicType<MutLeaf> {
    @org.zerodds.types.Id(1)
    private int u;
    @org.zerodds.types.Id(2)
    private double v;

    public MutLeaf() {}

    public int getU() { return u; }
    public void setU(int u) { this.u = u; }
    public double getV() { return v; }
    public void setV(double v) { this.v = v; }
}
