// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for MutNest. Generated by zerodds idl-java. */
public final class MutNestTypeSupport implements org.zerodds.cdr.TopicTypeSupport<MutNest> {
    public static final MutNestTypeSupport INSTANCE = new MutNestTypeSupport();

    private MutNestTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::MutNest"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.MUTABLE; }

    @Override
    public byte[] encode(MutNest sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(MutNest sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(MutNest sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        if (w.isXcdr1()) {
            {
                org.zerodds.cdr.Xcdr2Writer __plw10 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw10.writeInt32(sample.getTag());
                w.writePlCdr1Member(10, __plw10.toByteArray());
            }
            {
                org.zerodds.cdr.Xcdr2Writer __plw20 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw20.align(4);
                __plw20.writeBytes(MutLeafTypeSupport.INSTANCE.encode(sample.getLeaf(), endian, __plw20.isXcdr1() ? 0 : 1));
                w.writePlCdr1Member(20, __plw20.toByteArray());
            }
            {
                org.zerodds.cdr.Xcdr2Writer __plw30 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                {
                    java.util.List<MutLeaf> __seq0 = (sample.getList() == null) ? java.util.Collections.<MutLeaf>emptyList() : (sample.getList());
                    int __seqdh0 = __plw30.beginAppendable();
                    __plw30.writeSequenceCount(__seq0.size());
                    for (MutLeaf __el0 : __seq0) {
                        __plw30.align(4);
                        __plw30.writeBytes(MutLeafTypeSupport.INSTANCE.encode(__el0, endian, __plw30.isXcdr1() ? 0 : 1));
                    }
                    __plw30.endDelimited(__seqdh0);
                }
                w.writePlCdr1Member(30, __plw30.toByteArray());
            }
            w.writePlCdr1Sentinel();
        } else {
            int __dh = w.beginMutable();
            w.writeEmHeader(10, org.zerodds.cdr.Xcdr2Writer.LC_INT32, false);
            w.writeInt32(sample.getTag());
            w.writeEmHeader(20, org.zerodds.cdr.Xcdr2Writer.LC_NEXTINT_4, false);
            w.align(4);
            w.writeBytes(MutLeafTypeSupport.INSTANCE.encode(sample.getLeaf(), endian, w.isXcdr1() ? 0 : 1));
            w.writeEmHeader(30, org.zerodds.cdr.Xcdr2Writer.LC_NEXTINT_4, false);
            {
                java.util.List<MutLeaf> __seq0 = (sample.getList() == null) ? java.util.Collections.<MutLeaf>emptyList() : (sample.getList());
                int __seqdh0 = w.beginAppendable();
                w.writeSequenceCount(__seq0.size());
                for (MutLeaf __el0 : __seq0) {
                    w.align(4);
                    w.writeBytes(MutLeafTypeSupport.INSTANCE.encode(__el0, endian, w.isXcdr1() ? 0 : 1));
                }
                w.endDelimited(__seqdh0);
            }
            w.endDelimited(__dh);
        }
        return w.toByteArray();
    }

    @Override
    public MutNest decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public MutNest decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public MutNest decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public MutNest decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static MutNest decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        MutNest v = new MutNest();
        if (r.isXcdr1()) {
            org.zerodds.cdr.Xcdr2Reader.PlCdr1Member __plm;
            while ((__plm = r.beginPlCdr1Member()) != null) {
            if (__plm.memberId == 10) {
                {
                    int __rv = r.readInt32();
                    v.setTag(__rv);
                }
            }
            else if (__plm.memberId == 20) {
                {
                    MutLeaf __rv = MutLeafTypeSupport.decodeFrom(r);
                    v.setLeaf(__rv);
                }
            }
            else if (__plm.memberId == 30) {
                {
                    java.util.List<MutLeaf> __rv;
                    {
                        r.readDHeader();
                        int __cnt0 = r.readSequenceCount();
                        java.util.List<MutLeaf> __out0 = new java.util.ArrayList<>(__cnt0);
                        for (int __si0 = 0; __si0 < __cnt0; __si0++) {
                            MutLeaf __se0 = MutLeafTypeSupport.decodeFrom(r);
                            __out0.add(__se0);
                        }
                        __rv = __out0;
                    }
                    v.setList(__rv);
                }
            }
                r.endPlCdr1Member(__plm);
            }
            return v;
        }
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        while (r.position() < __endPos) {
            org.zerodds.cdr.Xcdr2Reader.EmHeader __em = r.readEmHeader();
            int __ni = (__em.lc == 4) ? r.readNextInt() : -1;
            if (__em.memberId == 10) {
                {
                    int __rv = r.readInt32();
                    v.setTag(__rv);
                }
            }
            else if (__em.memberId == 20) {
                {
                    MutLeaf __rv = MutLeafTypeSupport.decodeFrom(r);
                    v.setLeaf(__rv);
                }
            }
            else if (__em.memberId == 30) {
                {
                    java.util.List<MutLeaf> __rv;
                    {
                        r.readDHeader();
                        int __cnt0 = r.readSequenceCount();
                        java.util.List<MutLeaf> __out0 = new java.util.ArrayList<>(__cnt0);
                        for (int __si0 = 0; __si0 < __cnt0; __si0++) {
                            MutLeaf __se0 = MutLeafTypeSupport.decodeFrom(r);
                            __out0.add(__se0);
                        }
                        __rv = __out0;
                    }
                    v.setList(__rv);
                }
            }
            else {
                if (__ni >= 0) { r.skip(__ni); }
                else { skipByLc(r, __em.lc); }
            }
        }
        return v;
    }

    @Override
    public byte[] keyHash(MutNest sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
