// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.MUTABLE)
public class MutNest implements org.omg.dds.topic.TopicType<MutNest> {
    @org.zerodds.types.Id(10)
    private int tag;
    @org.zerodds.types.Id(20)
    private MutLeaf leaf;
    @org.zerodds.types.Id(30)
    private java.util.List<MutLeaf> list;

    public MutNest() {}

    public int getTag() { return tag; }
    public void setTag(int tag) { this.tag = tag; }
    public MutLeaf getLeaf() { return leaf; }
    public void setLeaf(MutLeaf leaf) { this.leaf = leaf; }
    public java.util.List<MutLeaf> getList() { return list; }
    public void setList(java.util.List<MutLeaf> list) { this.list = list; }
}
