// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Mut. Generated by zerodds idl-java. */
public final class MutTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Mut> {
    public static final MutTypeSupport INSTANCE = new MutTypeSupport();

    private MutTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Mut"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.MUTABLE; }

    @Override
    public byte[] encode(Mut sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Mut sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Mut sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        if (w.isXcdr1()) {
            {
                org.zerodds.cdr.Xcdr2Writer __plw10 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw10.writeInt32(sample.getA());
                w.writePlCdr1Member(10, __plw10.toByteArray());
            }
            {
                org.zerodds.cdr.Xcdr2Writer __plw20 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                __plw20.writeFloat64(sample.getB());
                w.writePlCdr1Member(20, __plw20.toByteArray());
            }
            {
                org.zerodds.cdr.Xcdr2Writer __plw30 = new org.zerodds.cdr.Xcdr2Writer(w.endian(), org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE);
                if (sample.getC() != null && sample.getC().getBytes(java.nio.charset.StandardCharsets.UTF_8).length > 8) throw new IllegalArgumentException("bounded string length exceeds its IDL bound (8)");
                __plw30.writeString(sample.getC());
                w.writePlCdr1Member(30, __plw30.toByteArray());
            }
            w.writePlCdr1Sentinel();
        } else {
            int __dh = w.beginMutable();
            w.writeEmHeader(10, org.zerodds.cdr.Xcdr2Writer.LC_INT32, false);
            w.writeInt32(sample.getA());
            w.writeEmHeader(20, org.zerodds.cdr.Xcdr2Writer.LC_INT64, false);
            w.writeFloat64(sample.getB());
            w.writeEmHeader(30, org.zerodds.cdr.Xcdr2Writer.LC_NEXTINT_4, false);
            if (sample.getC() != null && sample.getC().getBytes(java.nio.charset.StandardCharsets.UTF_8).length > 8) throw new IllegalArgumentException("bounded string length exceeds its IDL bound (8)");
            w.writeString(sample.getC());
            w.endDelimited(__dh);
        }
        return w.toByteArray();
    }

    @Override
    public Mut decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Mut decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Mut decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Mut decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Mut decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Mut v = new Mut();
        if (r.isXcdr1()) {
            org.zerodds.cdr.Xcdr2Reader.PlCdr1Member __plm;
            while ((__plm = r.beginPlCdr1Member()) != null) {
            if (__plm.memberId == 10) {
                {
                    int __rv = r.readInt32();
                    v.setA(__rv);
                }
            }
            else if (__plm.memberId == 20) {
                {
                    double __rv = r.readFloat64();
                    v.setB(__rv);
                }
            }
            else if (__plm.memberId == 30) {
                {
                    String __rv = r.readString();
                    v.setC(__rv);
                }
            }
                r.endPlCdr1Member(__plm);
            }
            return v;
        }
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        while (r.position() < __endPos) {
            org.zerodds.cdr.Xcdr2Reader.EmHeader __em = r.readEmHeader();
            int __ni = (__em.lc == 4) ? r.readNextInt() : -1;
            if (__em.memberId == 10) {
                {
                    int __rv = r.readInt32();
                    v.setA(__rv);
                }
            }
            else if (__em.memberId == 20) {
                {
                    double __rv = r.readFloat64();
                    v.setB(__rv);
                }
            }
            else if (__em.memberId == 30) {
                {
                    String __rv = r.readString();
                    v.setC(__rv);
                }
            }
            else {
                if (__ni >= 0) { r.skip(__ni); }
                else { skipByLc(r, __em.lc); }
            }
        }
        return v;
    }

    @Override
    public byte[] keyHash(Mut sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
