// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for NestedKey. Generated by zerodds idl-java. */
public final class NestedKeyTypeSupport implements org.zerodds.cdr.TopicTypeSupport<NestedKey> {
    public static final NestedKeyTypeSupport INSTANCE = new NestedKeyTypeSupport();

    private NestedKeyTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::NestedKey"; }

    @Override
    public boolean isKeyed() { return true; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.FINAL; }

    @Override
    public byte[] encode(NestedKey sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(NestedKey sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(NestedKey sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        w.writeInt32(sample.getHi());
        w.writeInt32(sample.getLo());
        return w.toByteArray();
    }

    @Override
    public NestedKey decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public NestedKey decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public NestedKey decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public NestedKey decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static NestedKey decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        NestedKey v = new NestedKey();
        {
            int __rv = r.readInt32();
            v.setHi(__rv);
        }
        {
            int __rv = r.readInt32();
            v.setLo(__rv);
        }
        return v;
    }

    @Override
    public byte[] keyHash(NestedKey sample) {
        org.zerodds.cdr.EndianMode endian = org.zerodds.cdr.EndianMode.BIG_ENDIAN;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian);
        w.writeInt32(sample.getHi());
        w.writeInt32(sample.getLo());
        byte[] holder = w.toByteArray();
        if (holder.length <= 16) {
            byte[] h = new byte[16];
            System.arraycopy(holder, 0, h, 0, holder.length);
            return h;
        }
        return org.zerodds.cdr.Md5.hash(holder);
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
