// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Nested
@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.FINAL)
public class NestedKey {
    @org.zerodds.types.Key
    private int hi;
    @org.zerodds.types.Key
    private int lo;

    public NestedKey() {}

    public int getHi() { return hi; }
    public void setHi(int hi) { this.hi = hi; }
    public int getLo() { return lo; }
    public void setLo(int lo) { this.lo = lo; }
}
