// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.FINAL)
public class OuterKey implements org.omg.dds.topic.TopicType<OuterKey> {
    @org.zerodds.types.Key
    private NestedKey k;
    private int payload;

    public OuterKey() {}

    public NestedKey getK() { return k; }
    public void setK(NestedKey k) { this.k = k; }
    public int getPayload() { return payload; }
    public void setPayload(int payload) { this.payload = payload; }
}
