// Generated by zerodds idl-java. Do not edit.
package feat;

public final class Perm {
    /** IDL `@bit_bound(32)` */
    public static final int BIT_BOUND = 32;

    /** Bit-position enum for Perm. */
    public enum Flag {
        READ(0),
        WRITE(1),
        EXEC(2);

        private final int position;
        Flag(int position) { this.position = position; }
        public int position() { return position; }
    }

    private java.util.EnumSet<Flag> bits = java.util.EnumSet.noneOf(Flag.class);

    public Perm() {}

    public java.util.EnumSet<Flag> bits() { return bits; }
    public void setBits(java.util.EnumSet<Flag> bits) { this.bits = java.util.EnumSet.copyOf(bits); }
    public boolean isSet(Flag f) { return bits.contains(f); }
    public void set(Flag f) { bits.add(f); }
    public void clear(Flag f) { bits.remove(f); }
}
