// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class Prim implements org.omg.dds.topic.TopicType<Prim> {
    private byte i8;
    /** unsigned IDL value (Java unsigned-workaround) */
    private short u8;
    private short i16;
    /** unsigned IDL value (Java unsigned-workaround) */
    private int u16;
    private int i32;
    /** unsigned IDL value (Java unsigned-workaround) */
    private long u32;
    private long i64;
    /** unsigned IDL value (Java unsigned-workaround) */
    private long u64;
    private float f32;
    private double f64;
    private boolean b;
    private byte o;
    private char ch;

    public Prim() {}

    public byte getI8() { return i8; }
    public void setI8(byte i8) { this.i8 = i8; }
    public short getU8() { return u8; }
    public void setU8(short u8) { this.u8 = u8; }
    public short getI16() { return i16; }
    public void setI16(short i16) { this.i16 = i16; }
    public int getU16() { return u16; }
    public void setU16(int u16) { this.u16 = u16; }
    public int getI32() { return i32; }
    public void setI32(int i32) { this.i32 = i32; }
    public long getU32() { return u32; }
    public void setU32(long u32) { this.u32 = u32; }
    public long getI64() { return i64; }
    public void setI64(long i64) { this.i64 = i64; }
    public long getU64() { return u64; }
    public void setU64(long u64) { this.u64 = u64; }
    public float getF32() { return f32; }
    public void setF32(float f32) { this.f32 = f32; }
    public double getF64() { return f64; }
    public void setF64(double f64) { this.f64 = f64; }
    public boolean getB() { return b; }
    public void setB(boolean b) { this.b = b; }
    public byte getO() { return o; }
    public void setO(byte o) { this.o = o; }
    public char getCh() { return ch; }
    public void setCh(char ch) { this.ch = ch; }
}
