// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Prim. Generated by zerodds idl-java. */
public final class PrimTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Prim> {
    public static final PrimTypeSupport INSTANCE = new PrimTypeSupport();

    private PrimTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Prim"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Prim sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Prim sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Prim sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        w.writeOctet(sample.getI8());
        w.writeUInt8(sample.getU8());
        w.writeInt16(sample.getI16());
        w.writeUInt16(sample.getU16());
        w.writeInt32(sample.getI32());
        w.writeUInt32(sample.getU32());
        w.writeInt64(sample.getI64());
        w.writeUInt64(sample.getU64());
        w.writeFloat32(sample.getF32());
        w.writeFloat64(sample.getF64());
        w.writeBoolean(sample.getB());
        w.writeOctet(sample.getO());
        w.writeChar(sample.getCh());
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Prim decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Prim decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Prim decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Prim decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Prim decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Prim v = new Prim();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            byte __rv = r.readOctet();
            v.setI8(__rv);
        }
        {
            short __rv = (short) r.readUInt8();
            v.setU8(__rv);
        }
        {
            short __rv = r.readInt16();
            v.setI16(__rv);
        }
        {
            int __rv = r.readUInt16();
            v.setU16(__rv);
        }
        {
            int __rv = r.readInt32();
            v.setI32(__rv);
        }
        {
            long __rv = r.readUInt32();
            v.setU32(__rv);
        }
        {
            long __rv = r.readInt64();
            v.setI64(__rv);
        }
        {
            long __rv = r.readUInt64();
            v.setU64(__rv);
        }
        {
            float __rv = r.readFloat32();
            v.setF32(__rv);
        }
        {
            double __rv = r.readFloat64();
            v.setF64(__rv);
        }
        {
            boolean __rv = r.readBoolean();
            v.setB(__rv);
        }
        {
            byte __rv = r.readOctet();
            v.setO(__rv);
        }
        {
            char __rv = r.readChar();
            v.setCh(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(Prim sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
