// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Pt. Generated by zerodds idl-java. */
public final class PtTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Pt> {
    public static final PtTypeSupport INSTANCE = new PtTypeSupport();

    private PtTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Pt"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Pt sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Pt sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Pt sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        w.writeInt32(sample.getX());
        w.writeInt32(sample.getY());
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Pt decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Pt decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Pt decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Pt decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Pt decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Pt v = new Pt();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            int __rv = r.readInt32();
            v.setX(__rv);
        }
        {
            int __rv = r.readInt32();
            v.setY(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(Pt sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
