// Generated by zerodds idl-java. Do not edit.
package feat;

public sealed interface Sel permits Sel.P, Sel.N, Sel.Z {
    // case 1 -> p
    // case 2 -> n
    // case default -> z

    record P(Pt p) implements Sel {}
    record N(int n) implements Sel {}
    record Z(byte z) implements Sel {}
}
