// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for union Sel. Generated by zerodds idl-java. */
public final class SelTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Sel> {
    public static final SelTypeSupport INSTANCE = new SelTypeSupport();
    private SelTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Sel"; }
    @Override
    public boolean isKeyed() { return false; }
    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Sel sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    @Override
    public byte[] encode(Sel sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }
    public byte[] encode(Sel sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        if (sample instanceof Sel.P __cv) {
            w.writeInt32(1);
            w.align(4);
            w.writeBytes(PtTypeSupport.INSTANCE.encode(__cv.p(), endian, w.isXcdr1() ? 0 : 1));
        } else if (sample instanceof Sel.N __cv) {
            w.writeInt32(2);
            w.writeInt32(__cv.n());
        } else if (sample instanceof Sel.Z __cv) {
            w.writeInt32(3);
            w.writeOctet(__cv.z());
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Sel decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }
    @Override
    public Sel decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Sel decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Sel decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Sel decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        r.readDHeader();
        int __disc = r.readInt32();
        if (__disc == (1)) {
            Pt __uv = PtTypeSupport.decodeFrom(r);
            return new Sel.P(__uv);
        } else if (__disc == (2)) {
            int __uv = r.readInt32();
            return new Sel.N(__uv);
        } else {
            byte __uv = r.readOctet();
            return new Sel.Z(__uv);
        }
    }

    @Override
    public byte[] keyHash(Sel sample) { return new byte[16]; }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
