// Generated by zerodds idl-java. Do not edit.
package feat;

@org.zerodds.types.Extensibility(org.zerodds.types.Extensibility.Kind.APPENDABLE)
public class Tree implements org.omg.dds.topic.TopicType<Tree> {
    private int value;
    private java.util.List<Tree> kids;

    public Tree() {}

    public int getValue() { return value; }
    public void setValue(int value) { this.value = value; }
    public java.util.List<Tree> getKids() { return kids; }
    public void setKids(java.util.List<Tree> kids) { this.kids = kids; }
}
