// Generated by zerodds idl-java. Do not edit.
package feat;

/** XCDR2 TypeSupport for Tree. Generated by zerodds idl-java. */
public final class TreeTypeSupport implements org.zerodds.cdr.TopicTypeSupport<Tree> {
    public static final TreeTypeSupport INSTANCE = new TreeTypeSupport();

    private TreeTypeSupport() {}

    @Override
    public String getTypeName() { return "feat::Tree"; }

    @Override
    public boolean isKeyed() { return false; }

    @Override
    public org.zerodds.cdr.ExtensibilityKind getExtensibility() { return org.zerodds.cdr.ExtensibilityKind.APPENDABLE; }

    @Override
    public byte[] encode(Tree sample) { return encode(sample, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }

    @Override
    public byte[] encode(Tree sample, org.zerodds.cdr.EndianMode endian) { return encode(sample, endian, 1); }

    public byte[] encode(Tree sample, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Writer.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Writer w = new org.zerodds.cdr.Xcdr2Writer(endian, __maxAlign);
        int __dh = w.beginAppendable();
        w.writeInt32(sample.getValue());
        {
            java.util.List<Tree> __seq0 = (sample.getKids() == null) ? java.util.Collections.<Tree>emptyList() : (sample.getKids());
            int __seqdh0 = w.beginAppendable();
            w.writeSequenceCount(__seq0.size());
            for (Tree __el0 : __seq0) {
                w.align(4);
                w.writeBytes(TreeTypeSupport.INSTANCE.encode(__el0, endian, w.isXcdr1() ? 0 : 1));
            }
            w.endDelimited(__seqdh0);
        }
        w.endDelimited(__dh);
        return w.toByteArray();
    }

    @Override
    public Tree decode(byte[] bytes) { return decode(bytes, 0, bytes.length); }

    @Override
    public Tree decode(byte[] bytes, int offset, int length) { return decode(bytes, offset, length, org.zerodds.cdr.EndianMode.LITTLE_ENDIAN); }
    public Tree decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian) { return decode(bytes, offset, length, endian, 1); }
    public Tree decode(byte[] bytes, int offset, int length, org.zerodds.cdr.EndianMode endian, int representation) {
        int __maxAlign = representation == 0 ? org.zerodds.cdr.Xcdr2Reader.XCDR1_MAX_ALIGN_VALUE : 4;
        org.zerodds.cdr.Xcdr2Reader r = new org.zerodds.cdr.Xcdr2Reader(bytes, offset, length, endian, __maxAlign);
        return decodeFrom(r);
    }

    public static Tree decodeFrom(org.zerodds.cdr.Xcdr2Reader r) {
        Tree v = new Tree();
        int __dhSize = r.readDHeader();
        int __endPos = r.position() + __dhSize;
        {
            int __rv = r.readInt32();
            v.setValue(__rv);
        }
        {
            java.util.List<Tree> __rv;
            {
                r.readDHeader();
                int __cnt0 = r.readSequenceCount();
                java.util.List<Tree> __out0 = new java.util.ArrayList<>(__cnt0);
                for (int __si0 = 0; __si0 < __cnt0; __si0++) {
                    Tree __se0 = TreeTypeSupport.decodeFrom(r);
                    __out0.add(__se0);
                }
                __rv = __out0;
            }
            v.setKids(__rv);
        }
        while (r.position() < __endPos) { r.skip(1); }
        return v;
    }

    @Override
    public byte[] keyHash(Tree sample) {
        return new byte[16];
    }

    private static void skipByLc(org.zerodds.cdr.Xcdr2Reader r, int lc) {
        switch (lc) {
            case 0: r.skip(1); break;
            case 1: r.skip(2); break;
            case 2: r.skip(4); break;
            case 3: r.skip(8); break;
            default: { int __n = r.readNextInt(); r.skip(__n); break; }
        }
    }

    private static byte[] readDelimitedFrame(org.zerodds.cdr.Xcdr2Reader r) {
        int __sz = r.readDHeader();
        byte[] __body = r.readBytes(__sz);
        byte[] __frame = new byte[4 + __sz];
        __frame[0] = (byte) (__sz & 0xFF); __frame[1] = (byte) ((__sz >>> 8) & 0xFF);
        __frame[2] = (byte) ((__sz >>> 16) & 0xFF); __frame[3] = (byte) ((__sz >>> 24) & 0xFF);
        System.arraycopy(__body, 0, __frame, 4, __sz);
        return __frame;
    }
}
