// Generated by zerodds idl-csharp. Do not edit.
// Target: C# 12.0 / .NET 8+
#nullable enable

using Omg.Types;
using System;
using ZeroDDS.Cdr;

namespace sensor_msgs
{
    namespace msg
    {
        public partial record class Temperature : ITopicType<Temperature>
        {
            public int Celsius { get; init; } = default!;
            public string SensorId { get; init; } = default!;
        }

        public sealed class TemperatureTypeSupport : IDdsTopicType<Temperature>
        {
            public static readonly TemperatureTypeSupport Instance = new();

            public string TypeName => "sensor_msgs::msg::Temperature";
            public bool IsKeyed => false;
            public ExtensibilityKind Extensibility => ExtensibilityKind.Appendable;

            public byte[] Encode(Temperature sample) => Encode(sample, EndianMode.LittleEndian);

            public byte[] Encode(Temperature sample, EndianMode endian)
            {
                var w = new Xcdr2Writer(endian);
                EncodeInto(w, sample);
                return w.ToArray();
            }

            public void EncodeInto(Xcdr2Writer w, Temperature sample)
            {
                using (var __scope = w.BeginAppendable())
                {
                    w.WriteInt32(sample.Celsius);
                    w.WriteString(sample.SensorId);
                }
            }

            public Temperature Decode(ReadOnlySpan<byte> bytes)
            {
                var r = new Xcdr2Reader(bytes, EndianMode.LittleEndian);
                return DecodeFrom(r);
            }

            public Temperature DecodeFrom(Xcdr2Reader r)
            {
                var __scope = r.BeginDHeader();
                int __m0 = default;
                __m0 = r.ReadInt32();
                string __m1 = default;
                __m1 = r.ReadString();
                r.EndDHeader(__scope);
                return new Temperature
                {
                    Celsius = __m0!,
                    SensorId = __m1!,
                };
            }

            public byte[] KeyHash(Temperature sample)
            {
                return new byte[16];
            }
        }

    } // namespace msg
} // namespace sensor_msgs

